#!/usr/bin/env python3
"""
Auto-generated bracket data for March Madness Agent Swarm 2026.
Source: NCAA.com, ESPN, Yahoo Sports (March 15, 2026)

First Four games:
- West 11: NC State vs Texas
- Midwest 16: UMBC vs Howard
- Midwest 11: SMU vs Miami OH
- South 16: Lehigh vs Prairie View A&M
"""

BRACKET_2026 = {
  "East": [
    {
      "name": "Duke",
      "seed": 1,
      "region": "East",
      "adj_o": 126.7,
      "adj_d": 87.1,
      "adj_tempo": 70.0,
      "record": "32-2",
      "conference": "ACC",
      "kenpom_rank": 1,
      "three_pt_pct": 37.8,
      "last_10_record": "10-0",
      "current_streak": "W11",
      "conference_tourney_result": "ACC Champion (beat FSU, beat Clemson, beat Virginia 74-70 in final)",
      "recent_form_notes": "11-game win streak, ACC regular season + tourney champs, #1 overall seed with Cameron Boozer dominant all season",
      "injury_notes": "Caleb Foster (G) \u2014 fractured foot in regular season finale vs UNC, had surgery. Likely OUT unless Duke makes deep run. Averaged 8.5 PPG, elite perimeter defender. Also Patrick Ngongba II questionable with foot soreness.",
      "key_players": "1. Cameron Boozer (F, Fr, 22.5 PPG, 10.2 RPG, 4.2 APG) \u2014 primary scorer, double-double machine [NBA]; 2. Isaiah Evans (G, So, 14.9 PPG) \u2014 secondary scorer, 3PT specialist wing [NBA]; 5. Cayden Boozer (G, Fr, 7.1 PPG) \u2014 playmaker, stepped into starting PG a... [NBA]. MISSING: Patrick Ngongba II (10.7 PPG, 6.0 RPG) \u2014 Right foot soreness; missed ACC Tournament, expected back for NCAAs; MISSING: Caleb Foster (8.5 PPG, 3.6 RPG) \u2014 Fractured right foot, had surgery, likely OUT",
      "experience_score": 3.0,
      "rest_days": 3,
      "travel_distance_miles": 476.0,
      "turnover_rate": 10.5,
      "opp_fg_pct": 0.392
    },
    {
      "name": "Ohio State",
      "seed": 8,
      "region": "East",
      "adj_o": 125.3,
      "adj_d": 91.4,
      "adj_tempo": 70.6,
      "record": "21-12",
      "conference": "Big Ten",
      "kenpom_rank": 26,
      "three_pt_pct": 36.3,
      "last_10_record": "6-4",
      "current_streak": "L1",
      "conference_tourney_result": "Big Ten Quarterfinals -- beat Iowa 72-69 (3rd Rd), lost to Michigan 71-67 (QF)",
      "recent_form_notes": "Ohio State (21-12) ended a three-year NCAA Tournament drought and played competitive games in the Big Ten Tournament, but have been inconsistent down the stretch with four losses in their last ten.",
      "key_players": "1. Bruce Thornton (G, Sr, 20.2 PPG, 5.1 RPG) \u2014 primary scorer, floor general, team l... [NBA]; 2. John Mobley Jr. (G, So, 15.7 PPG) \u2014 secondary scorer, elite 3PT specialist [NBA]; 3. Devin Royal (F, Jr, 13.7 PPG, 5.7 RPG) \u2014 versatile forward, inside-outside threat [NBA]; 4. Christoph Tilly (C, Sr, 11.0 PPG) \u2014 interior scorer, rim protector; 5. Amare Bynum (F, Fr, 9.7 PPG) \u2014 sixth man, energy forward",
      "experience_score": 5.0,
      "rest_days": 3,
      "travel_distance_miles": 292.0,
      "turnover_rate": 10.4,
      "opp_fg_pct": 0.439
    },
    {
      "name": "TCU",
      "seed": 9,
      "region": "East",
      "adj_o": 118.4,
      "adj_d": 88.8,
      "adj_tempo": 70.9,
      "record": "22-11",
      "conference": "Big 12",
      "kenpom_rank": 43,
      "three_pt_pct": 34.9,
      "last_10_record": "6-4",
      "current_streak": "L1",
      "conference_tourney_result": "Big 12 Quarterfinals -- beat Oklahoma State 95-88 (2nd Rd), lost to Kansas 78-73 (QF)",
      "recent_form_notes": "TCU (22-11) earned their first winning Big 12 record at 11-7 and returned to the Dance for the fourth time in five years; fell to Kansas in the Big 12 quarters but had a solid overall campaign.",
      "key_players": "1. David Punch (F, So, 13.6 PPG, 6.6 RPG) \u2014 primary interior scorer, physical for... [NBA]; 2. Xavier Edmonds (F, Jr, 12.8 PPG, 6.6 RPG) \u2014 efficient forward, double-double threat; 3. Micah Robinson (F, So, 10.6 PPG) \u2014 athletic 6-6 wing; 4. Jayden Pierre (G, Sr, 10.4 PPG) \u2014 floor general, Providence transfer; 5. Kayden Edwards (G, Fr, 8.5 PPG) \u2014 four-star freshman combo guard",
      "experience_score": 4.0,
      "rest_days": 3,
      "travel_distance_miles": 1226.0,
      "turnover_rate": 10.9,
      "opp_fg_pct": 0.446
    },
    {
      "name": "St. John's",
      "seed": 5,
      "region": "East",
      "adj_o": 122.4,
      "adj_d": 87.9,
      "adj_tempo": 66.4,
      "record": "28-6",
      "conference": "Big East",
      "kenpom_rank": 16,
      "three_pt_pct": 35.5,
      "last_10_record": "9-1",
      "current_streak": "W6",
      "conference_tourney_result": "Big East Champion -- beat Providence 85-72 (QF), Seton Hall 78-68 (SF), UConn 72-52 (Final)",
      "recent_form_notes": "St. John's won its second consecutive Big East regular season and tournament titles, dominating UConn 72-52 in the final behind Zuby Ejiofor's 18 pts/9 reb/7 blk; the Red Storm never trailed in the tournament and are rolling into March.",
      "key_players": "1. Zuby Ejiofor (F/C, Sr, 16.3 PPG, 7.1 RPG) \u2014 primary scorer, Big East POY, defensi... [NBA]; 2. Bryce Hopkins (F, Sr, 13.5 PPG, 6.2 RPG) \u2014 secondary scorer, versatile forward; 3. Oziyah Sellers (G, Sr, 10.7 PPG) \u2014 3PT specialist, perimeter shooter; 4. Ian Jackson (G, So, 9.6 PPG) \u2014 scoring guard, developing wing [NBA]; 5. Joson Sanon (G, So, 8.3 PPG) \u2014 sixth man, spark-plug guard",
      "experience_score": 6.0,
      "rest_days": 3,
      "travel_distance_miles": 302.0,
      "turnover_rate": 10.5,
      "opp_fg_pct": 0.421
    },
    {
      "name": "Northern Iowa",
      "seed": 12,
      "region": "East",
      "adj_o": 110.7,
      "adj_d": 89.0,
      "adj_tempo": 67.7,
      "record": "23-12",
      "conference": "MVC",
      "kenpom_rank": 71,
      "three_pt_pct": 32.0,
      "last_10_record": "7-3",
      "current_streak": "W4",
      "conference_tourney_result": "MVC Champion (Arch Madness) -- won four games in four days including 84-69 over UIC in Final",
      "recent_form_notes": "Northern Iowa (23-12) became the lowest seed (6th) to ever win Arch Madness, winning four games in four days; Trey Campbell earned MOS honors and the Panthers are dancing for the ninth time in program history.",
      "key_players": "1. Trey Campbell (G, Sr, 13.2 PPG) \u2014 leading scorer, All-MVC, 50 steals; 2. Leon Bond III (G, Jr, 11.5 PPG, 5.0 RPG) \u2014 All-MVC, All-Defensive, Virginia tran...; 3. Will Hornseth (F, Gr, 11.3 PPG) \u2014 experienced 6-6 grad forward; 4. Tristan Smith (F, Sr, 9.9 PPG, 5.3 RPG) \u2014 physical forward, rebounder; 5. Max Weisbrod (G, Sr, 5.1 PPG) \u2014 bench sharpshooter, 39.6% 3PT",
      "experience_score": 8.0,
      "rest_days": 3,
      "travel_distance_miles": 689.0,
      "turnover_rate": 9.3,
      "opp_fg_pct": 0.407
    },
    {
      "name": "Kansas",
      "seed": 4,
      "region": "East",
      "adj_o": 121.0,
      "adj_d": 87.8,
      "adj_tempo": 67.4,
      "record": "23-10",
      "conference": "Big 12",
      "kenpom_rank": 21,
      "three_pt_pct": 34.3,
      "last_10_record": "6-4",
      "current_streak": "L1",
      "conference_tourney_result": "Lost Big 12 SF to Houston 47-69 (beat TCU 78-73 in QF, then blown out by 22 in semis)",
      "recent_form_notes": "Inconsistent 4-4 down the stretch, then embarrassed by Houston in Big 12 SF \u2014 limping into NCAAs",
      "key_players": "1. Darryn Peterson (G, Fr, 19.8 PPG) \u2014 primary scorer, one-and-done star [NBA]; 2. Tre White (G/F, Sr, 13.8 PPG, 6.7 RPG) \u2014 secondary scorer, floor spacer [NBA]; 3. Flory Bidunga (F/C, So, 13.5 PPG, 9.2 RPG) \u2014 rim protector, DPOY candidate, elite ... [NBA]; 4. Melvin Council Jr. (G, Sr, 12.9 PPG, 5.1 APG) \u2014 floor general, lead facilitator; 5. Bryson Tiller (F, Fr, 8.2 PPG, 6.0 RPG) \u2014 versatile forward, rebounder [NBA]",
      "experience_score": 4.0,
      "rest_days": 4,
      "travel_distance_miles": 895.0,
      "turnover_rate": 10.7,
      "opp_fg_pct": 0.388
    },
    {
      "name": "Cal Baptist",
      "seed": 13,
      "region": "East",
      "adj_o": 106.7,
      "adj_d": 91.1,
      "adj_tempo": 67.1,
      "record": "25-8",
      "conference": "WAC",
      "kenpom_rank": 106,
      "three_pt_pct": 32.0,
      "last_10_record": "8-2",
      "current_streak": "W3",
      "conference_tourney_result": "WAC Champion -- beat Utah Valley 63-61 (Final) on Dominique Daniels Jr.'s clutch 3-pointer",
      "recent_form_notes": "Cal Baptist (25-8) stunned top-seeded Utah Valley in the WAC final after erasing a 7-point deficit, earning the program's first-ever NCAA Division I Tournament appearance; Dominique Daniels Jr. was tournament MVP.",
      "key_players": "1. Dominique Daniels Jr. (G, Gr, 23.2 PPG) \u2014 WAC POY, top-10 national scorer, 47-p...; 2. Martel Williams (G, Sr, 14.1 PPG) \u2014 second scorer, reliable guard; 3. Jayden Jackson (G, Jr, 7.5 PPG) \u2014 versatile 6-4 guard; 4. Thomas Ndong (F, Jr, 6.8 PPG, 7.1 RPG) \u2014 6-10 OSU transfer, primary rebounder; 5. Jordan Muller (G, Fr, 5.8 PPG) \u2014 freshman, WAC All-Freshman Team",
      "experience_score": 8.0,
      "rest_days": 3,
      "travel_distance_miles": 2156.0,
      "turnover_rate": 12.4,
      "opp_fg_pct": 0.417
    },
    {
      "name": "Louisville",
      "seed": 6,
      "region": "East",
      "adj_o": 125.0,
      "adj_d": 89.0,
      "adj_tempo": 67.5,
      "record": "23-10",
      "conference": "ACC",
      "kenpom_rank": 19,
      "three_pt_pct": 35.0,
      "last_10_record": "7-3",
      "current_streak": "L1",
      "conference_tourney_result": "ACC Quarterfinals -- beat SMU 62-58 (2nd Rd), lost to Miami 78-73 (QF)",
      "recent_form_notes": "Louisville finished 23-10 with strong individual play from Mikel Brown Jr. and J'Vonne Hadley but stumbled in the ACC quarters against Miami; solid resume but inconsistent down the stretch.",
      "injury_notes": "Mikel Brown Jr. (PG) \u2014 recurring back injury, sat out ACC Tournament. Averaged 18.2 PPG (25.5 over last 10 healthy games). Goal is to be 100% for NCAA first round but status uncertain.",
      "key_players": "1. Ryan Conwell (G, Sr, 18.7 PPG) \u2014 primary scorer, elite shot-maker [NBA]; 3. J'Vonne Hadley (G, Sr, 11.8 PPG, 5.2 RPG) \u2014 versatile two-way wing, highly efficient; 4. Isaac McKneely (G, Sr, 10.6 PPG) \u2014 3PT specialist, floor spacer; 5. Sananda Fru (F, Jr, 9.2 PPG, 6.0 RPG) \u2014 interior finisher, ultra-efficient re.... MISSING: Mikel Brown Jr. (18.2 PPG, 3.3 RPG) \u2014 Lower back injury; missed ACC Tournament; hoping to return for NCAAs",
      "experience_score": 6.0,
      "rest_days": 4,
      "travel_distance_miles": 577.0,
      "turnover_rate": 11.6,
      "opp_fg_pct": 0.424
    },
    {
      "name": "USF",
      "seed": 11,
      "region": "East",
      "adj_o": 120.9,
      "adj_d": 91.0,
      "adj_tempo": 67.6,
      "record": "25-8",
      "conference": "AAC",
      "kenpom_rank": 49,
      "three_pt_pct": 33.9,
      "last_10_record": "8-2",
      "current_streak": "W4",
      "conference_tourney_result": "AAC Champion -- beat Charlotte (SF), beat Wichita State 70-55 (Final)",
      "recent_form_notes": "South Florida (25-8) won its first conference tournament title since 1990 and earned its first NCAA Tournament bid since 2012, dominating Wichita State 70-55 in the AAC final; riding a four-game winning streak and playing their best basketball of the season.",
      "key_players": "1. Wes Enis (G, Jr, 16.5 PPG) \u2014 leading scorer, AAC Tourney MOP, 100+ 3s; 2. Izaiyah Nelson (F, Sr, 15.8 PPG, 9.8 RPG) \u2014 AAC POY, near double-double avg, 18 DD; 3. Joseph Pinion (G, Sr, 14.2 PPG) \u2014 elite 3PT (39.1%), career-high season; 4. Josh Omojafo (G, Sr, 11.7 PPG, 5.2 RPG) \u2014 versatile 6-5 guard, strong rebounder; 5. CJ Brown (G, So, 11.4 PPG) \u2014 sophomore guard, playmaker",
      "experience_score": 7.0,
      "rest_days": 4,
      "travel_distance_miles": 919.0,
      "turnover_rate": 11.2,
      "opp_fg_pct": 0.413
    },
    {
      "name": "Michigan State",
      "seed": 3,
      "region": "East",
      "adj_o": 124.5,
      "adj_d": 88.0,
      "adj_tempo": 68.7,
      "record": "25-7",
      "conference": "Big Ten",
      "kenpom_rank": 9,
      "three_pt_pct": 36.7,
      "last_10_record": "7-3",
      "current_streak": "L1",
      "conference_tourney_result": "Lost Big Ten QF to UCLA 84-88 (trailed by 15 in 2nd half, Fears had 21pts/13ast in loss)",
      "recent_form_notes": "Lost 3 of last 4 before tourney, early Big Ten exit despite 28 straight NCAA appearances",
      "key_players": "1. Jeremy Fears Jr. (G, Jr, 15.7 PPG, 9.2 APG) \u2014 floor general, elite playmaker (9.2 APG) [NBA]; 2. Jaxon Kohler (F, Sr, 12.7 PPG, 9.0 RPG) \u2014 secondary scorer, lead rebounder, ski...; 3. Coen Carr (F, Jr, 11.6 PPG, 5.4 RPG) \u2014 athletic slasher, rim protector, elit... [NBA]; 4. Carson Cooper (C, Sr, 10.8 PPG, 7.1 RPG) \u2014 rim protector, interior anchor; 5. Kur Teng (G, So, 7.7 PPG) \u2014 sixth man, 3PT specialist off bench",
      "experience_score": 7.0,
      "rest_days": 6,
      "travel_distance_miles": 519.0,
      "turnover_rate": 11.5,
      "opp_fg_pct": 0.41
    },
    {
      "name": "North Dakota State",
      "seed": 14,
      "region": "East",
      "adj_o": 113.8,
      "adj_d": 97.4,
      "adj_tempo": 66.2,
      "record": "27-7",
      "conference": "Summit",
      "kenpom_rank": 113,
      "three_pt_pct": 32.9,
      "last_10_record": "9-1",
      "current_streak": "W5",
      "conference_tourney_result": "Summit League Champion -- beat North Dakota 70-62 in Final",
      "recent_form_notes": "North Dakota State (27-7) set a school record for wins while sweeping the Summit League regular season and tournament titles; Damari Wheeler-Thomas earned tournament MVP as the Bison dominated from start to finish.",
      "key_players": "1. Damari Wheeler-Thomas (G, Jr, 14.4 PPG) \u2014 All-Summit League, 1000+ career pts; 2. Trevian Carson (G, Jr, 12.4 PPG, 5.0 RPG) \u2014 All-Summit First Team, JUCO transfer; 3. Treyson Anderson (F, So, 10.6 PPG, 5.8 RPG) \u2014 6-9 interior scorer and rebounder; 4. Andy Stefonowicz (G, So, 9.2 PPG, 4.7 APG) \u2014 PG, primary facilitator, 11-assist game; 5. Noah Feddersen (F, So, 8.5 PPG) \u2014 Summit League 6MOY, 6-10 shot blocker",
      "experience_score": 4.0,
      "rest_days": 4,
      "travel_distance_miles": 1181.0,
      "turnover_rate": 10.8,
      "opp_fg_pct": 0.438
    },
    {
      "name": "UCLA",
      "seed": 7,
      "region": "East",
      "adj_o": 124.8,
      "adj_d": 91.5,
      "adj_tempo": 66.7,
      "record": "23-11",
      "conference": "Big Ten",
      "kenpom_rank": 27,
      "three_pt_pct": 37.9,
      "last_10_record": "7-3",
      "current_streak": "L1",
      "conference_tourney_result": "Big Ten Semifinals -- beat Rutgers 72-59 (3rd Rd), beat Michigan State 88-84 (QF), lost to Purdue 73-66 (SF)",
      "recent_form_notes": "UCLA went on a strong Big Ten Tournament run including Donovan Dent's historic triple-double vs Rutgers, but lost Tyler Bilodeau to injury and fell to Purdue in the semis; enter the NCAAs at 23-11 with some momentum but injury concerns.",
      "key_players": "1. Tyler Bilodeau (F, Sr, 17.6 PPG, 5.6 RPG) \u2014 primary scorer, stretch-four, elite e... [NBA]; 2. Donovan Dent (G, Sr, 13.5 PPG, 7.6 APG) \u2014 floor general, elite playmaker (7.6 APG) [NBA]; 3. Trent Perry (G, So, 12.7 PPG) \u2014 secondary scorer, 3PT threat; 4. Skyy Clark (G, Sr, 11.7 PPG) \u2014 3PT specialist, floor spacer; 5. Eric Dailey Jr. (F, Jr, 11.3 PPG, 5.8 RPG) \u2014 versatile two-way wing [NBA]",
      "experience_score": 7.0,
      "rest_days": 4,
      "travel_distance_miles": 2398.0,
      "turnover_rate": 8.9,
      "opp_fg_pct": 0.433
    },
    {
      "name": "UCF",
      "seed": 10,
      "region": "East",
      "adj_o": 122.8,
      "adj_d": 95.5,
      "adj_tempo": 67.3,
      "record": "21-11",
      "conference": "Big 12",
      "kenpom_rank": 54,
      "three_pt_pct": 35.2,
      "last_10_record": "5-5",
      "current_streak": "L1",
      "conference_tourney_result": "Big 12 Quarterfinals -- beat Cincinnati 66-65 OT (2nd Rd), lost to Arizona 81-59 (QF)",
      "recent_form_notes": "UCF (21-11) made the NCAA Tournament for the first time as a Big 12 member; the overtime win over Cincinnati clinched their at-large bid but they were blown out by Arizona in the quarterfinals.",
      "key_players": "1. Riley Kugel (G, Sr, 14.4 PPG) \u2014 senior guard, Miss St transfer; 2. Themus Fulks (G, Sr, 14.4 PPG, 6.8 APG) \u2014 All-Big 12, UCF assists record, floor...; 3. Jordan Burks (F, Jr, 13.4 PPG) \u2014 6-9 Georgetown transfer, versatile; 4. Jamichael Stillwell (F, Sr, 12.4 PPG, 9.1 RPG) \u2014 dominant rebounder (9.1 RPG), interio...; 5. George Beale Jr. (G, Sr, 7.2 PPG) \u2014 sixth man, perimeter shooter",
      "experience_score": 8.0,
      "rest_days": 4,
      "travel_distance_miles": 856.0,
      "turnover_rate": 11.2,
      "opp_fg_pct": 0.456
    },
    {
      "name": "UConn",
      "seed": 2,
      "region": "East",
      "adj_o": 123.9,
      "adj_d": 87.8,
      "adj_tempo": 70.4,
      "record": "29-5",
      "conference": "Big East",
      "kenpom_rank": 12,
      "three_pt_pct": 35.9,
      "last_10_record": "8-2",
      "current_streak": "L1",
      "conference_tourney_result": "Big East Runner-Up (beat Xavier 93-68 QF, beat Georgetown 67-51 SF, lost to St. John's 52-72 in final)",
      "recent_form_notes": "Had 18-game win streak Nov-Feb but demolished by 20 in Big East final by St. John's",
      "key_players": "1. Tarris Reed Jr. (F, Sr, 13.7 PPG, 8.1 RPG) \u2014 interior anchor, dominant finisher (.... [NBA]; 2. Solomon Ball (G, Jr, 13.5 PPG) \u2014 secondary scorer, shooting guard [NBA]; 3. Alex Karaban (F, Sr, 12.6 PPG, 5.2 RPG) \u2014 stretch-four, two-time national champ... [NBA]; 4. Braylon Mullins (G, Fr, 12.0 PPG) \u2014 freshman scorer, McDonald's All-American [NBA]. MISSING: Silas Demary Jr. (10.9 PPG, 4.5 RPG) \u2014 Left ankle sprain in Big East final; out of boot, expected to play",
      "experience_score": 6.0,
      "rest_days": 4,
      "travel_distance_miles": 199.0,
      "turnover_rate": 11.2,
      "opp_fg_pct": 0.402
    },
    {
      "name": "Furman",
      "seed": 15,
      "region": "East",
      "adj_o": 105.7,
      "adj_d": 102.4,
      "adj_tempo": 64.9,
      "record": "22-12",
      "conference": "SoCon",
      "kenpom_rank": 190,
      "three_pt_pct": 34.4,
      "last_10_record": "7-3",
      "current_streak": "W3",
      "conference_tourney_result": "SoCon Champion -- beat ETSU 76-61 in Final as 5th seed (upset of regular-season champ)",
      "recent_form_notes": "Furman (22-12) shocked top-seeded ETSU 76-61 in the SoCon final, shooting 50.9% from the field; Alex Wilkins was tournament MOP and Cooper Bowser had 21 points as the Paladins earned a No. 15 seed for the second time in four years.",
      "key_players": "1. Alex Wilkins (G, Fr, 17.7 PPG, 4.9 APG) \u2014 star freshman PG, 34-pt game [NBA]; 2. Cooper Bowser (F, Jr, 13.4 PPG, 6.3 RPG) \u2014 6-11 forward, team block leader; 3. Asa Thomas (G, So, 13.1 PPG) \u2014 6-7 Clemson transfer, versatile wing; 4. Charles Johnston (F, Sr, 10.1 PPG, 9.2 RPG) \u2014 6-11 Australian center, leading rebou...; 5. Gunnar Lewis (G, Sr, 8.5 PPG) \u2014 6-7 FSU transfer, floor spacer",
      "experience_score": 4.0,
      "rest_days": 4,
      "travel_distance_miles": 528.0,
      "turnover_rate": 11.9,
      "opp_fg_pct": 0.425
    },
    {
      "name": "Siena",
      "seed": 16,
      "region": "East",
      "adj_o": 104.9,
      "adj_d": 101.8,
      "adj_tempo": 64.1,
      "record": "23-11",
      "conference": "MAAC",
      "kenpom_rank": 192,
      "three_pt_pct": 31.5,
      "last_10_record": "8-2",
      "current_streak": "W4",
      "conference_tourney_result": "MAAC Champion -- beat Merrimack 64-54 in Final",
      "recent_form_notes": "Siena (23-11) won its seventh MAAC title and first since 2020, defeating top-seeded Merrimack behind Gavin Doty's 23 points; the Saints earned their first NCAA Tournament berth since 2010.",
      "key_players": "1. Gavin Doty (G, So, 17.9 PPG, 7.0 RPG) \u2014 leading scorer and rebounder, 31-pt game; 2. Justice Shoats (G, Sr, 13.2 PPG, 4.4 APG) \u2014 senior PG, assist leader, 26 in MAAC ...; 3. Brendan Coyle (F, Sr, 12.8 PPG) \u2014 stretch four, 22 double-figure games; 5. Antonio Chandler (F, Gr, 6.7 PPG, 5.7 RPG) \u2014 grad transfer, interior rebounder. MISSING: Tasman Goodrick (9.7 PPG, 7.3 RPG) \u2014 Season-ending knee injury since December 2025",
      "experience_score": 7.0,
      "rest_days": 3,
      "travel_distance_miles": 260.0,
      "turnover_rate": 10.3,
      "opp_fg_pct": 0.422
    }
  ],
  "West": [
    {
      "name": "Arizona",
      "seed": 1,
      "region": "West",
      "adj_o": 126.6,
      "adj_d": 87.2,
      "adj_tempo": 67.7,
      "record": "32-2",
      "conference": "Big 12",
      "kenpom_rank": 3,
      "three_pt_pct": 37.3,
      "last_10_record": "10-0",
      "current_streak": "W9",
      "conference_tourney_result": "Big 12 Champion (beat Iowa State 82-80 SF on Bradley buzzer-beater, beat Houston 79-74 in final)",
      "recent_form_notes": "9-game win streak, swept Big 12 regular season + tourney titles, 12 ranked wins (tied D-I record)",
      "key_players": "1. Brayden Burries (G, Fr, 15.9 PPG) \u2014 leading scorer, explosive freshman co... [NBA]; 2. Koa Peat (F, Fr, 13.6 PPG, 5.3 RPG) \u2014 versatile 6-8 freshman forward, elite... [NBA]; 3. Jaden Bradley (G, Sr, 13.4 PPG, 4.6 APG) \u2014 floor general, team leader, Alabama t...; 4. Motiejus Krivas (C, Jr, 10.5 PPG, 8.1 RPG) \u2014 7-2 rim protector, 1.9 BPG, interior ... [NBA]; 5. Tobe Awaka (F, Sr, 9.6 PPG, 7.8 RPG) \u2014 Big 12 Sixth Man of the Year, energy big",
      "experience_score": 4.0,
      "rest_days": 3,
      "travel_distance_miles": 1112.0,
      "turnover_rate": 10.8,
      "opp_fg_pct": 0.392
    },
    {
      "name": "Villanova",
      "seed": 8,
      "region": "West",
      "adj_o": 122.7,
      "adj_d": 89.9,
      "adj_tempo": 64.7,
      "record": "24-8",
      "conference": "Big East",
      "kenpom_rank": 33,
      "three_pt_pct": 36.6,
      "last_10_record": "6-4",
      "current_streak": "L1",
      "conference_tourney_result": "Big East Quarterfinals -- lost to Georgetown 78-64 (QF) as 3-seed",
      "recent_form_notes": "Villanova (24-8) had a strong regular season at 15-5 in the Big East but was upset by 11th-seeded Georgetown in the tournament quarterfinals; enter the NCAAs as an 8-seed after a disappointing early exit.",
      "key_players": "1. Tyler Perkins (F, Jr, 13.6 PPG, 6.2 RPG) \u2014 team-leading scorer, versatile forward; 2. Duke Brennan (F, So, 12.4 PPG, 8.5 RPG) \u2014 physical interior, double-double threat [NBA]; 3. Acaden Lewis (G, So, 12.4 PPG, 5.8 APG) \u2014 primary ball-handler, leads team in a...; 4. Devin Askew (G, Sr, 11.2 PPG) \u2014 veteran guard, explosive scorer; 5. Eric Dixon Jr. (F, Gr, 10.5 PPG, 5.5 RPG) \u2014 veteran stretch forward",
      "experience_score": 6.0,
      "rest_days": 3,
      "travel_distance_miles": 2395.0,
      "turnover_rate": 10.1,
      "opp_fg_pct": 0.45
    },
    {
      "name": "Utah State",
      "seed": 9,
      "region": "West",
      "adj_o": 124.1,
      "adj_d": 90.7,
      "adj_tempo": 65.7,
      "record": "28-6",
      "conference": "MWC",
      "kenpom_rank": 30,
      "three_pt_pct": 37.8,
      "last_10_record": "10-0",
      "current_streak": "W10",
      "conference_tourney_result": "Mountain West Champion -- beat UNLV 80-60 (QF), beat Nevada 79-66 (SF), beat San Diego State 73-62 (Final)",
      "recent_form_notes": "Utah State (28-6) is on a dominant 10-game winning streak and swept the MW regular season and tournament titles, winning all three tournament games by double digits; MJ Collins Jr. was tournament MVP and the Aggies are peaking at the right time.",
      "key_players": "1. MJ Collins (G, Sr, 17.9 PPG) \u2014 leading scorer, MW Tourney MVP, 50% 3PT; 2. Mason Falslev (G, Jr, 16.0 PPG, 6.1 RPG) \u2014 Mountain West POY, all-around playmaker; 3. Garry Clark (F, Gr, 10.3 PPG, 6.8 RPG) \u2014 physical forward, elite offensive reb...; 4. Karson Templin (F, Jr, 8.9 PPG) \u2014 versatile 6-9 stretch forward; 5. Drake Allen (G, Jr, 7.5 PPG) \u2014 starting guard, perimeter shooter",
      "experience_score": 7.0,
      "rest_days": 3,
      "travel_distance_miles": 602.0,
      "turnover_rate": 10.6,
      "opp_fg_pct": 0.424
    },
    {
      "name": "Wisconsin",
      "seed": 5,
      "region": "West",
      "adj_o": 125.9,
      "adj_d": 91.2,
      "adj_tempo": 66.2,
      "record": "24-10",
      "conference": "Big Ten",
      "kenpom_rank": 22,
      "three_pt_pct": 36.1,
      "last_10_record": "7-3",
      "current_streak": "L1",
      "conference_tourney_result": "Big Ten Semifinals -- beat Washington 85-82 (3rd Rd), beat Illinois 91-88 OT (QF), lost to Michigan 68-65 (SF)",
      "recent_form_notes": "Wisconsin (24-10) made a spirited Big Ten Tournament run with Nick Boyd's career-high 38 points in an OT upset of Illinois, but fell to Michigan 68-65 on a last-second three; enter the NCAAs with momentum despite the semifinal heartbreak.",
      "key_players": "1. Nick Boyd (G, Sr, 20.6 PPG, 4.2 APG) \u2014 leading scorer, 4th-highest in progra... [NBA]; 2. John Blackwell (G, Jr, 18.8 PPG) \u2014 dynamic scoring guard, career-high 34... [NBA]; 3. Nolan Winter (C, Jr, 13.5 PPG, 8.7 RPG) \u2014 7-foot center, stretches floor, ancho... [NBA]; 4. Austin Rapp (F, So, 9.3 PPG) \u2014 floor spacer, reliable FT shooter; 5. Braeden Carrington (G, Sr, 8.4 PPG) \u2014 sharpshooting guard, multiple school ...",
      "experience_score": 7.0,
      "rest_days": 3,
      "travel_distance_miles": 1642.0,
      "turnover_rate": 8.9,
      "opp_fg_pct": 0.447
    },
    {
      "name": "High Point",
      "seed": 12,
      "region": "West",
      "adj_o": 120.0,
      "adj_d": 100.6,
      "adj_tempo": 66.3,
      "record": "30-4",
      "conference": "Big South",
      "kenpom_rank": 92,
      "three_pt_pct": 34.6,
      "last_10_record": "9-1",
      "current_streak": "W6",
      "conference_tourney_result": "Big South Champion -- beat Winthrop 89-76 in Final",
      "recent_form_notes": "High Point (30-4) won its second straight Big South championship and is one of the hottest mid-majors in the country with a 30-win season; dominant conference play makes them a potential upset threat as a 12-seed.",
      "key_players": "1. Terry Anderson (F, Sr, 16.0 PPG, 6.1 RPG) \u2014 leading scorer and rebounder; 2. Rob Martin (G, Sr, 15.0 PPG, 4.5 APG) \u2014 dynamic PG, leads team in assists/steals; 3. Vincent Brady II (G, Sr, 10.5 PPG) \u2014 experienced guard, backcourt depth; 4. Babacar Diallo (G, Jr, 8.2 PPG) \u2014 versatile guard-forward, connector; 5. David Fonville (G, So, 7.5 PPG) \u2014 bench guard, energy scorer",
      "experience_score": 7.0,
      "rest_days": 3,
      "travel_distance_miles": 2300.0,
      "turnover_rate": 9.4,
      "opp_fg_pct": 0.426
    },
    {
      "name": "Arkansas",
      "seed": 4,
      "region": "West",
      "adj_o": 126.5,
      "adj_d": 91.3,
      "adj_tempo": 71.3,
      "record": "26-8",
      "conference": "SEC",
      "kenpom_rank": 18,
      "three_pt_pct": 36.4,
      "last_10_record": "9-1",
      "current_streak": "W5",
      "conference_tourney_result": "SEC Champion (beat Oklahoma 82-79 QF, beat Ole Miss 93-90 OT SF, beat Vanderbilt 86-75 final \u2014 Acuff 30pts/11ast)",
      "recent_form_notes": "Won SEC tourney first time since 2000, 5-game win streak, Calipari's team peaking in year 2",
      "key_players": "1. Darius Acuff Jr. (G, Fr, 22.7 PPG, 6.4 APG) \u2014 SEC POY, Wooden finalist, 1st Team Al... [NBA]; 2. Meleek Thomas (G, Fr, 15.6 PPG) \u2014 five-star freshman, SEC All-Freshman [NBA]; 3. Trevon Brazile (F, Sr, 12.8 PPG, 7.2 RPG) \u2014 senior forward, top rebounder; 4. Billy Richmond III (G, So, 11.1 PPG) \u2014 emerging sophomore, SEC postseason ho...; 5. Karter Knox (F, So, 8.4 PPG) \u2014 withdrew from 2025 draft to return",
      "experience_score": 3.0,
      "rest_days": 3,
      "travel_distance_miles": 1617.0,
      "turnover_rate": 9.0,
      "opp_fg_pct": 0.453
    },
    {
      "name": "Hawaii",
      "seed": 13,
      "region": "West",
      "adj_o": 105.0,
      "adj_d": 90.5,
      "adj_tempo": 64.0,
      "record": "24-8",
      "conference": "Big West",
      "kenpom_rank": 107,
      "three_pt_pct": 30.9,
      "last_10_record": "7-3",
      "current_streak": "W3",
      "conference_tourney_result": "Big West Champion -- beat UC Irvine 71-64 in Final as 2-seed",
      "recent_form_notes": "Hawaii (24-8) won its first Big West Tournament title since 2016 by knocking off top-seeded UC Irvine; the Rainbow Warriors earned a 13-seed in their final Big West season and enter March Madness with confidence.",
      "key_players": "1. Isaac Johnson (C, Sr, 13.7 PPG, 8.0 RPG) \u2014 7-0 center, All-Big West, dominant in...; 2. Dre Bullock (G, Gr, 12.3 PPG) \u2014 All-Big West, experienced grad transfer; 3. Harry Rouhliadeff (C, Sr, 11.7 PPG, 5.3 RPG) \u2014 team captain, 4-year player, double-d...; 4. Gytis Nemeiksa (F, Sr, 10.0 PPG, 5.2 RPG) \u2014 preseason All-Big West, Lithuanian fo...; 5. Aaron Hunkin-Claytor (G, So, 8.5 PPG) \u2014 freshman PG, leads team in assists/st...",
      "experience_score": 8.0,
      "rest_days": 3,
      "travel_distance_miles": 2593.0,
      "turnover_rate": 13.5,
      "opp_fg_pct": 0.411
    },
    {
      "name": "BYU",
      "seed": 6,
      "region": "West",
      "adj_o": 126.0,
      "adj_d": 91.8,
      "adj_tempo": 68.4,
      "record": "23-11",
      "conference": "Big 12",
      "kenpom_rank": 23,
      "three_pt_pct": 37.4,
      "last_10_record": "5-5",
      "current_streak": "L1",
      "conference_tourney_result": "Big 12 Quarterfinals -- beat Kansas State 105-91 (1st Rd), beat West Virginia 68-48 (2nd Rd), lost to Houston 73-66 (QF)",
      "recent_form_notes": "BYU (23-11) featured freshman AJ Dybantsa breaking Kevin Durant's Big 12 tournament freshman scoring record with 40 points; the Cougars went 9-9 in Big 12 play but are a dangerous team built around Dybantsa's star power.",
      "injury_notes": "Richie Saunders (W) \u2014 torn ACL Feb 14, OUT for season. Averaged 18.0 PPG, shot 38% from three. Team went through rough stretch after injury but recovered late.",
      "key_players": "1. AJ Dybantsa (F, Fr, 25.3 PPG, 6.7 RPG) \u2014 Big 12 leading scorer, projected #1 o... [NBA]; 2. Robert Wright III (G, So, 18.5 PPG, 4.8 APG) \u2014 stepped up after Saunders injury, eli... [NBA]; 4. Kennard Davis Jr. (F, Jr, 7.2 PPG) \u2014 SIU transfer, 6-11 forward, scored 20...; 5. Keba Keita (C, Sr, 6.3 PPG, 7.3 RPG) \u2014 elite FG%, leads offensive rebounding. MISSING: Richie Saunders (18.0 PPG, 5.8 RPG) \u2014 Torn ACL Feb 15, OUT for season",
      "experience_score": 4.0,
      "rest_days": 4,
      "travel_distance_miles": 603.0,
      "turnover_rate": 10.9,
      "opp_fg_pct": 0.443
    },
    {
      "name": "NC State",
      "seed": 11,
      "region": "West",
      "adj_o": 125.1,
      "adj_d": 94.2,
      "adj_tempo": 67.4,
      "record": "22-10",
      "conference": "ACC",
      "kenpom_rank": 34,
      "three_pt_pct": 35.1,
      "last_10_record": "4-6",
      "current_streak": "L1",
      "conference_tourney_result": "ACC Quarterfinals -- beat Pittsburgh 98-88 (2nd Rd), lost to Virginia 81-74 (QF); First Four team",
      "recent_form_notes": "NC State (20-13) enters the First Four with shaky recent form after a four-game losing streak in the regular season; they snapped it with a win over Pitt in the ACC tourney but lost to Virginia and are a bubble team that barely got in.",
      "key_players": "1. Paul McNeil Jr. (G, So, 13.9 PPG) \u2014 Starting shooting guard and elite per...; 2. Quadir Copeland (G, Sr, 13.9 PPG, 6.6 APG) \u2014 Starting point guard and floor genera... [NBA]; 3. Ven-Allen Lubin (F, Sr, 13.9 PPG, 7.2 RPG) \u2014 Starting power forward; ultra-efficie...; 4. Darrion Williams (F, Sr, 13.8 PPG) \u2014 Starting wing forward; versatile two-... [NBA]; 5. Tre Holloman (G, Sr, 9.3 PPG) \u2014 Starting guard; sharpshooter from thr...",
      "experience_score": 7.0,
      "rest_days": 3,
      "travel_distance_miles": 2194.0,
      "turnover_rate": 9.2,
      "opp_fg_pct": 0.45
    },
    {
      "name": "Gonzaga",
      "seed": 3,
      "region": "West",
      "adj_o": 124.0,
      "adj_d": 87.7,
      "adj_tempo": 70.3,
      "record": "30-3",
      "conference": "WCC",
      "kenpom_rank": 10,
      "three_pt_pct": 37.4,
      "last_10_record": "9-1",
      "current_streak": "W4",
      "conference_tourney_result": "WCC Champion (beat Santa Clara 79-68 in final \u2014 Graham Ike MOP)",
      "recent_form_notes": "30-3, 23rd WCC tourney title, 27th straight NCAA appearance, but missing Braden Huff (17.8 PPG) with knee injury",
      "injury_notes": "Braden Huff (F) \u2014 dislocated kneecap Jan 14, OUT for first weekend. Was averaging 17.8 PPG, 5.6 RPG. Jogging and shooting but will not play first or second round. Possible return second weekend if team advances.",
      "key_players": "1. Graham Ike (F, Sr, 19.7 PPG, 8.2 RPG) \u2014 Starting power forward and team's lea... [NBA]; 3. Tyon Grant-Foster (G, Sr, 11.2 PPG, 5.0 RPG) \u2014 Sixth man and key reserve wing; athle...; 4. Mario Saint-Supery (G, Fr, 8.6 PPG) \u2014 Freshman guard splitting time between...; 5. Davis Fogle (G, Fr, 8.4 PPG) \u2014 Freshman reserve guard; efficient sco.... MISSING: Braden Huff (17.8 PPG, 5.6 RPG) \u2014 Dislocated kneecap suffered Jan. 15; OUT for first weekend of NCAA Tournament per coach Mark Few",
      "experience_score": 5.0,
      "rest_days": 4,
      "travel_distance_miles": 1033.0,
      "turnover_rate": 9.7,
      "opp_fg_pct": 0.395
    },
    {
      "name": "Kennesaw State",
      "seed": 14,
      "region": "West",
      "adj_o": 111.7,
      "adj_d": 103.5,
      "adj_tempo": 70.0,
      "record": "21-13",
      "conference": "ASUN",
      "kenpom_rank": 163,
      "three_pt_pct": 34.0,
      "last_10_record": "6-4",
      "current_streak": "W2",
      "conference_tourney_result": "Conference USA Champion -- beat Louisiana Tech 71-60 in Final",
      "recent_form_notes": "Kennesaw State (21-13) won its first-ever Conference USA championship and enters the NCAA Tournament as a 14-seed; a scrappy program making just its second D-I tournament appearance.",
      "key_players": "2. RJ Johnson (G, Jr, 14.5 PPG, 4.0 APG) \u2014 Starting guard and top available scor...; 3. Braedan Lue (F, So, 11.1 PPG, 5.4 RPG) \u2014 Starting forward; versatile scorer an...; 4. Frankquon Sherman (F, Jr, 10.3 PPG, 8.4 RPG) \u2014 Starting forward and leading rebounde...; 5. Trey Simpson (F, Fr, 9.2 PPG) \u2014 Starting freshman forward; emerging s.... MISSING: Simeon Cottle (20.2 PPG, 2.5 RPG) \u2014 Suspended indefinitely since Jan. 15 after federal indictment in point-shaving scheme; will not play in tournament",
      "experience_score": 5.0,
      "rest_days": 4,
      "travel_distance_miles": 1874.0,
      "turnover_rate": 11.9,
      "opp_fg_pct": 0.407
    },
    {
      "name": "Miami FL",
      "seed": 7,
      "region": "West",
      "adj_o": 123.6,
      "adj_d": 90.1,
      "adj_tempo": 65.6,
      "record": "25-8",
      "conference": "ACC",
      "kenpom_rank": 31,
      "three_pt_pct": 34.1,
      "last_10_record": "7-3",
      "current_streak": "L1",
      "conference_tourney_result": "ACC Semifinals -- beat Louisville 78-73 (QF), lost to Virginia 84-62 (SF)",
      "recent_form_notes": "Miami (25-8) enjoyed a resurgent season under first-year coach Jai Lucas with Malik Reneau leading the charge; they beat Louisville in the ACC quarters but were blown out by Virginia in the semis before earning a 7-seed.",
      "key_players": "1. Malik Reneau (F, Sr, 18.8 PPG, 6.6 RPG) \u2014 Starting power forward and team's lea... [NBA]; 2. Tre Donaldson (G, Sr, 16.5 PPG, 5.8 APG) \u2014 Starting point guard and primary play... [NBA]; 3. Shelton Henderson (F, Fr, 13.7 PPG) \u2014 Starting freshman wing; five-star rec... [NBA]; 4. Tru Washington (G, Jr, 12.1 PPG) \u2014 Starting guard; reliable perimeter sh...; 5. Ernest Udeh Jr. (C, Sr, 6.9 PPG, 9.3 RPG) \u2014 Starting center and elite rebounder; ...",
      "experience_score": 6.0,
      "rest_days": 4,
      "travel_distance_miles": 2264.0,
      "turnover_rate": 11.2,
      "opp_fg_pct": 0.445
    },
    {
      "name": "Missouri",
      "seed": 10,
      "region": "West",
      "adj_o": 121.8,
      "adj_d": 93.5,
      "adj_tempo": 66.4,
      "record": "20-12",
      "conference": "SEC",
      "kenpom_rank": 52,
      "three_pt_pct": 34.9,
      "last_10_record": "5-5",
      "current_streak": "L1",
      "conference_tourney_result": "SEC 2nd Round -- lost to Kentucky 78-72",
      "recent_form_notes": "Missouri (20-12) had a .500 record down the stretch and was bounced in their SEC Tournament opener by Kentucky; the Tigers rely on inconsistent offense and enter as a vulnerable 10-seed.",
      "key_players": "1. Mark Mitchell (F, Sr, 18.3 PPG, 5.3 RPG) \u2014 Starting power forward and team's lea... [NBA]; 2. Jayden Stone (G, Sr, 13.2 PPG, 5.0 RPG) \u2014 Starting guard; missed early games wi...; 3. Trent Pierce (F, Jr, 10.6 PPG) \u2014 Starting forward; missed start of sea...; 4. T.O. Barrett (G, So, 8.9 PPG) \u2014 Backup guard and primary ball-handler...; 5. Anthony Robinson II (G, Jr, 8.8 PPG) \u2014 Starting guard; versatile backcourt c...",
      "experience_score": 7.0,
      "rest_days": 5,
      "travel_distance_miles": 1451.0,
      "turnover_rate": 12.4,
      "opp_fg_pct": 0.436
    },
    {
      "name": "Purdue",
      "seed": 2,
      "region": "West",
      "adj_o": 126.9,
      "adj_d": 90.0,
      "adj_tempo": 69.7,
      "record": "27-8",
      "conference": "Big Ten",
      "kenpom_rank": 8,
      "three_pt_pct": 39.2,
      "last_10_record": "7-3",
      "current_streak": "W5",
      "conference_tourney_result": "Big Ten Champion as 7-seed (beat Rutgers, Northwestern, Illinois, UCLA 73-66 SF, Michigan 80-72 final \u2014 Cluff 21pts in title game)",
      "recent_form_notes": "First 7-seed to win Big Ten tourney, 5 wins in 5 days, but closed regular season with 4 losses in 6 before hot tourney run",
      "key_players": "1. Braden Smith (G, Sr, 14.0 PPG, 9.0 APG) \u2014 Starting point guard and team leader;... [NBA]; 2. Fletcher Loyer (G, Sr, 13.8 PPG) \u2014 Starting shooting guard; elite three-...; 3. Trey Kaufman-Renn (F, Sr, 13.4 PPG, 8.7 RPG) \u2014 Starting power forward; first-team Al... [NBA]; 4. Oscar Cluff (F, Sr, 10.3 PPG, 7.4 RPG) \u2014 Starting center; ultra-efficient rim ...; 5. C.J. Cox (G, So, 8.4 PPG) \u2014 Starting guard; sophomore sharpshoote...",
      "experience_score": 8.0,
      "rest_days": 4,
      "travel_distance_miles": 1751.0,
      "turnover_rate": 8.9,
      "opp_fg_pct": 0.446
    },
    {
      "name": "Queens",
      "seed": 15,
      "region": "West",
      "adj_o": 118.9,
      "adj_d": 114.3,
      "adj_tempo": 69.4,
      "record": "21-13",
      "conference": "ASUN",
      "kenpom_rank": 181,
      "three_pt_pct": 35.0,
      "last_10_record": "6-4",
      "current_streak": "W2",
      "conference_tourney_result": "ASUN Champion -- beat Central Arkansas 98-93 OT in Final",
      "recent_form_notes": "Queens University of Charlotte (21-13) made history with its first ASUN title and first-ever NCAA D-I Tournament appearance; Chris Ashby scored 34 points in the overtime championship win and the Royals are the ultimate Cinderella candidate.",
      "key_players": "1. Nasir Mann (F, Sr, 13.4 PPG, 5.8 RPG) \u2014 Starting forward and team's leading s...; 2. Yoav Berman (F, So, 12.6 PPG) \u2014 Starting forward; skilled playmaking ...; 3. Jordan Watford (G, Fr, 11.9 PPG) \u2014 Freshman guard and key reserve; ultra...; 4. Chris Ashby (G, Sr, 11.7 PPG) \u2014 Starting shooting guard; volume three...; 5. Avantae Parker (F, Jr, 11.3 PPG, 5.3 RPG) \u2014 Starting forward; hyper-efficient int...",
      "experience_score": 5.0,
      "rest_days": 4,
      "travel_distance_miles": 2077.0,
      "turnover_rate": 10.7,
      "opp_fg_pct": 0.466
    },
    {
      "name": "LIU",
      "seed": 16,
      "region": "West",
      "adj_o": 101.5,
      "adj_d": 102.7,
      "adj_tempo": 67.1,
      "record": "24-10",
      "conference": "NEC",
      "kenpom_rank": 216,
      "three_pt_pct": 31.3,
      "last_10_record": "7-3",
      "current_streak": "W3",
      "conference_tourney_result": "NEC Champion -- beat Mercyhurst 79-70 in Final",
      "recent_form_notes": "LIU (24-10) won the NEC championship and became the first team selected for the 2026 NCAA Tournament; the Sharks are a 16-seed heading to the First Four.",
      "key_players": "1. Jamal Fuller (F, Sr, 16.4 PPG, 5.5 RPG) \u2014 Starting forward and team's leading s...; 2. Malachi Davis (G, Sr, 14.4 PPG) \u2014 Starting guard and primary ball-handl...; 3. Greg Gordon (G, Sr, 14.1 PPG, 5.5 RPG) \u2014 Starting guard; physical guard who ex...; 4. Jomo Goings (G, Jr, 10.0 PPG) \u2014 Starting guard; well-rounded contribu...; 5. Mason Porter-Brown (F, Jr, 7.6 PPG) \u2014 Key reserve forward; efficient scorer...",
      "experience_score": 8.0,
      "rest_days": 3,
      "travel_distance_miles": 2441.0,
      "turnover_rate": 13.0,
      "opp_fg_pct": 0.445
    },
    {
      "name": "Texas",
      "seed": 11,
      "region": "West",
      "adj_o": 125.8,
      "adj_d": 96.3,
      "adj_tempo": 69.8,
      "record": "18-14",
      "conference": "SEC",
      "kenpom_rank": 37,
      "three_pt_pct": 35.3,
      "last_10_record": "5-5",
      "current_streak": "L3",
      "conference_tourney_result": "Lost SEC first round to Ole Miss 66-76",
      "recent_form_notes": "Elite offense (KenPom AdjO 13th) but defense struggles; won 5 straight in Feb then collapsed with 4 losses in last 5",
      "key_players": "1. Dailyn Swain (F, Jr, 17.8 PPG, 7.6 RPG) \u2014 primary scorer, leads team in PPG/RPG/AP [NBA]; 2. Matas Vokietaitis (C, So, 15.5 PPG, 6.8 RPG) \u2014 interior force, elite FG%, rim finisher; 3. Tramon Mark (G, Sr, 13.5 PPG) \u2014 veteran scoring guard; 4. Jordan Pope (G, Sr, 13.3 PPG) \u2014 best 3PT shooter, floor spacer; 5. Camden Heide (F, Jr, 6.2 PPG) \u2014 3PT specialist (45.9%)",
      "experience_score": 6.0,
      "rest_days": 3,
      "travel_distance_miles": 1155.0,
      "turnover_rate": 11.0,
      "opp_fg_pct": 0.449
    }
  ],
  "Midwest": [
    {
      "name": "Michigan",
      "seed": 1,
      "region": "Midwest",
      "adj_o": 126.3,
      "adj_d": 87.0,
      "adj_tempo": 71.4,
      "record": "31-3",
      "conference": "Big Ten",
      "kenpom_rank": 2,
      "three_pt_pct": 37.6,
      "last_10_record": "9-1",
      "current_streak": "L1",
      "conference_tourney_result": "Lost Big Ten final to 7-seed Purdue 72-80 (beat Ohio State QF, Wisconsin 68-65 SF)",
      "recent_form_notes": "Historic 31-3 season (19-1 Big Ten, perfect 10-0 road record), but stunned by Purdue in B1G final",
      "injury_notes": "L.J. Cason (G) \u2014 torn ACL late February, OUT. Averaged 8.4 PPG off bench. Hurts depth but Michigan still has plenty of firepower.",
      "key_players": "1. Yaxel Lendeborg (F, Sr, 14.4 PPG, 7.0 RPG) \u2014 Big Ten POY, versatile senior forward [NBA]; 2. Morez Johnson Jr. (F, So, 13.3 PPG, 7.3 RPG) \u2014 explosive sophomore, 7-2 wingspan, ph... [NBA]; 3. Aday Mara (C, Jr, 11.6 PPG, 6.9 RPG) \u2014 7-3 center, elite rim protector, skil... [NBA]; 4. Elliot Cadeau (G, Jr, 10.2 PPG, 5.4 APG) \u2014 starting PG, UNC transfer, team assis...; 5. Trey McKenney (G, Fr, 9.7 PPG) \u2014 freshman sharpshooter, expanded role ...",
      "experience_score": 5.0,
      "rest_days": 3,
      "travel_distance_miles": 876.0,
      "turnover_rate": 12.0,
      "opp_fg_pct": 0.384
    },
    {
      "name": "Georgia",
      "seed": 8,
      "region": "Midwest",
      "adj_o": 125.4,
      "adj_d": 93.7,
      "adj_tempo": 65.9,
      "record": "22-10",
      "conference": "SEC",
      "kenpom_rank": 32,
      "three_pt_pct": 35.9,
      "last_10_record": "6-4",
      "current_streak": "L1",
      "conference_tourney_result": "SEC 2nd Round -- lost to Ole Miss 76-72 (blew 23-point lead)",
      "recent_form_notes": "Georgia (22-10) set a program record for regular-season wins in 121 years of basketball but suffered a shocking SEC Tournament exit, blowing a 23-point lead to Ole Miss; the Bulldogs earned a second straight NCAA bid but have a troubling collapse fresh in their minds.",
      "key_players": "1. Jeremiah Wilkinson (G, So, 17.0 PPG) \u2014 leading scorer, Cal transfer; 2. Blue Cain (G, Jr, 13.3 PPG, 5.1 RPG) \u2014 breakout junior, elite FT (90.5%) [NBA]; 3. Kanon Catchings (F, So, 12.0 PPG) \u2014 versatile sophomore, reliable 3PT; 4. Marcus Millender (G, Jr, 11.9 PPG, 4.0 APG) \u2014 team assist leader, strong 3PT off bench; 5. Somto Cyril (C, So, 9.6 PPG, 5.6 RPG) \u2014 elite FG% (76.4%), interior finisher",
      "experience_score": 4.0,
      "rest_days": 4,
      "travel_distance_miles": 810.0,
      "turnover_rate": 10.7,
      "opp_fg_pct": 0.438
    },
    {
      "name": "Saint Louis",
      "seed": 9,
      "region": "Midwest",
      "adj_o": 121.7,
      "adj_d": 90.4,
      "adj_tempo": 65.6,
      "record": "28-5",
      "conference": "A-10",
      "kenpom_rank": 41,
      "three_pt_pct": 36.7,
      "last_10_record": "7-3",
      "current_streak": "L1",
      "conference_tourney_result": "A-10 Semifinals -- beat George Washington 88-81 (QF), lost to Dayton 70-69 (SF)",
      "recent_form_notes": "Saint Louis (28-5) co-won the A-10 regular season title with VCU and Robbie Avila led the way all season; they fell by one point to Dayton in the A-10 semis but earned a strong 9-seed thanks to their outstanding regular season.",
      "key_players": "1. Robbie Avila (C, Sr, 12.9 PPG, 4.1 APG) \u2014 A-10 POY, 6-10 skilled passer, 3PT bi... [NBA]; 2. Dion Brown (G, Sr, 11.1 PPG, 5.5 RPG) \u2014 elite efficiency (60.6% FG, 40.4% 3PT); 3. Trey Green (G, Jr, 11.1 PPG) \u2014 elite 3PT sniper (45.7%); 4. Amari McCottry (G, So, 10.3 PPG, 5.2 RPG) \u2014 all-around sophomore, strong rebounder; 5. Kellen Thames (G, Jr, 9.9 PPG) \u2014 school-record FG%, A-10 Third Team, 4...",
      "experience_score": 7.0,
      "rest_days": 3,
      "travel_distance_miles": 458.0,
      "turnover_rate": 12.5,
      "opp_fg_pct": 0.379
    },
    {
      "name": "Texas Tech",
      "seed": 5,
      "region": "Midwest",
      "adj_o": 125.8,
      "adj_d": 89.7,
      "adj_tempo": 69.4,
      "record": "22-10",
      "conference": "Big 12",
      "kenpom_rank": 20,
      "three_pt_pct": 37.1,
      "last_10_record": "6-4",
      "current_streak": "L1",
      "conference_tourney_result": "Big 12 Quarterfinals -- lost to Iowa State 75-53 (QF) as 4-seed",
      "recent_form_notes": "Texas Tech (22-10) had a strong regular season at 12-6 in the Big 12 but was blown out by Iowa State in the Big 12 quarterfinals; the Red Raiders are a solid 5-seed but enter with questions after the lopsided loss.",
      "injury_notes": "JT Toppin (F) \u2014 torn ACL Feb 17, OUT for season. Was averaging 21.8 PPG, 10.8 RPG on 54.8% shooting. Consensus All-American, Big 12 Player of the Year. Team went 3-3 without him. Replaced by Luke Bamgboye (3.9 PPG). This is a completely different team without their best player.",
      "key_players": "2. Christian Anderson (G, So, 18.9 PPG, 7.6 APG) \u2014 star PG, Wooden ballot, projected 1st... [NBA]; 3. Donovan Atwell (F, Sr, 13.5 PPG) \u2014 senior sharpshooter, 45.4% 3PT; 4. LeJuan Watts (F, Jr, 11.5 PPG, 6.0 RPG) \u2014 6-6 wing, increased post duties with ...; 5. Jaylen Petty (G, Fr, 9.5 PPG) \u2014 freshman stepped into starting lineup. MISSING: JT Toppin (21.8 PPG, 10.8 RPG) \u2014 Torn ACL Feb 18, OUT for season",
      "experience_score": 5.0,
      "rest_days": 3,
      "travel_distance_miles": 279.0,
      "turnover_rate": 10.8,
      "opp_fg_pct": 0.439
    },
    {
      "name": "Akron",
      "seed": 12,
      "region": "Midwest",
      "adj_o": 121.3,
      "adj_d": 96.5,
      "adj_tempo": 70.7,
      "record": "29-5",
      "conference": "MAC",
      "kenpom_rank": 64,
      "three_pt_pct": 36.6,
      "last_10_record": "9-1",
      "current_streak": "W5",
      "conference_tourney_result": "MAC Champion (3-peat) -- beat Buffalo (QF), beat Kent State (SF), beat Toledo 79-76 (Final) on Shammah Scott's game-winner with 6.4 sec left",
      "recent_form_notes": "Akron (29-5) became the first team in MAC tournament history to win three consecutive championships; Shammah Scott's clutch three-pointer sealed the final and the Zips set a program record for wins.",
      "key_players": "1. Tavari Johnson (G, Sr, 20.1 PPG, 5.0 APG) \u2014 MAC star, 20+ PPG, MAC Tourney hero (...; 2. Amani Lyles (F, Sr, 14.6 PPG, 8.0 RPG) \u2014 double-double threat, leading rebounder; 3. Shammah Scott (G, Sr, 12.7 PPG) \u2014 elite 3PT (42.2%), instant offense of...; 4. Evan Mahaffey (F, Sr, 10.2 PPG, 5.6 RPG) \u2014 most versatile player, strong passer ...; 5. Bowen Hardman (G, Sr, 7.9 PPG) \u2014 bench sharpshooter, 40.7% 3PT",
      "experience_score": 8.0,
      "rest_days": 3,
      "travel_distance_miles": 949.0,
      "turnover_rate": 10.9,
      "opp_fg_pct": 0.421
    },
    {
      "name": "Alabama",
      "seed": 4,
      "region": "Midwest",
      "adj_o": 126.8,
      "adj_d": 92.6,
      "adj_tempo": 71.5,
      "record": "23-9",
      "conference": "SEC",
      "kenpom_rank": 17,
      "three_pt_pct": 36.9,
      "last_10_record": "8-2",
      "current_streak": "L1",
      "conference_tourney_result": "Lost SEC QF to 15-seed Ole Miss 79-80 (one-and-done despite 2-seed and double bye)",
      "recent_form_notes": "Won 9 of last 10 regular season games before shocking SEC tourney upset by Ole Miss",
      "key_players": "1. Labaron Philon (G, So, 21.7 PPG, 4.7 APG) \u2014 All-SEC, elite shot creator, projecte... [NBA]; 2. Aden Holloway (G, Jr, 16.8 PPG) \u2014 Auburn transfer, elite 3PT (43.8%); 3. Latrell Wrightsell Jr. (G, Sr, 12.8 PPG) \u2014 veteran guard, prior Achilles tear, i...; 4. Amari Allen (F, Fr, 11.7 PPG, 7.1 RPG) \u2014 freshman sensation, projected top-20 ... [NBA]; 5. Aiden Sherrell (F, So, 11.1 PPG, 6.1 RPG) \u2014 efficient interior scorer, started al...",
      "experience_score": 4.0,
      "rest_days": 5,
      "travel_distance_miles": 590.0,
      "turnover_rate": 9.8,
      "opp_fg_pct": 0.433
    },
    {
      "name": "Hofstra",
      "seed": 13,
      "region": "Midwest",
      "adj_o": 117.6,
      "adj_d": 95.1,
      "adj_tempo": 64.9,
      "record": "24-10",
      "conference": "CAA",
      "kenpom_rank": 88,
      "three_pt_pct": 34.6,
      "last_10_record": "8-2",
      "current_streak": "W7",
      "conference_tourney_result": "CAA Champion -- beat Monmouth 75-69 in Final",
      "recent_form_notes": "Hofstra (24-10) won the CAA title on a seven-game winning streak behind freshman Preston Edmead's 26-point championship performance; the Pride are making their first NCAA Tournament appearance since 2001 and are riding high.",
      "key_players": "1. Cruz Davis (G, Sr, 20.2 PPG, 4.6 APG) \u2014 CAA star, 20+ PPG, dropped 36 at Pitt; 2. Preston Edmead (G, Fr, 15.9 PPG, 4.4 APG) \u2014 dynamic freshman, top CAA freshman; 3. James Patterson (G, Sr, 9.5 PPG, 5.6 RPG) \u2014 strong rebounder for guard (5.6 RPG); 4. German Plotnikov (G, Sr, 9.3 PPG) \u2014 consistent starter, reliable 3PT; 5. Joshua DeCady (F, So, 6.3 PPG) \u2014 sophomore forward, provides size",
      "experience_score": 6.0,
      "rest_days": 3,
      "travel_distance_miles": 1346.0,
      "turnover_rate": 10.6,
      "opp_fg_pct": 0.387
    },
    {
      "name": "Tennessee",
      "seed": 6,
      "region": "Midwest",
      "adj_o": 123.1,
      "adj_d": 88.2,
      "adj_tempo": 66.7,
      "record": "22-11",
      "conference": "SEC",
      "kenpom_rank": 15,
      "three_pt_pct": 37.0,
      "last_10_record": "6-4",
      "current_streak": "L1",
      "conference_tourney_result": "SEC Quarterfinals -- beat Auburn 72-62 (2nd Rd), lost to Vanderbilt 75-68 (QF)",
      "recent_form_notes": "Tennessee (22-11) beat Auburn in the SEC Tournament but fell to Vanderbilt in the quarters; freshman Nate Ament has been a bright spot, but the Vols are making their eighth straight NCAA appearance without their best late-season form.",
      "key_players": "1. Ja'Kobi Gillespie (G, Sr, 18.0 PPG, 5.5 APG) \u2014 leading scorer, veteran leader, 32 vs...; 2. Nate Ament (F, Fr, 17.5 PPG, 6.6 RPG) \u2014 star freshman, projected top-10 NBA pick [NBA]; 3. J.P. Estrella (F, Jr, 10.1 PPG, 5.2 RPG) \u2014 elite efficiency (61.4% FG), interior...; 4. Felix Okpara (C, Sr, 7.7 PPG, 6.2 RPG) \u2014 starting center, rim protector, defen...; 5. Jaylen Carey (F, Jr, 7.4 PPG, 6.2 RPG) \u2014 energy rebounder off bench, no 3PT at...",
      "experience_score": 6.0,
      "rest_days": 4,
      "travel_distance_miles": 391.0,
      "turnover_rate": 11.7,
      "opp_fg_pct": 0.409
    },
    {
      "name": "SMU",
      "seed": 11,
      "region": "Midwest",
      "adj_o": 124.3,
      "adj_d": 94.7,
      "adj_tempo": 66.8,
      "record": "22-11",
      "conference": "ACC",
      "kenpom_rank": 42,
      "three_pt_pct": 34.9,
      "last_10_record": "4-6",
      "current_streak": "L1",
      "conference_tourney_result": "ACC 2nd Round -- beat Syracuse 86-69 (1st Rd), lost to Louisville 62-58 (2nd Rd); First Four team",
      "recent_form_notes": "SMU (20-13) barely squeezed into the field as a First Four team with an 8-10 ACC record; Boopie Miller scored 25 in the tourney opener vs Syracuse but the Mustangs lack consistency and are one of the last four teams in.",
      "key_players": "1. Kevin Miller (G, Sr, 19.2 PPG, 6.4 APG) \u2014 primary scorer, All-ACC Second Team; 2. Jaron Pierre Jr. (G, Sr, 17.6 PPG) \u2014 second scorer, 6-6 wing [NBA]; 5. Samet Yigitoglu (C, So, 10.8 PPG, 7.9 RPG) \u2014 7-2 center, dominant rebounder, rim f.... MISSING: B.J. Edwards (12.7 PPG, 5.9 RPG) \u2014 Ankle injury; missed last 5 games; questionable for NCAAs; MISSING: Corey Washington (11.3 PPG, 4.9 RPG) \u2014 Shoulder injury in ACC Tournament; status uncertain",
      "experience_score": 8.0,
      "rest_days": 3,
      "travel_distance_miles": 544.0,
      "turnover_rate": 11.3,
      "opp_fg_pct": 0.434
    },
    {
      "name": "Virginia",
      "seed": 3,
      "region": "Midwest",
      "adj_o": 124.2,
      "adj_d": 88.3,
      "adj_tempo": 63.9,
      "record": "29-5",
      "conference": "ACC",
      "kenpom_rank": 13,
      "three_pt_pct": 34.9,
      "last_10_record": "9-1",
      "current_streak": "L1",
      "conference_tourney_result": "ACC Runner-Up (beat NC State 81-74 QF, lost to Duke 70-74 in final)",
      "recent_form_notes": "29-5 in Ryan Odom's first year (winningest first-year ACC coach ever), lost close ACC final to Duke",
      "key_players": "1. Thijs De Ridder (F, Fr, 15.5 PPG, 6.2 RPG) \u2014 leading scorer, 6-9 Belgian freshman [NBA]; 2. Malik Thomas (G, Sr, 12.4 PPG) \u2014 veteran guard, second scorer; 3. Sam Lewis (G, Jr, 10.8 PPG) \u2014 elite 3PT shooter (40.7%); 4. Chance Mallory (G, Fr, 9.5 PPG) \u2014 freshman guard, primary facilitator; 5. Jacari White (G, Sr, 8.8 PPG) \u2014 sixth man, elite 3PT (43.0%)",
      "experience_score": 4.0,
      "rest_days": 4,
      "travel_distance_miles": 635.0,
      "turnover_rate": 10.8,
      "opp_fg_pct": 0.395
    },
    {
      "name": "Wright State",
      "seed": 14,
      "region": "Midwest",
      "adj_o": 114.6,
      "adj_d": 103.4,
      "adj_tempo": 65.9,
      "record": "23-11",
      "conference": "Horizon",
      "kenpom_rank": 140,
      "three_pt_pct": 32.6,
      "last_10_record": "8-2",
      "current_streak": "W4",
      "conference_tourney_result": "Horizon League Champion -- beat Detroit Mercy 66-63 in Final",
      "recent_form_notes": "Wright State (23-11) swept the Horizon League regular season and tournament titles for the first time in program history; TJ Burch earned tournament MVP with 19 points in the final and the Raiders enter as a confident 14-seed.",
      "key_players": "1. Michael Cooper (G, Fr, 13.4 PPG) \u2014 freshman PG, leading scorer, breakout...; 2. TJ Burch (G, So, 12.3 PPG) \u2014 HL Tourney MVP, DPOY, Newcomer of Year; 3. Michael Imariagbe (F, Sr, 11.8 PPG, 7.0 RPG) \u2014 leading rebounder, efficient interior...; 4. Solomon Callaghan (G, So, 9.9 PPG) \u2014 elite FT shooter (92.2%), 3PT threat; 5. Dominic Pangonis (G, So, 9.0 PPG) \u2014 key reserve, efficient shooter",
      "experience_score": 4.0,
      "rest_days": 4,
      "travel_distance_miles": 338.0,
      "turnover_rate": 11.3,
      "opp_fg_pct": 0.457
    },
    {
      "name": "Kentucky",
      "seed": 7,
      "region": "Midwest",
      "adj_o": 122.9,
      "adj_d": 89.2,
      "adj_tempo": 67.1,
      "record": "21-13",
      "conference": "SEC",
      "kenpom_rank": 28,
      "three_pt_pct": 34.6,
      "last_10_record": "5-5",
      "current_streak": "L1",
      "conference_tourney_result": "SEC Quarterfinals -- beat LSU 87-82 (1st Rd), beat Missouri 78-72 (2nd Rd), lost to Florida 71-63 (QF)",
      "recent_form_notes": "Kentucky (21-13) won multiple SEC Tournament games for the first time since 2018 but still fell to Florida in the quarters; an inconsistent season under Mark Pope leaves them as a dangerous but unpredictable 7-seed.",
      "key_players": "1. Otega Oweh (G, Sr, 18.2 PPG) \u2014 leading scorer, All-SEC Second Team [NBA]; 2. Denzel Aberdeen (G, Sr, 13.2 PPG) \u2014 team assist leader, backcourt partner; 3. Collin Chandler (G, So, 9.9 PPG) \u2014 elite 3PT shooter (42.7%); 4. Mouhamed Dioubate (F, Jr, 8.7 PPG, 5.5 RPG) \u2014 physical interior, second rebounder; 5. Malachi Moreno (C, Fr, 8.0 PPG, 6.4 RPG) \u2014 leading rebounder, All-SEC Freshman, ... [NBA]",
      "experience_score": 6.0,
      "rest_days": 4,
      "travel_distance_miles": 312.0,
      "turnover_rate": 10.5,
      "opp_fg_pct": 0.425
    },
    {
      "name": "Santa Clara",
      "seed": 10,
      "region": "Midwest",
      "adj_o": 124.6,
      "adj_d": 93.9,
      "adj_tempo": 66.8,
      "record": "26-8",
      "conference": "WCC",
      "kenpom_rank": 35,
      "three_pt_pct": 38.0,
      "last_10_record": "7-3",
      "current_streak": "L1",
      "conference_tourney_result": "WCC Runner-Up -- beat Saint Mary's 76-71 (SF), lost to Gonzaga 79-68 (Final)",
      "recent_form_notes": "Santa Clara (26-8) upset No. 21 Saint Mary's in the WCC semis and pushed Gonzaga in the final; coach Herb Sendek earned his 600th career win and the Broncos are making the NCAA Tournament with the WCC earning three bids for the first time since 2022.",
      "key_players": "1. Christian Hammond (G, So, 15.8 PPG) \u2014 leading scorer, All-WCC First Team; 2. Elijah Mahi (F, Sr, 13.9 PPG) \u2014 veteran forward, All-WCC First Team; 3. Allen Graves (F, Fr, 11.6 PPG, 6.5 RPG) \u2014 WCC FOY & 6MOY, drawing NBA attention [NBA]; 4. Aleksandar Gavalyugov (G, Fr, 8.8 PPG) \u2014 key reserve, playmaking guard; 5. Bukky Oboye (C, So, 8.0 PPG) \u2014 starting center, hyper-efficient (66....",
      "experience_score": 4.0,
      "rest_days": 4,
      "travel_distance_miles": 1722.0,
      "turnover_rate": 10.8,
      "opp_fg_pct": 0.451
    },
    {
      "name": "Iowa State",
      "seed": 2,
      "region": "Midwest",
      "adj_o": 124.9,
      "adj_d": 87.3,
      "adj_tempo": 70.3,
      "record": "27-7",
      "conference": "Big 12",
      "kenpom_rank": 6,
      "three_pt_pct": 37.9,
      "last_10_record": "8-2",
      "current_streak": "L1",
      "conference_tourney_result": "Lost Big 12 SF to Arizona 80-82 on Jaden Bradley buzzer-beater (beat Arizona State by 49, beat Texas Tech 75-53 QF)",
      "recent_form_notes": "Started 16-0 then went 11-7 rest of way, lost heartbreaker to Arizona at the buzzer in Big 12 SF",
      "key_players": "1. Milan Momcilovic (F, Jr, 17.1 PPG) \u2014 leading scorer, elite 3PT sniper (49.6%) [NBA]; 2. Joshua Jefferson (F, Sr, 16.9 PPG, 7.6 RPG, 4.9 APG) \u2014 do-it-all wing, projected 1st round pick [NBA]; 3. Tamin Lipsey (G, Sr, 13.3 PPG, 5.0 APG) \u2014 PG, team assist leader (5.0 APG); 4. Blake Buchanan (F, Jr, 8.4 PPG, 5.7 RPG) \u2014 elite finisher (64.5% FG), rebounder; 5. Killyan Toure (G, Fr, 8.1 PPG) \u2014 starting freshman guard",
      "experience_score": 6.0,
      "rest_days": 5,
      "travel_distance_miles": 297.0,
      "turnover_rate": 10.3,
      "opp_fg_pct": 0.426
    },
    {
      "name": "Tennessee State",
      "seed": 15,
      "region": "Midwest",
      "adj_o": 108.6,
      "adj_d": 104.9,
      "adj_tempo": 66.1,
      "record": "23-9",
      "conference": "OVC",
      "kenpom_rank": 187,
      "three_pt_pct": 32.4,
      "last_10_record": "8-2",
      "current_streak": "W5",
      "conference_tourney_result": "OVC Champion -- beat UT Martin 68-55 (SF), beat Morehead State 93-67 (Final)",
      "recent_form_notes": "Tennessee State (23-9) won the OVC Tournament for the first time in 32 years, demolishing Morehead State 93-67 in the final with blistering three-point shooting; Dante Harris was tournament MVP as the Tigers end a decades-long NCAA Tournament drought.",
      "key_players": "1. Aaron Nkrumah (G, Sr, 17.6 PPG, 5.5 RPG) \u2014 OVC POY, national leader in steals; 2. Travis Harper II (G, Sr, 17.3 PPG) \u2014 All-OVC, elite 3PT (40.1%); 3. Dante Harris (G, Sr, 11.7 PPG, 4.5 APG) \u2014 OVC Tourney MVP, primary playmaker; 4. Antoine Lorick III (F, Jr, 9.5 PPG, 5.0 RPG) \u2014 efficient interior scorer; 5. Jalen Pitre (F, Sr, 6.5 PPG, 6.6 RPG) \u2014 leading rebounder, ultra-efficient (6...",
      "experience_score": 8.0,
      "rest_days": 4,
      "travel_distance_miles": 251.0,
      "turnover_rate": 12.2,
      "opp_fg_pct": 0.444
    },
    {
      "name": "UMBC",
      "seed": 16,
      "region": "Midwest",
      "adj_o": 107.4,
      "adj_d": 103.3,
      "adj_tempo": 70.1,
      "record": "20-14",
      "conference": "America East",
      "kenpom_rank": 185,
      "three_pt_pct": 31.9,
      "last_10_record": "8-2",
      "current_streak": "W4",
      "conference_tourney_result": "America East Champion -- beat Vermont 74-59 in Final; heads to First Four vs Howard",
      "recent_form_notes": "UMBC (24-8) is back in the NCAA Tournament for the first time since their historic 16-over-1 upset in 2018; DJ Armstrong Jr. scored 33 points with seven threes in the AE final, and the Retrievers closed on a 26-8 run to dominate Vermont.",
      "key_players": "1. Jah'Likai King (G, Jr, 13.9 PPG) \u2014 leading scorer, America East First Team; 2. DJ Armstrong Jr. (F, Sr, 13.2 PPG) \u2014 Tourney MOP (33 pts in title game), e...; 3. Ace Valentine (G, Jr, 12.0 PPG, 4.0 APG) \u2014 versatile guard, best playmaker (4.0 ...; 4. Caden Diggs (F, So, 9.8 PPG) \u2014 ODU transfer, well-rounded scorer; 5. Josh Odunowo (F, Gr, 8.6 PPG, 5.2 RPG) \u2014 leading rebounder, veteran interior p...",
      "experience_score": 7.0,
      "rest_days": 2,
      "travel_distance_miles": 1170.0,
      "turnover_rate": 9.6,
      "opp_fg_pct": 0.424
    },
    {
      "name": "Howard",
      "seed": 16,
      "region": "Midwest",
      "adj_o": 103.4,
      "adj_d": 97.2,
      "adj_tempo": 69.5,
      "record": "23-10",
      "conference": "MEAC",
      "kenpom_rank": 207,
      "three_pt_pct": 34.5,
      "last_10_record": "9-1",
      "current_streak": "W8",
      "conference_tourney_result": "MEAC Champion (beat SC State 78-61, beat NC Central 70-63)",
      "recent_form_notes": "Program-record 23 wins; won MEAC regular season and tournament titles; dominant 8-game win streak",
      "key_players": "1. Bryce Harris (G, Sr, 17.1 PPG, 6.9 RPG) \u2014 MEAC POY, MEAC Tourney MOP; 2. Cedric Taylor III (G, Jr, 17.1 PPG, 6.7 RPG) \u2014 co-leading scorer, versatile guard; 3. Cam Gillus (G, Jr, 10.6 PPG, 4.6 APG) \u2014 floor general, lead facilitator; 4. Ose Okojie (G, Sr, 10.5 PPG) \u2014 efficient scorer, elite 3PT (42.9%); 5. Travelle Bryson (F, So, 8.8 PPG) \u2014 interior presence, developing big",
      "experience_score": 7.0,
      "rest_days": 2,
      "travel_distance_miles": 1151.0,
      "turnover_rate": 13.5,
      "opp_fg_pct": 0.418
    },
    {
      "name": "Miami OH",
      "seed": 11,
      "region": "Midwest",
      "adj_o": 123.9,
      "adj_d": 102.8,
      "adj_tempo": 71.5,
      "record": "31-1",
      "conference": "MAC",
      "kenpom_rank": 93,
      "three_pt_pct": 39.2,
      "last_10_record": "9-1",
      "current_streak": "L1",
      "conference_tourney_result": "Lost MAC QF to UMass 83-87 (ended 31-0 regular season)",
      "recent_form_notes": "Went 31-0 in regular season (3rd team in D-I history); elite shooting (39.2% 3PT); only loss in MAC tourney QF",
      "key_players": "1. Peter Suder (G, Sr, 14.6 PPG, 4.0 APG) \u2014 MAC POY, elite efficiency, complete play; 2. Brant Byers (F, So, 14.2 PPG) \u2014 All-MAC, versatile scoring forward; 3. Evan Ipsaro (G, Jr, 13.9 PPG) \u2014 elite shooting guard, high efficiency; 4. Eian Elmer (F, Jr, 12.6 PPG, 6.0 RPG) \u2014 All-MAC, top rebounder, inside-outside; 5. Antwone Woolfolk (F, Sr, 10.3 PPG, 5.5 RPG) \u2014 interior finisher, elite FG%",
      "experience_score": 6.0,
      "rest_days": 3,
      "travel_distance_miles": 300.0,
      "turnover_rate": 10.5,
      "opp_fg_pct": 0.436
    }
  ],
  "South": [
    {
      "name": "Florida",
      "seed": 1,
      "region": "South",
      "adj_o": 126.1,
      "adj_d": 87.4,
      "adj_tempo": 72.0,
      "record": "26-7",
      "conference": "SEC",
      "kenpom_rank": 4,
      "three_pt_pct": 36.6,
      "last_10_record": "9-1",
      "current_streak": "L1",
      "conference_tourney_result": "Lost SEC SF to Vanderbilt 74-91 (had 12-game win streak snapped, blown out by 17)",
      "recent_form_notes": "SEC regular season champs, back-to-back #1 seeds, but 17-point blowout loss to Vandy in SEC semis is concerning",
      "key_players": "1. Thomas Haugh (F, Jr, 17.1 PPG, 6.2 RPG) \u2014 primary scorer, versatile forward [NBA]; 2. Alex Condon (F, Jr, 15.0 PPG, 7.7 RPG) \u2014 skilled 6-11 forward, secondary playm... [NBA]; 3. Boogie Fland (G, So, 11.6 PPG) \u2014 dynamic guard, pick-and-roll prowess [NBA]; 4. Xaivian Lee (G, Sr, 11.5 PPG, 4.2 APG) \u2014 floor general, scores at all three le... [NBA]; 5. Rueben Chinyelu (C, Jr, 11.2 PPG, 11.5 RPG) \u2014 elite rebounder (11.5 RPG), paint def... [NBA]",
      "experience_score": 6.0,
      "rest_days": 4,
      "travel_distance_miles": 360.0,
      "turnover_rate": 11.9,
      "opp_fg_pct": 0.408
    },
    {
      "name": "Clemson",
      "seed": 8,
      "region": "South",
      "adj_o": 119.5,
      "adj_d": 88.6,
      "adj_tempo": 64.1,
      "record": "24-10",
      "conference": "ACC",
      "kenpom_rank": 36,
      "three_pt_pct": 35.9,
      "last_10_record": "7-3",
      "current_streak": "L1",
      "conference_tourney_result": "ACC Semifinals -- beat Wake Forest 71-62 (2nd Rd), beat UNC 80-79 (QF), lost to Duke 73-61 (SF)",
      "recent_form_notes": "Clemson (24-10) made a solid ACC Tournament run, edging UNC by one point in the quarters before falling to Duke in the semis; a well-rounded 8-seed with postseason experience.",
      "injury_notes": "Carter Welling (C) \u2014 torn ACL March 12 in ACC Tournament, OUT for season. Averaged 10.2 PPG, 5.4 RPG. Significant frontcourt depth loss.",
      "key_players": "1. RJ Godfrey (F, Sr, 11.9 PPG, 5.3 RPG) \u2014 leading scorer, highly efficient forward; 3. Jestin Porter (G, Sr, 9.6 PPG) \u2014 perimeter shooter, starting guard; 4. Nick Davidson (F, Sr, 9.1 PPG) \u2014 versatile bench forward, efficient sc...; 5. Ace Buckner (G, So, 8.4 PPG) \u2014 bench guard, scoring depth. MISSING: Carter Welling (10.2 PPG, 5.4 RPG) \u2014 Torn ACL in ACC Tournament, OUT for season",
      "experience_score": 7.0,
      "rest_days": 3,
      "travel_distance_miles": 28.0,
      "turnover_rate": 9.4,
      "opp_fg_pct": 0.419
    },
    {
      "name": "Iowa",
      "seed": 9,
      "region": "South",
      "adj_o": 123.8,
      "adj_d": 89.5,
      "adj_tempo": 67.9,
      "record": "21-12",
      "conference": "Big Ten",
      "kenpom_rank": 25,
      "three_pt_pct": 34.9,
      "last_10_record": "5-5",
      "current_streak": "L1",
      "conference_tourney_result": "Big Ten 3rd Round -- beat Maryland 75-64 (2nd Rd), lost to Ohio State 72-69 (3rd Rd)",
      "recent_form_notes": "Iowa (21-12) returned to the NCAA Tournament for the first time since 2023 under first-year coach Ben McCollum; a .500 record down the stretch and early Big Ten Tournament exit raise concerns, but the Hawkeyes have enough talent to be competitive as a 9-seed.",
      "key_players": "1. Bennett Stirtz (G, Sr, 20.0 PPG, 4.5 APG) \u2014 star player, best passer in 2026 draf... [NBA]; 2. Tavion Banks (G, Sr, 10.5 PPG) \u2014 sharpshooting guard, elite 3PT (47.2%); 3. Alvaro Folgueiras (F, Jr, 8.1 PPG) \u2014 versatile bench forward; 4. Cooper Koch (F, So, 7.7 PPG) \u2014 starting forward, reliable 3PT shooter; 5. Cam Manyawu (F, Jr, 7.1 PPG) \u2014 interior forward, elite finishing eff...",
      "experience_score": 7.0,
      "rest_days": 4,
      "travel_distance_miles": 683.0,
      "turnover_rate": 9.7,
      "opp_fg_pct": 0.461
    },
    {
      "name": "Vanderbilt",
      "seed": 5,
      "region": "South",
      "adj_o": 126.4,
      "adj_d": 89.4,
      "adj_tempo": 67.1,
      "record": "26-8",
      "conference": "SEC",
      "kenpom_rank": 11,
      "three_pt_pct": 36.6,
      "last_10_record": "7-3",
      "current_streak": "L1",
      "conference_tourney_result": "SEC Runner-Up -- beat Tennessee 75-68 (QF), beat Florida 91-74 (SF), lost to Arkansas 86-75 (Final)",
      "recent_form_notes": "Vanderbilt (26-8) made a spectacular SEC Tournament run, upsetting No. 1 seed Florida 91-74 in the semis before falling to Arkansas in the championship; the Commodores tied their program record for wins and are a dangerous 5-seed.",
      "key_players": "1. Tyler Tanner (G, So, 19.2 PPG, 5.3 APG) \u2014 leading scorer, floor general, lotter... [NBA]; 2. Duke Miles (G, Sr, 16.4 PPG, 4.3 APG) \u2014 veteran backcourt partner, elite FT s...; 3. Tyler Nickel (F, Sr, 13.3 PPG) \u2014 sharpshooting forward, floor spacer; 4. AK Okereke (F, Sr, 9.8 PPG) \u2014 versatile senior forward, efficient s...; 5. Devin McGlockton (F, Sr, 9.7 PPG, 6.7 RPG) \u2014 physical interior forward, leading re...",
      "experience_score": 7.0,
      "rest_days": 3,
      "travel_distance_miles": 263.0,
      "turnover_rate": 9.5,
      "opp_fg_pct": 0.427
    },
    {
      "name": "McNeese",
      "seed": 12,
      "region": "South",
      "adj_o": 117.4,
      "adj_d": 90.9,
      "adj_tempo": 67.6,
      "record": "28-5",
      "conference": "Southland",
      "kenpom_rank": 68,
      "three_pt_pct": 33.1,
      "last_10_record": "9-1",
      "current_streak": "W6",
      "conference_tourney_result": "Southland Champion (3-peat) -- beat UTRGV 84-80 3OT (SF), beat Stephen F. Austin 76-59 (Final)",
      "recent_form_notes": "McNeese (28-5) won their third straight Southland title, surviving a triple-overtime thriller against UTRGV before blowing out SFA in the final; only the third team in league history to three-peat, and they are rolling.",
      "key_players": "1. Larry Johnson (G, So, 17.5 PPG, 5.5 RPG) \u2014 leading scorer, explosive, can put up...; 2. Tyshawn Archie (G, Jr, 14.3 PPG) \u2014 second scorer, elite FT, 3PT specialist; 3. Javohn Garcia (G, Sr, 12.0 PPG) \u2014 veteran guard, efficient scorer; 4. DJ Richards (G, Sr, 8.3 PPG) \u2014 bench scorer, 3PT specialist; 5. Garwey Dual (G, Jr, 8.2 PPG, 4.3 APG) \u2014 playmaking guard, team assist leader",
      "experience_score": 6.0,
      "rest_days": 3,
      "travel_distance_miles": 707.0,
      "turnover_rate": 9.6,
      "opp_fg_pct": 0.407
    },
    {
      "name": "Nebraska",
      "seed": 4,
      "region": "South",
      "adj_o": 121.2,
      "adj_d": 87.5,
      "adj_tempo": 66.2,
      "record": "26-6",
      "conference": "Big Ten",
      "kenpom_rank": 14,
      "three_pt_pct": 35.7,
      "last_10_record": "6-4",
      "current_streak": "L1",
      "conference_tourney_result": "Lost Big Ten QF to 7-seed Purdue 58-74 (2-seed, never led, blown out from opening minutes)",
      "recent_form_notes": "Record 15 Big Ten regular season wins but humiliating QF loss to Purdue, limping into NCAAs",
      "key_players": "1. Pryce Sandfort (F, Jr, 17.8 PPG) \u2014 star player, elite 3PT shooter [NBA]; 2. Rienk Mast (F, Sr, 13.5 PPG, 5.8 RPG) \u2014 veteran forward, versatile playmaker; 3. Braden Frager (F, Fr, 11.6 PPG) \u2014 talented freshman, efficient bench sc...; 4. Jamarques Lawrence (G, Sr, 9.7 PPG, 4.0 APG) \u2014 starting PG, primary distributor; 5. Sam Hoiberg (G, Sr, 9.6 PPG, 5.3 RPG, 4.3 APG) \u2014 versatile guard, elite efficiency, co...",
      "experience_score": 6.0,
      "rest_days": 5,
      "travel_distance_miles": 881.0,
      "turnover_rate": 9.8,
      "opp_fg_pct": 0.404
    },
    {
      "name": "Troy",
      "seed": 13,
      "region": "South",
      "adj_o": 112.0,
      "adj_d": 101.0,
      "adj_tempo": 66.8,
      "record": "22-11",
      "conference": "Sun Belt",
      "kenpom_rank": 143,
      "three_pt_pct": 32.8,
      "last_10_record": "7-3",
      "current_streak": "W3",
      "conference_tourney_result": "Sun Belt Champion -- beat Georgia Southern 77-61 in Final (back-to-back titles)",
      "recent_form_notes": "Troy (22-11) became the Sun Belt's first back-to-back champion since 2018-19 Georgia State; Thomas Dowd posted a game-high 23 points and 13 rebounds in the title game as the first Sun Belt back-to-back champion since Georgia State.",
      "key_players": "1. Thomas Dowd (F, Jr, 14.8 PPG, 10.1 RPG) \u2014 double-double machine (14.8/10.1); 2. Victor Valdes (F, Jr, 14.8 PPG, 4.6 APG) \u2014 co-leading scorer, top playmaker; 3. Theo Seng (F, Sr, 12.9 PPG, 5.8 RPG) \u2014 efficient starting forward; 4. Cooper Campbell (G, So, 12.7 PPG, 4.2 APG) \u2014 explosive scoring guard, strong 3PT; 5. Cobi Campbell (G, Sr, 9.0 PPG) \u2014 3PT specialist (40.4%)",
      "experience_score": 6.0,
      "rest_days": 3,
      "travel_distance_miles": 295.0,
      "turnover_rate": 11.9,
      "opp_fg_pct": 0.433
    },
    {
      "name": "UNC",
      "seed": 6,
      "region": "South",
      "adj_o": 123.7,
      "adj_d": 90.1,
      "adj_tempo": 65.0,
      "record": "24-8",
      "conference": "ACC",
      "kenpom_rank": 29,
      "three_pt_pct": 34.2,
      "last_10_record": "7-3",
      "current_streak": "L1",
      "conference_tourney_result": "ACC Quarterfinals -- lost to Clemson 80-79 (QF) as 4-seed",
      "recent_form_notes": "North Carolina (24-8) had a strong regular season at 12-6 in the ACC but was bounced in the ACC quarterfinals by Clemson in a heartbreaking one-point loss; the Tar Heels have the talent of a 6-seed but limp into the tournament on a loss.",
      "injury_notes": "Caleb Wilson (F) \u2014 OUT for tournament. Originally fractured left hand Feb 10, then broke right thumb in practice March 5 while rehabbing. Was averaging ~20 PPG, 9+ RPG. Team is significantly weakened without their best player.",
      "key_players": "2. Henri Veesaar (F, Sr, 16.7 PPG, 8.7 RPG) \u2014 7-foot Arizona transfer, elite effici... [NBA]; 3. Seth Trimble (G, Sr, 14.0 PPG) \u2014 veteran guard, expanded role with Wil...; 4. Luka Bogavac (G, Jr, 9.8 PPG) \u2014 3PT shooter, perimeter scoring; 5. Jarin Stevenson (F, Jr, 8.0 PPG) \u2014 versatile forward, bigger role with W.... MISSING: Caleb Wilson (19.8 PPG, 9.4 RPG) \u2014 Fractured left hand + broken right thumb, OUT for season",
      "experience_score": 6.0,
      "rest_days": 4,
      "travel_distance_miles": 585.0,
      "turnover_rate": 9.7,
      "opp_fg_pct": 0.418
    },
    {
      "name": "VCU",
      "seed": 11,
      "region": "South",
      "adj_o": 122.2,
      "adj_d": 92.3,
      "adj_tempo": 66.8,
      "record": "27-7",
      "conference": "A-10",
      "kenpom_rank": 46,
      "three_pt_pct": 34.4,
      "last_10_record": "9-1",
      "current_streak": "W5",
      "conference_tourney_result": "A-10 Champion -- beat Duquesne (QF), beat Saint Joseph's 77-64 (SF), beat Dayton 70-62 (Final)",
      "recent_form_notes": "VCU (27-7) won its second straight A-10 Tournament championship and co-regular season title; the Rams are on a five-game winning streak and peaking at exactly the right time for their 21st March Madness appearance.",
      "key_players": "1. Terrence Hill Jr. (G, So, 14.6 PPG) \u2014 leading scorer, elite sixth man, All-...; 2. Lazar Djokovic (F, Jr, 13.7 PPG, 5.6 RPG) \u2014 interior scorer, starting forward, Al...; 3. Jadrian Tracey (G, Sr, 10.1 PPG) \u2014 starting guard, perimeter scorer; 4. Brandon Jennings (G, So, 8.8 PPG) \u2014 starting guard, playmaker, All-Defens...; 5. Nyk Lewis (G, Fr, 8.5 PPG) \u2014 starting freshman guard, A-10 Rookie ...",
      "experience_score": 4.0,
      "rest_days": 4,
      "travel_distance_miles": 724.0,
      "turnover_rate": 10.5,
      "opp_fg_pct": 0.431
    },
    {
      "name": "Illinois",
      "seed": 3,
      "region": "South",
      "adj_o": 127.0,
      "adj_d": 89.3,
      "adj_tempo": 68.8,
      "record": "24-8",
      "conference": "Big Ten",
      "kenpom_rank": 7,
      "three_pt_pct": 36.8,
      "last_10_record": "6-4",
      "current_streak": "L1",
      "conference_tourney_result": "Lost Big Ten QF to Wisconsin 88-91 OT (blew 15-point 2nd half lead, 0-4 in OT games this season)",
      "recent_form_notes": "Lost 5 straight Quad I games since early Feb, blew 15-point lead in Big Ten tourney, fading badly",
      "key_players": "1. Keaton Wagler (G, Fr, 17.9 PPG, 4.3 APG) \u2014 primary scorer, unanimous Big Ten Fre... [NBA]; 2. Kylan Boswell (G, Sr, 13.3 PPG) \u2014 starting combo guard, secondary score...; 3. David Mirkovic (F, Fr, 13.2 PPG, 7.8 RPG) \u2014 starting forward, double-double threa... [NBA]; 4. Tomislav Ivisic (C, Sr, 10.0 PPG, 5.6 RPG) \u2014 starting center, rim protector, inter...; 5. Ben Humrichous (F, Gr, 6.3 PPG) \u2014 starting stretch four, veteran leader...",
      "experience_score": 5.0,
      "rest_days": 6,
      "travel_distance_miles": 902.0,
      "turnover_rate": 8.9,
      "opp_fg_pct": 0.41
    },
    {
      "name": "Penn",
      "seed": 14,
      "region": "South",
      "adj_o": 104.1,
      "adj_d": 96.4,
      "adj_tempo": 67.1,
      "record": "18-11",
      "conference": "Ivy",
      "kenpom_rank": 159,
      "three_pt_pct": 32.3,
      "last_10_record": "6-4",
      "current_streak": "W2",
      "conference_tourney_result": "Ivy League Champion -- beat Harvard in OT (SF), beat Yale 88-84 OT (Final)",
      "recent_form_notes": "Penn (18-11) pulled off a stunning rally with TJ Power hitting two 3-pointers in the final 6.7 seconds of regulation to force OT, then beat Yale 88-84; Power scored 44 points as the Quakers earned their first NCAA bid since 2018 under new coach Fran McCaffery.",
      "key_players": "2. TJ Power (F, Jr, 15.4 PPG, 6.8 RPG) \u2014 Ivy Tournament MVP, scored 44 in cham...; 3. AJ Levine (G, So, 12.1 PPG) \u2014 starting guard, clutch performer, hit...; 4. Michael Zanoni (F, Sr, 10.6 PPG) \u2014 starting forward, Mercer transfer, of...; 5. Dylan Williams (G, Sr, 7.2 PPG) \u2014 starting point guard, floor general, .... MISSING: Ethan Roberts (18.0 PPG, 5.2 RPG) \u2014 Concussion; out for Ivy League Tournament and likely NCAA Tournament",
      "experience_score": 7.0,
      "rest_days": 4,
      "travel_distance_miles": 927.0,
      "turnover_rate": 10.8,
      "opp_fg_pct": 0.451
    },
    {
      "name": "Saint Mary's",
      "seed": 7,
      "region": "South",
      "adj_o": 122.5,
      "adj_d": 88.5,
      "adj_tempo": 65.9,
      "record": "27-5",
      "conference": "WCC",
      "kenpom_rank": 24,
      "three_pt_pct": 36.9,
      "last_10_record": "6-4",
      "current_streak": "L2",
      "conference_tourney_result": "WCC Semifinals -- lost to Santa Clara 76-71 (SF)",
      "recent_form_notes": "Saint Mary's (27-5) won their fourth straight WCC regular season title but were upset by Santa Clara 76-71 in the conference tournament semis; despite the stumble, a strong 27-5 record earned them a 7-seed and fifth consecutive NCAA Tournament appearance.",
      "key_players": "1. Paulius Murauskas (F, Jr, 18.6 PPG, 7.7 RPG) \u2014 primary scorer, WCC scoring leader, A... [NBA]; 2. Mikey Lewis (G, So, 13.9 PPG) \u2014 starting guard, perimeter scorer, hit...; 3. Joshua Dent (G, So, 13.3 PPG, 5.6 APG) \u2014 starting point guard, lead facilitato...; 4. Andrew McKeever (C, So, 8.3 PPG, 9.1 RPG) \u2014 starting center, WCC leading rebounde...; 5. Dillan Shaw (G, Fr, 7.5 PPG, 5.3 RPG) \u2014 key bench contributor, combo guard, e...",
      "experience_score": 4.0,
      "rest_days": 4,
      "travel_distance_miles": 2380.0,
      "turnover_rate": 10.8,
      "opp_fg_pct": 0.405
    },
    {
      "name": "Texas A&M",
      "seed": 10,
      "region": "South",
      "adj_o": 121.9,
      "adj_d": 90.3,
      "adj_tempo": 65.0,
      "record": "21-11",
      "conference": "SEC",
      "kenpom_rank": 39,
      "three_pt_pct": 35.2,
      "last_10_record": "5-5",
      "current_streak": "L1",
      "conference_tourney_result": "SEC 2nd Round -- lost to Oklahoma 83-63",
      "recent_form_notes": "Texas A&M (21-11) finished fourth in the SEC at 11-7 but was blown out by Oklahoma 83-63 in the SEC Tournament, giving up an 18-1 edge in second-chance points; the Aggies are a mediocre 10-seed entering on a loss.",
      "key_players": "1. Rashaun Agee (F, Gr, 14.7 PPG, 8.9 RPG) \u2014 leading scorer, double-double machine...; 2. Jacari Lane (G, Sr, 13.5 PPG, 5.0 APG) \u2014 starting point guard, floor general, ...; 3. Rylan Griffen (G, Sr, 12.8 PPG) \u2014 starting shooting guard, elite three-...; 4. Ruben Dominguez (G, So, 11.2 PPG) \u2014 starting guard, sharpshooting sophomo...; 5. Zach Clemence (F, Gr, 10.5 PPG) \u2014 starting forward, stretch big, rim pr...",
      "experience_score": 8.0,
      "rest_days": 5,
      "travel_distance_miles": 856.0,
      "turnover_rate": 10.8,
      "opp_fg_pct": 0.442
    },
    {
      "name": "Houston",
      "seed": 2,
      "region": "South",
      "adj_o": 125.6,
      "adj_d": 87.3,
      "adj_tempo": 68.5,
      "record": "28-6",
      "conference": "Big 12",
      "kenpom_rank": 5,
      "three_pt_pct": 36.3,
      "last_10_record": "8-2",
      "current_streak": "L1",
      "conference_tourney_result": "Big 12 Runner-Up (beat BYU 73-66 QF, beat Kansas 69-47 SF, lost to Arizona 74-79 in final)",
      "recent_form_notes": "Strong Big 12 tourney run demolishing Kansas in SF, lost close final to Arizona \u2014 6 straight Sweet 16s",
      "key_players": "1. Kingston Flemings (G, Fr, 16.5 PPG, 5.4 APG) \u2014 starting point guard, All-Big 12 Firs... [NBA]; 2. Emanuel Sharp (G, Sr, 15.8 PPG) \u2014 leading scorer, All-Big 12 First Team... [NBA]; 3. Milos Uzan (G, Sr, 11.6 PPG, 4.6 APG) \u2014 starting guard, veteran playmaker, Bi...; 4. Chris Cenac Jr. (F/C, Fr, 8.9 PPG, 7.6 RPG) \u2014 starting big, elite rebounder, lotter... [NBA]; 5. Joseph Tugler (F/C, Jr, 8.5 PPG, 5.5 RPG) \u2014 starting forward, rim protector, shot...",
      "experience_score": 5.0,
      "rest_days": 4,
      "travel_distance_miles": 789.0,
      "turnover_rate": 8.5,
      "opp_fg_pct": 0.4
    },
    {
      "name": "Idaho",
      "seed": 15,
      "region": "South",
      "adj_o": 108.3,
      "adj_d": 98.5,
      "adj_tempo": 64.4,
      "record": "21-14",
      "conference": "Big Sky",
      "kenpom_rank": 145,
      "three_pt_pct": 32.4,
      "last_10_record": "7-3",
      "current_streak": "W3",
      "conference_tourney_result": "Big Sky Champion -- beat Montana 77-66 in Final",
      "recent_form_notes": "Idaho (21-14) won its first Big Sky Tournament title since 1990, ending a 36-year NCAA Tournament drought by defeating reigning champion Montana 77-66 in the final; a feel-good story but they face a steep challenge as a 15-seed.",
      "key_players": "1. Jackson Rasmussen (F, Fr, 13.9 PPG) \u2014 leading scorer, Big Sky All-Tournamen...; 2. Kolton Mitchell (G, So, 13.7 PPG) \u2014 starting point guard, Big Sky All-Tou...; 3. Isaiah Brickner (G, Sr, 12.1 PPG) \u2014 sixth man, Big Sky All-Tournament Tea...; 4. Brody Rowbury (F/C, Sr, 9.2 PPG, 5.2 RPG) \u2014 starting center, leading rebounder, e...; 5. Biko Johnson (G, Sr, 8.8 PPG) \u2014 starting guard, veteran perimeter pre...",
      "experience_score": 5.0,
      "rest_days": 4,
      "travel_distance_miles": 2270.0,
      "turnover_rate": 10.6,
      "opp_fg_pct": 0.431
    },
    {
      "name": "Lehigh",
      "seed": 16,
      "region": "South",
      "adj_o": 96.1,
      "adj_d": 108.8,
      "adj_tempo": 68.4,
      "record": "22-12",
      "conference": "Patriot",
      "kenpom_rank": 284,
      "three_pt_pct": 31.0,
      "last_10_record": "6-4",
      "current_streak": "W3",
      "conference_tourney_result": "Patriot League Champion -- beat Boston University 74-60 in Final",
      "recent_form_notes": "Lehigh (18-16) won its fourth Patriot League title behind tournament MVP Nasir Whitlock's 23 ppg average; the Mountain Hawks are a 16-seed in the First Four despite a sub-.500 record overall.",
      "key_players": "1. Nasir Whitlock (G, Jr, 15.6 PPG) \u2014 leading scorer, team captain, First-T...; 2. Tyler Whitney-Sidney (G, Sr, 14.3 PPG) \u2014 starting guard, second-team All-Patri...; 3. Hank Alvey (F, So, 10.8 PPG, 7.1 RPG) \u2014 starting forward, Second-Team All-Pat...; 5. Jalen Vazquez (G, Jr, 7.5 PPG) \u2014 backup point guard, JUCO transfer fro.... MISSING: Keith Higgins Jr. (10.2 PPG, 3.0 RPG) \u2014 Season-ending injury; ruled out for remainder of season",
      "experience_score": 7.0,
      "rest_days": 2,
      "travel_distance_miles": 552.0,
      "turnover_rate": 12.1,
      "opp_fg_pct": 0.446
    },
    {
      "name": "Prairie View A&M",
      "seed": 16,
      "region": "South",
      "adj_o": 100.2,
      "adj_d": 103.8,
      "adj_tempo": 70.6,
      "record": "18-17",
      "conference": "SWAC",
      "kenpom_rank": 288,
      "three_pt_pct": 33.4,
      "last_10_record": "9-1",
      "current_streak": "W7",
      "conference_tourney_result": "SWAC Champion as 8-seed (beat Bethune-Cookman 71-67, Alabama A&M 74-55, Southern 72-66)",
      "recent_form_notes": "First 8-seed to win SWAC tourney in conference history; 7-game win streak; Horne and Joseph combine for nearly 40 PPG",
      "key_players": "1. Dontae Horne (G, Sr, 20.2 PPG) \u2014 primary scorer, 30-pt SWAC tourney games; 2. Tai'Reon Joseph (G, Sr, 18.2 PPG) \u2014 secondary scorer, high-volume shooter; 3. Cory Wells (F, Sr, 13.1 PPG, 7.1 RPG) \u2014 top rebounder, double-double threat; 4. Lance Williams (G, Sr, 10.1 PPG) \u2014 facilitator, best 3PT shooter (43.1%); 5. Doug Young (G, Sr, 9.3 PPG) \u2014 veteran guard, reliable contributor",
      "experience_score": 8.0,
      "rest_days": 2,
      "travel_distance_miles": 857.0,
      "turnover_rate": 11.9,
      "opp_fg_pct": 0.437
    }
  ]
}

def get_all_teams() -> list[dict]:
    """Return flat list of all teams in the bracket."""
    teams = []
    for region, region_teams in BRACKET_2026.items():
        teams.extend(region_teams)
    return teams


def get_region(region_name: str) -> list[dict]:
    """Return teams for a specific region."""
    return BRACKET_2026.get(region_name, [])


def get_matchup(region: str, seed_a: int, seed_b: int) -> tuple[dict, dict]:
    """Get a first-round matchup by region and seeds."""
    region_teams = {t["seed"]: t for t in BRACKET_2026.get(region, [])}
    return region_teams.get(seed_a), region_teams.get(seed_b)


if __name__ == "__main__":
    import json
    print(json.dumps(BRACKET_2026, indent=2))
    print(f"\nTotal teams: {len(get_all_teams())}")
