#!/usr/bin/env python3
"""
Interactive CLI to build the March Madness bracket.
Outputs bracket_loader.py and writes teams to Supabase.
"""

import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).parent / ".env")

TEAM_DATA_FILE = Path(__file__).parent / "team_data_2026.json"
OUTPUT_FILE = Path(__file__).parent / "bracket_loader.py"

REGIONS = ["East", "West", "South", "Midwest"]
SEEDS_PER_REGION = 16


def load_team_data() -> dict:
    """Load scraped team data for auto-fill."""
    if not TEAM_DATA_FILE.exists():
        print(f"  No team data file found at {TEAM_DATA_FILE}")
        print("  Run scrape_teams.py first for auto-fill, or enter data manually.")
        return {}

    try:
        with open(TEAM_DATA_FILE) as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"  Error: {TEAM_DATA_FILE} contains invalid JSON: {e}")
        return {}
    except OSError as e:
        print(f"  Error reading {TEAM_DATA_FILE}: {e}")
        return {}

    # Index by lowercase name
    index = {}
    for team in data.get("teams", []):
        name = team.get("name", "").lower().strip()
        if name:
            index[name] = team
    print(f"  Loaded {len(index)} teams from {TEAM_DATA_FILE}")
    return index


def find_team(name: str, team_index: dict) -> dict | None:
    """Look up a team in the index, with fuzzy matching."""
    from difflib import SequenceMatcher

    key = name.lower().strip()
    # Exact match first
    if key in team_index:
        return team_index[key]

    # Substring match: require the substring to be at least 4 characters
    # and match as a whole word boundary within the other string
    for k, v in team_index.items():
        if len(key) >= 4 and key in k.split():
            return v
        if len(k) >= 4 and k in key.split():
            return v

    # Fuzzy match with a high threshold
    best_match = None
    best_ratio = 0.0
    for k, v in team_index.items():
        ratio = SequenceMatcher(None, key, k).ratio()
        if ratio > best_ratio:
            best_ratio = ratio
            best_match = v
    if best_ratio >= 0.75:
        return best_match

    return None


def prompt_team(seed: int, region: str, team_index: dict) -> dict:
    """Prompt user for a single team entry."""
    name = input(f"  #{seed} seed: ").strip()
    if not name:
        return None

    # Try auto-fill from scraped data
    existing = find_team(name, team_index)
    if existing:
        print(f"    → Auto-filled stats for {existing.get('name', name)}")
        entry = {
            "name": existing.get("name", name),
            "seed": seed,
            "region": region,
            "adj_o": existing.get("adj_o", 0),
            "adj_d": existing.get("adj_d", 0),
            "adj_tempo": existing.get("adj_tempo", 0),
            "record": existing.get("record", ""),
            "conference": existing.get("conference", ""),
            "kenpom_rank": existing.get("kenpom_rank", 0),
            "three_pt_pct": existing.get("three_pt_pct", 0),
        }
    else:
        print(f"    (No auto-fill data found for '{name}')")
        entry = {
            "name": name,
            "seed": seed,
            "region": region,
            "adj_o": 0,
            "adj_d": 0,
            "adj_tempo": 0,
            "record": "",
            "conference": "",
            "kenpom_rank": 0,
            "three_pt_pct": 0,
        }

    return entry


def write_bracket_loader(bracket: dict):
    """Generate bracket_loader.py with the completed bracket data."""
    code = '''#!/usr/bin/env python3
"""
Auto-generated bracket data for March Madness Agent Swarm 2026.
Generated by fill_bracket.py
"""

BRACKET_2026 = {bracket_json}


def get_all_teams() -> list[dict]:
    """Return flat list of all teams in the bracket."""
    teams = []
    for region, region_teams in BRACKET_2026.items():
        teams.extend(region_teams)
    return teams


def get_region(region_name: str) -> list[dict]:
    """Return teams for a specific region."""
    return BRACKET_2026.get(region_name, [])


def get_matchup(region: str, seed_a: int, seed_b: int) -> tuple[dict, dict]:
    """Get a first-round matchup by region and seeds."""
    region_teams = {{t["seed"]: t for t in BRACKET_2026.get(region, [])}}
    return region_teams.get(seed_a), region_teams.get(seed_b)


if __name__ == "__main__":
    import json
    print(json.dumps(BRACKET_2026, indent=2))
    print(f"\\nTotal teams: {{len(get_all_teams())}}")
'''.format(bracket_json=json.dumps(bracket, indent=2))

    try:
        with open(OUTPUT_FILE, "w") as f:
            f.write(code)
    except OSError as e:
        print(f"\n✗ Failed to write bracket_loader.py: {e}")
        return

    print(f"\n✓ Wrote bracket_loader.py to {OUTPUT_FILE}")


def write_to_supabase(bracket: dict):
    """Write all teams to Supabase mm_teams table."""
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_KEY")

    if not url or not key or "xxxxx" in key:
        print("\n⚠ Supabase credentials not configured yet. Skipping DB write.")
        print("  Update .env with real keys, then re-run or use bracket_loader.py directly.")
        return

    try:
        from supabase import create_client
        client = create_client(url, key)

        all_teams = []
        for region, teams in bracket.items():
            for team in teams:
                row = {
                    "name": team["name"],
                    "seed": team["seed"],
                    "region": team["region"],
                    "adj_o": team["adj_o"],
                    "adj_d": team["adj_d"],
                    "adj_tempo": team["adj_tempo"],
                    "record": team["record"],
                    "conference": team["conference"],
                    "kenpom_rank": team["kenpom_rank"],
                    "three_pt_pct": team["three_pt_pct"],
                }
                if team.get("injury_notes"):
                    row["injury_notes"] = team["injury_notes"]
                all_teams.append(row)

        result = client.table("mm_teams").upsert(all_teams, on_conflict="name").execute()
        print(f"\n✓ Wrote {len(all_teams)} teams to Supabase mm_teams table")

    except Exception as e:
        print(f"\n✗ Supabase write failed: {e}")


def main():
    print("=" * 60)
    print("March Madness Agent Swarm - Bracket Builder")
    print("=" * 60)
    print("\nLoading team data for auto-fill...")

    team_index = load_team_data()

    bracket = {}

    for region in REGIONS:
        print(f"\n{'─' * 40}")
        custom_name = input(f"Region name [{region}]: ").strip()
        region_name = custom_name if custom_name else region
        print(f"Enter 16 teams for the {region_name} region (seed auto-assigned 1-16):")

        teams = []
        for seed in range(1, SEEDS_PER_REGION + 1):
            team = prompt_team(seed, region_name, team_index)
            if team:
                teams.append(team)
            else:
                print(f"    (Skipped #{seed} seed)")

        bracket[region_name] = teams
        print(f"  → {len(teams)} teams entered for {region_name}")

    # Generate bracket_loader.py
    write_bracket_loader(bracket)

    # Write to Supabase
    write_to_supabase(bracket)

    total = sum(len(t) for t in bracket.values())
    print(f"\n{'=' * 60}")
    print(f"Bracket complete! {total} teams across {len(bracket)} regions.")
    print(f"bracket_loader.py ready at: {OUTPUT_FILE}")
    print("=" * 60)


if __name__ == "__main__":
    main()
