#!/usr/bin/env python3
"""Batch 3: South region (Florida, Clemson, Iowa, Vanderbilt, McNeese, Nebraska, Troy, UNC)"""

players_batch3 = [
    # === FLORIDA (1-seed South) ===
    {"team_name": "Florida", "player_name": "Thomas Haugh", "position": "F", "year": "Jr", "points_per_game": 17.1, "rebounds_per_game": 6.2, "assists_per_game": 2.0, "fg_pct": 0.461, "three_pt_pct": 0.331, "ft_pct": 0.766, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary scorer, versatile forward", "nba_draft_prospect": True},
    {"team_name": "Florida", "player_name": "Alex Condon", "position": "F", "year": "Jr", "points_per_game": 15.0, "rebounds_per_game": 7.7, "assists_per_game": 3.5, "fg_pct": 0.548, "three_pt_pct": 0.170, "ft_pct": 0.648, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "skilled 6-11 forward, secondary playmaker, elite passer", "nba_draft_prospect": True},
    {"team_name": "Florida", "player_name": "Boogie Fland", "position": "G", "year": "So", "points_per_game": 11.6, "rebounds_per_game": 2.5, "assists_per_game": 3.4, "fg_pct": 0.435, "three_pt_pct": 0.233, "ft_pct": 0.725, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "dynamic guard, pick-and-roll prowess", "nba_draft_prospect": True},
    {"team_name": "Florida", "player_name": "Xaivian Lee", "position": "G", "year": "Sr", "points_per_game": 11.5, "rebounds_per_game": 3.8, "assists_per_game": 4.2, "fg_pct": 0.414, "three_pt_pct": 0.282, "ft_pct": 0.771, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "floor general, scores at all three levels", "nba_draft_prospect": True},
    {"team_name": "Florida", "player_name": "Rueben Chinyelu", "position": "C", "year": "Jr", "points_per_game": 11.2, "rebounds_per_game": 11.5, "assists_per_game": 0.7, "fg_pct": 0.583, "three_pt_pct": 0.0, "ft_pct": 0.690, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "elite rebounder (11.5 RPG), paint defender, program OR record", "nba_draft_prospect": True},

    # === CLEMSON (8-seed South) ===
    {"team_name": "Clemson", "player_name": "RJ Godfrey", "position": "F", "year": "Sr", "points_per_game": 11.9, "rebounds_per_game": 5.3, "assists_per_game": 1.6, "fg_pct": 0.612, "three_pt_pct": 0.222, "ft_pct": 0.662, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, highly efficient forward", "nba_draft_prospect": False},
    {"team_name": "Clemson", "player_name": "Carter Welling", "position": "C", "year": "Jr", "points_per_game": 10.2, "rebounds_per_game": 5.4, "assists_per_game": 1.1, "fg_pct": 0.493, "three_pt_pct": 0.293, "ft_pct": 0.701, "is_starter": True, "is_injured": True, "injury_details": "Torn ACL in ACC Tournament, OUT for season", "role_description": "starting center, led team in rebounds and blocks", "nba_draft_prospect": False},
    {"team_name": "Clemson", "player_name": "Jestin Porter", "position": "G", "year": "Sr", "points_per_game": 9.6, "rebounds_per_game": 1.8, "assists_per_game": 1.3, "fg_pct": 0.371, "three_pt_pct": 0.343, "ft_pct": 0.762, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "perimeter shooter, starting guard", "nba_draft_prospect": False},
    {"team_name": "Clemson", "player_name": "Nick Davidson", "position": "F", "year": "Sr", "points_per_game": 9.1, "rebounds_per_game": 4.1, "assists_per_game": 1.1, "fg_pct": 0.519, "three_pt_pct": 0.354, "ft_pct": 0.667, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "versatile bench forward, efficient scorer", "nba_draft_prospect": False},
    {"team_name": "Clemson", "player_name": "Ace Buckner", "position": "G", "year": "So", "points_per_game": 8.4, "rebounds_per_game": 2.8, "assists_per_game": 1.8, "fg_pct": 0.435, "three_pt_pct": 0.322, "ft_pct": 0.821, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "bench guard, scoring depth", "nba_draft_prospect": False},

    # === IOWA (9-seed South) ===
    {"team_name": "Iowa", "player_name": "Bennett Stirtz", "position": "G", "year": "Sr", "points_per_game": 20.0, "rebounds_per_game": 2.5, "assists_per_game": 4.5, "fg_pct": 0.492, "three_pt_pct": 0.376, "ft_pct": 0.845, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "star player, best passer in 2026 draft class", "nba_draft_prospect": True},
    {"team_name": "Iowa", "player_name": "Tavion Banks", "position": "G", "year": "Sr", "points_per_game": 10.5, "rebounds_per_game": 4.7, "assists_per_game": 1.2, "fg_pct": 0.537, "three_pt_pct": 0.472, "ft_pct": 0.810, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "sharpshooting guard, elite 3PT (47.2%)", "nba_draft_prospect": False},
    {"team_name": "Iowa", "player_name": "Alvaro Folgueiras", "position": "F", "year": "Jr", "points_per_game": 8.1, "rebounds_per_game": 3.8, "assists_per_game": 2.3, "fg_pct": 0.495, "three_pt_pct": 0.326, "ft_pct": 0.729, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "versatile bench forward", "nba_draft_prospect": False},
    {"team_name": "Iowa", "player_name": "Cooper Koch", "position": "F", "year": "So", "points_per_game": 7.7, "rebounds_per_game": 3.0, "assists_per_game": 1.1, "fg_pct": 0.437, "three_pt_pct": 0.394, "ft_pct": 0.793, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting forward, reliable 3PT shooter", "nba_draft_prospect": False},
    {"team_name": "Iowa", "player_name": "Cam Manyawu", "position": "F", "year": "Jr", "points_per_game": 7.1, "rebounds_per_game": 4.5, "assists_per_game": 1.0, "fg_pct": 0.640, "three_pt_pct": 0.0, "ft_pct": 0.603, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "interior forward, elite finishing efficiency", "nba_draft_prospect": False},

    # === VANDERBILT (5-seed South) ===
    {"team_name": "Vanderbilt", "player_name": "Tyler Tanner", "position": "G", "year": "So", "points_per_game": 19.2, "rebounds_per_game": 3.5, "assists_per_game": 5.3, "fg_pct": 0.500, "three_pt_pct": 0.373, "ft_pct": 0.853, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, floor general, lottery prospect", "nba_draft_prospect": True},
    {"team_name": "Vanderbilt", "player_name": "Duke Miles", "position": "G", "year": "Sr", "points_per_game": 16.4, "rebounds_per_game": 3.2, "assists_per_game": 4.3, "fg_pct": 0.440, "three_pt_pct": 0.361, "ft_pct": 0.894, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "veteran backcourt partner, elite FT shooter", "nba_draft_prospect": False},
    {"team_name": "Vanderbilt", "player_name": "Tyler Nickel", "position": "F", "year": "Sr", "points_per_game": 13.3, "rebounds_per_game": 3.0, "assists_per_game": 1.2, "fg_pct": 0.446, "three_pt_pct": 0.391, "ft_pct": 0.868, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "sharpshooting forward, floor spacer", "nba_draft_prospect": False},
    {"team_name": "Vanderbilt", "player_name": "AK Okereke", "position": "F", "year": "Sr", "points_per_game": 9.8, "rebounds_per_game": 3.5, "assists_per_game": 2.0, "fg_pct": 0.498, "three_pt_pct": 0.391, "ft_pct": 0.776, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile senior forward, efficient scorer", "nba_draft_prospect": False},
    {"team_name": "Vanderbilt", "player_name": "Devin McGlockton", "position": "F", "year": "Sr", "points_per_game": 9.7, "rebounds_per_game": 6.7, "assists_per_game": 1.3, "fg_pct": 0.547, "three_pt_pct": 0.303, "ft_pct": 0.784, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "physical interior forward, leading rebounder", "nba_draft_prospect": False},

    # === McNEESE (12-seed South) ===
    {"team_name": "McNeese", "player_name": "Larry Johnson", "position": "G", "year": "So", "points_per_game": 17.5, "rebounds_per_game": 5.5, "assists_per_game": 1.4, "fg_pct": 0.502, "three_pt_pct": 0.242, "ft_pct": 0.770, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, explosive, can put up 30+", "nba_draft_prospect": False},
    {"team_name": "McNeese", "player_name": "Tyshawn Archie", "position": "G", "year": "Jr", "points_per_game": 14.3, "rebounds_per_game": 1.9, "assists_per_game": 2.9, "fg_pct": 0.436, "three_pt_pct": 0.374, "ft_pct": 0.900, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "second scorer, elite FT, 3PT specialist", "nba_draft_prospect": False},
    {"team_name": "McNeese", "player_name": "Javohn Garcia", "position": "G", "year": "Sr", "points_per_game": 12.0, "rebounds_per_game": 3.1, "assists_per_game": 1.6, "fg_pct": 0.464, "three_pt_pct": 0.373, "ft_pct": 0.767, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "veteran guard, efficient scorer", "nba_draft_prospect": False},
    {"team_name": "McNeese", "player_name": "DJ Richards", "position": "G", "year": "Sr", "points_per_game": 8.3, "rebounds_per_game": 2.0, "assists_per_game": 0.7, "fg_pct": 0.371, "three_pt_pct": 0.355, "ft_pct": 0.776, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "bench scorer, 3PT specialist", "nba_draft_prospect": False},
    {"team_name": "McNeese", "player_name": "Garwey Dual", "position": "G", "year": "Jr", "points_per_game": 8.2, "rebounds_per_game": 2.8, "assists_per_game": 4.3, "fg_pct": 0.451, "three_pt_pct": 0.306, "ft_pct": 0.764, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "playmaking guard, team assist leader", "nba_draft_prospect": False},

    # === NEBRASKA (4-seed South) ===
    {"team_name": "Nebraska", "player_name": "Pryce Sandfort", "position": "F", "year": "Jr", "points_per_game": 17.8, "rebounds_per_game": 4.8, "assists_per_game": 2.0, "fg_pct": 0.471, "three_pt_pct": 0.401, "ft_pct": 0.853, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "star player, elite 3PT shooter", "nba_draft_prospect": True},
    {"team_name": "Nebraska", "player_name": "Rienk Mast", "position": "F", "year": "Sr", "points_per_game": 13.5, "rebounds_per_game": 5.8, "assists_per_game": 2.9, "fg_pct": 0.449, "three_pt_pct": 0.324, "ft_pct": 0.818, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "veteran forward, versatile playmaker", "nba_draft_prospect": False},
    {"team_name": "Nebraska", "player_name": "Braden Frager", "position": "F", "year": "Fr", "points_per_game": 11.6, "rebounds_per_game": 3.8, "assists_per_game": 0.9, "fg_pct": 0.490, "three_pt_pct": 0.348, "ft_pct": 0.816, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "talented freshman, efficient bench scorer", "nba_draft_prospect": False},
    {"team_name": "Nebraska", "player_name": "Jamarques Lawrence", "position": "G", "year": "Sr", "points_per_game": 9.7, "rebounds_per_game": 2.5, "assists_per_game": 4.0, "fg_pct": 0.413, "three_pt_pct": 0.350, "ft_pct": 0.736, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting PG, primary distributor", "nba_draft_prospect": False},
    {"team_name": "Nebraska", "player_name": "Sam Hoiberg", "position": "G", "year": "Sr", "points_per_game": 9.6, "rebounds_per_game": 5.3, "assists_per_game": 4.3, "fg_pct": 0.547, "three_pt_pct": 0.400, "ft_pct": 0.741, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile guard, elite efficiency, coach's son", "nba_draft_prospect": False},

    # === TROY (13-seed South) ===
    {"team_name": "Troy", "player_name": "Thomas Dowd", "position": "F", "year": "Jr", "points_per_game": 14.8, "rebounds_per_game": 10.1, "assists_per_game": 2.2, "fg_pct": 0.451, "three_pt_pct": 0.344, "ft_pct": 0.796, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "double-double machine (14.8/10.1)", "nba_draft_prospect": False},
    {"team_name": "Troy", "player_name": "Victor Valdes", "position": "F", "year": "Jr", "points_per_game": 14.8, "rebounds_per_game": 4.0, "assists_per_game": 4.6, "fg_pct": 0.401, "three_pt_pct": 0.223, "ft_pct": 0.759, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "co-leading scorer, top playmaker", "nba_draft_prospect": False},
    {"team_name": "Troy", "player_name": "Theo Seng", "position": "F", "year": "Sr", "points_per_game": 12.9, "rebounds_per_game": 5.8, "assists_per_game": 1.1, "fg_pct": 0.517, "three_pt_pct": 0.321, "ft_pct": 0.763, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "efficient starting forward", "nba_draft_prospect": False},
    {"team_name": "Troy", "player_name": "Cooper Campbell", "position": "G", "year": "So", "points_per_game": 12.7, "rebounds_per_game": 3.5, "assists_per_game": 4.2, "fg_pct": 0.432, "three_pt_pct": 0.386, "ft_pct": 0.831, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "explosive scoring guard, strong 3PT", "nba_draft_prospect": False},
    {"team_name": "Troy", "player_name": "Cobi Campbell", "position": "G", "year": "Sr", "points_per_game": 9.0, "rebounds_per_game": 1.8, "assists_per_game": 1.5, "fg_pct": 0.416, "three_pt_pct": 0.404, "ft_pct": 0.786, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "3PT specialist (40.4%)", "nba_draft_prospect": False},

    # === UNC (6-seed South) ===
    {"team_name": "UNC", "player_name": "Caleb Wilson", "position": "F", "year": "Fr", "points_per_game": 19.8, "rebounds_per_game": 9.4, "assists_per_game": 2.7, "fg_pct": 0.578, "three_pt_pct": 0.259, "ft_pct": 0.713, "is_starter": True, "is_injured": True, "injury_details": "Fractured left hand + broken right thumb, OUT for season", "role_description": "best player, projected top-5 NBA pick, 19.8/9.4", "nba_draft_prospect": True},
    {"team_name": "UNC", "player_name": "Henri Veesaar", "position": "F", "year": "Sr", "points_per_game": 16.7, "rebounds_per_game": 8.7, "assists_per_game": 2.0, "fg_pct": 0.614, "three_pt_pct": 0.420, "ft_pct": 0.620, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "7-foot Arizona transfer, elite efficiency, floor-spacing big", "nba_draft_prospect": True},
    {"team_name": "UNC", "player_name": "Seth Trimble", "position": "G", "year": "Sr", "points_per_game": 14.0, "rebounds_per_game": 3.6, "assists_per_game": 2.8, "fg_pct": 0.472, "three_pt_pct": 0.288, "ft_pct": 0.672, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "veteran guard, expanded role with Wilson out", "nba_draft_prospect": False},
    {"team_name": "UNC", "player_name": "Luka Bogavac", "position": "G", "year": "Jr", "points_per_game": 9.8, "rebounds_per_game": 2.5, "assists_per_game": 2.2, "fg_pct": 0.404, "three_pt_pct": 0.359, "ft_pct": 0.736, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "3PT shooter, perimeter scoring", "nba_draft_prospect": False},
    {"team_name": "UNC", "player_name": "Jarin Stevenson", "position": "F", "year": "Jr", "points_per_game": 8.0, "rebounds_per_game": 4.4, "assists_per_game": 0.9, "fg_pct": 0.472, "three_pt_pct": 0.294, "ft_pct": 0.744, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "versatile forward, bigger role with Wilson out", "nba_draft_prospect": False},
]
