#!/usr/bin/env python3
"""Batch 7: Midwest main (Michigan, Georgia, Saint Louis, Texas Tech, Akron, Alabama, Hofstra, Tennessee)"""

players_batch7 = [
    # === MICHIGAN (1-seed Midwest) ===
    {"team_name": "Michigan", "player_name": "Yaxel Lendeborg", "position": "F", "year": "Sr", "points_per_game": 14.4, "rebounds_per_game": 7.0, "assists_per_game": 3.3, "fg_pct": 0.506, "three_pt_pct": 0.343, "ft_pct": 0.820, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "Big Ten POY, versatile senior forward", "nba_draft_prospect": True},
    {"team_name": "Michigan", "player_name": "Morez Johnson Jr.", "position": "F", "year": "So", "points_per_game": 13.3, "rebounds_per_game": 7.3, "assists_per_game": 1.2, "fg_pct": 0.629, "three_pt_pct": 0.393, "ft_pct": 0.787, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "explosive sophomore, 7-2 wingspan, physical interior", "nba_draft_prospect": True},
    {"team_name": "Michigan", "player_name": "Aday Mara", "position": "C", "year": "Jr", "points_per_game": 11.6, "rebounds_per_game": 6.9, "assists_per_game": 2.3, "fg_pct": 0.670, "three_pt_pct": 0.250, "ft_pct": 0.540, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "7-3 center, elite rim protector, skilled passer", "nba_draft_prospect": True},
    {"team_name": "Michigan", "player_name": "Elliot Cadeau", "position": "G", "year": "Jr", "points_per_game": 10.2, "rebounds_per_game": 2.6, "assists_per_game": 5.4, "fg_pct": 0.424, "three_pt_pct": 0.380, "ft_pct": 0.716, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting PG, UNC transfer, team assist leader", "nba_draft_prospect": False},
    {"team_name": "Michigan", "player_name": "Trey McKenney", "position": "G", "year": "Fr", "points_per_game": 9.7, "rebounds_per_game": 2.5, "assists_per_game": 0.8, "fg_pct": 0.453, "three_pt_pct": 0.381, "ft_pct": 0.910, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "freshman sharpshooter, expanded role after Cason injury", "nba_draft_prospect": False},

    # === GEORGIA (8-seed Midwest) ===
    {"team_name": "Georgia", "player_name": "Jeremiah Wilkinson", "position": "G", "year": "So", "points_per_game": 17.0, "rebounds_per_game": 2.0, "assists_per_game": 1.8, "fg_pct": 0.409, "three_pt_pct": 0.350, "ft_pct": 0.779, "is_starter": True, "is_injured": False, "injury_details": "Missed games with shoulder mid-season, returned", "role_description": "leading scorer, Cal transfer", "nba_draft_prospect": False},
    {"team_name": "Georgia", "player_name": "Blue Cain", "position": "G", "year": "Jr", "points_per_game": 13.3, "rebounds_per_game": 5.1, "assists_per_game": 2.7, "fg_pct": 0.472, "three_pt_pct": 0.308, "ft_pct": 0.905, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "breakout junior, elite FT (90.5%)", "nba_draft_prospect": True},
    {"team_name": "Georgia", "player_name": "Kanon Catchings", "position": "F", "year": "So", "points_per_game": 12.0, "rebounds_per_game": 4.8, "assists_per_game": 1.2, "fg_pct": 0.438, "three_pt_pct": 0.386, "ft_pct": 0.651, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile sophomore, reliable 3PT", "nba_draft_prospect": False},
    {"team_name": "Georgia", "player_name": "Marcus Millender", "position": "G", "year": "Jr", "points_per_game": 11.9, "rebounds_per_game": 2.8, "assists_per_game": 4.0, "fg_pct": 0.459, "three_pt_pct": 0.393, "ft_pct": 0.848, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "team assist leader, strong 3PT off bench", "nba_draft_prospect": False},
    {"team_name": "Georgia", "player_name": "Somto Cyril", "position": "C", "year": "So", "points_per_game": 9.6, "rebounds_per_game": 5.6, "assists_per_game": 0.6, "fg_pct": 0.764, "three_pt_pct": 0.0, "ft_pct": 0.578, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "elite FG% (76.4%), interior finisher", "nba_draft_prospect": False},

    # === SAINT LOUIS (9-seed Midwest) ===
    {"team_name": "Saint Louis", "player_name": "Robbie Avila", "position": "C", "year": "Sr", "points_per_game": 12.9, "rebounds_per_game": 4.5, "assists_per_game": 4.1, "fg_pct": 0.506, "three_pt_pct": 0.416, "ft_pct": 0.805, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "A-10 POY, 6-10 skilled passer, 3PT big man", "nba_draft_prospect": True},
    {"team_name": "Saint Louis", "player_name": "Dion Brown", "position": "G", "year": "Sr", "points_per_game": 11.1, "rebounds_per_game": 5.5, "assists_per_game": 1.5, "fg_pct": 0.606, "three_pt_pct": 0.404, "ft_pct": 0.750, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "elite efficiency (60.6% FG, 40.4% 3PT)", "nba_draft_prospect": False},
    {"team_name": "Saint Louis", "player_name": "Trey Green", "position": "G", "year": "Jr", "points_per_game": 11.1, "rebounds_per_game": 2.8, "assists_per_game": 1.7, "fg_pct": 0.472, "three_pt_pct": 0.457, "ft_pct": 0.861, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "elite 3PT sniper (45.7%)", "nba_draft_prospect": False},
    {"team_name": "Saint Louis", "player_name": "Amari McCottry", "position": "G", "year": "So", "points_per_game": 10.3, "rebounds_per_game": 5.2, "assists_per_game": 2.8, "fg_pct": 0.508, "three_pt_pct": 0.290, "ft_pct": 0.583, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "all-around sophomore, strong rebounder", "nba_draft_prospect": False},
    {"team_name": "Saint Louis", "player_name": "Kellen Thames", "position": "G", "year": "Jr", "points_per_game": 9.9, "rebounds_per_game": 4.8, "assists_per_game": 1.9, "fg_pct": 0.649, "three_pt_pct": 0.182, "ft_pct": 0.650, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "school-record FG%, A-10 Third Team, 40 steals", "nba_draft_prospect": False},

    # === TEXAS TECH (5-seed Midwest) ===
    {"team_name": "Texas Tech", "player_name": "JT Toppin", "position": "F", "year": "Jr", "points_per_game": 21.8, "rebounds_per_game": 10.8, "assists_per_game": 2.1, "fg_pct": 0.548, "three_pt_pct": 0.281, "ft_pct": 0.579, "is_starter": True, "is_injured": True, "injury_details": "Torn ACL Feb 18, OUT for season", "role_description": "All-American, Big 12 POY, dominant double-double", "nba_draft_prospect": True},
    {"team_name": "Texas Tech", "player_name": "Christian Anderson", "position": "G", "year": "So", "points_per_game": 18.9, "rebounds_per_game": 3.6, "assists_per_game": 7.6, "fg_pct": 0.479, "three_pt_pct": 0.425, "ft_pct": 0.795, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "star PG, Wooden ballot, projected 1st round pick", "nba_draft_prospect": True},
    {"team_name": "Texas Tech", "player_name": "Donovan Atwell", "position": "F", "year": "Sr", "points_per_game": 13.5, "rebounds_per_game": 3.3, "assists_per_game": 0.8, "fg_pct": 0.458, "three_pt_pct": 0.454, "ft_pct": 0.842, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "senior sharpshooter, 45.4% 3PT", "nba_draft_prospect": False},
    {"team_name": "Texas Tech", "player_name": "LeJuan Watts", "position": "F", "year": "Jr", "points_per_game": 11.5, "rebounds_per_game": 6.0, "assists_per_game": 2.5, "fg_pct": 0.428, "three_pt_pct": 0.329, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "6-6 wing, increased post duties with Toppin out", "nba_draft_prospect": False},
    {"team_name": "Texas Tech", "player_name": "Jaylen Petty", "position": "G", "year": "Fr", "points_per_game": 9.5, "rebounds_per_game": 3.9, "assists_per_game": 2.2, "fg_pct": 0.400, "three_pt_pct": 0.372, "ft_pct": 0.786, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "freshman stepped into starting lineup", "nba_draft_prospect": False},

    # === AKRON (12-seed Midwest) ===
    {"team_name": "Akron", "player_name": "Tavari Johnson", "position": "G", "year": "Sr", "points_per_game": 20.1, "rebounds_per_game": 3.0, "assists_per_game": 5.0, "fg_pct": 0.512, "three_pt_pct": 0.373, "ft_pct": 0.870, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "MAC star, 20+ PPG, MAC Tourney hero (25 pts)", "nba_draft_prospect": False},
    {"team_name": "Akron", "player_name": "Amani Lyles", "position": "F", "year": "Sr", "points_per_game": 14.6, "rebounds_per_game": 8.0, "assists_per_game": 2.2, "fg_pct": 0.557, "three_pt_pct": 0.375, "ft_pct": 0.710, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "double-double threat, leading rebounder", "nba_draft_prospect": False},
    {"team_name": "Akron", "player_name": "Shammah Scott", "position": "G", "year": "Sr", "points_per_game": 12.7, "rebounds_per_game": 2.6, "assists_per_game": 2.9, "fg_pct": 0.449, "three_pt_pct": 0.422, "ft_pct": 0.780, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "elite 3PT (42.2%), instant offense off bench", "nba_draft_prospect": False},
    {"team_name": "Akron", "player_name": "Evan Mahaffey", "position": "F", "year": "Sr", "points_per_game": 10.2, "rebounds_per_game": 5.6, "assists_per_game": 3.5, "fg_pct": 0.585, "three_pt_pct": 0.318, "ft_pct": 0.576, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "most versatile player, strong passer for F", "nba_draft_prospect": False},
    {"team_name": "Akron", "player_name": "Bowen Hardman", "position": "G", "year": "Sr", "points_per_game": 7.9, "rebounds_per_game": 1.6, "assists_per_game": 0.2, "fg_pct": 0.407, "three_pt_pct": 0.407, "ft_pct": 0.833, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "bench sharpshooter, 40.7% 3PT", "nba_draft_prospect": False},

    # === ALABAMA (4-seed Midwest) ===
    {"team_name": "Alabama", "player_name": "Labaron Philon", "position": "G", "year": "So", "points_per_game": 21.7, "rebounds_per_game": 3.2, "assists_per_game": 4.7, "fg_pct": 0.509, "three_pt_pct": 0.402, "ft_pct": 0.787, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "All-SEC, elite shot creator, projected 1st round", "nba_draft_prospect": True},
    {"team_name": "Alabama", "player_name": "Aden Holloway", "position": "G", "year": "Jr", "points_per_game": 16.8, "rebounds_per_game": 2.8, "assists_per_game": 3.8, "fg_pct": 0.481, "three_pt_pct": 0.438, "ft_pct": 0.864, "is_starter": True, "is_injured": False, "injury_details": "Wrist injury flare-ups, day-to-day", "role_description": "Auburn transfer, elite 3PT (43.8%)", "nba_draft_prospect": False},
    {"team_name": "Alabama", "player_name": "Latrell Wrightsell Jr.", "position": "G", "year": "Sr", "points_per_game": 12.8, "rebounds_per_game": 3.1, "assists_per_game": 2.0, "fg_pct": 0.398, "three_pt_pct": 0.357, "ft_pct": 0.813, "is_starter": False, "is_injured": False, "injury_details": "Missed 8 games with injuries including knee", "role_description": "veteran guard, prior Achilles tear, impactful when healthy", "nba_draft_prospect": False},
    {"team_name": "Alabama", "player_name": "Amari Allen", "position": "F", "year": "Fr", "points_per_game": 11.7, "rebounds_per_game": 7.1, "assists_per_game": 3.1, "fg_pct": 0.455, "three_pt_pct": 0.365, "ft_pct": 0.737, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "freshman sensation, projected top-20 pick", "nba_draft_prospect": True},
    {"team_name": "Alabama", "player_name": "Aiden Sherrell", "position": "F", "year": "So", "points_per_game": 11.1, "rebounds_per_game": 6.1, "assists_per_game": 1.1, "fg_pct": 0.551, "three_pt_pct": 0.324, "ft_pct": 0.705, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "efficient interior scorer, started all 31 games", "nba_draft_prospect": False},

    # === HOFSTRA (13-seed Midwest) ===
    {"team_name": "Hofstra", "player_name": "Cruz Davis", "position": "G", "year": "Sr", "points_per_game": 20.2, "rebounds_per_game": 3.7, "assists_per_game": 4.6, "fg_pct": 0.443, "three_pt_pct": 0.399, "ft_pct": 0.829, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "CAA star, 20+ PPG, dropped 36 at Pitt", "nba_draft_prospect": False},
    {"team_name": "Hofstra", "player_name": "Preston Edmead", "position": "G", "year": "Fr", "points_per_game": 15.9, "rebounds_per_game": 3.5, "assists_per_game": 4.4, "fg_pct": 0.404, "three_pt_pct": 0.383, "ft_pct": 0.833, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "dynamic freshman, top CAA freshman", "nba_draft_prospect": False},
    {"team_name": "Hofstra", "player_name": "James Patterson", "position": "G", "year": "Sr", "points_per_game": 9.5, "rebounds_per_game": 5.6, "assists_per_game": 0.4, "fg_pct": 0.407, "three_pt_pct": 0.318, "ft_pct": 0.761, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "strong rebounder for guard (5.6 RPG)", "nba_draft_prospect": False},
    {"team_name": "Hofstra", "player_name": "German Plotnikov", "position": "G", "year": "Sr", "points_per_game": 9.3, "rebounds_per_game": 3.4, "assists_per_game": 0.8, "fg_pct": 0.422, "three_pt_pct": 0.377, "ft_pct": 0.851, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "consistent starter, reliable 3PT", "nba_draft_prospect": False},
    {"team_name": "Hofstra", "player_name": "Joshua DeCady", "position": "F", "year": "So", "points_per_game": 6.3, "rebounds_per_game": 3.4, "assists_per_game": 0.6, "fg_pct": 0.415, "three_pt_pct": 0.281, "ft_pct": 0.577, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "sophomore forward, provides size", "nba_draft_prospect": False},

    # === TENNESSEE (6-seed Midwest) ===
    {"team_name": "Tennessee", "player_name": "Ja'Kobi Gillespie", "position": "G", "year": "Sr", "points_per_game": 18.0, "rebounds_per_game": 2.8, "assists_per_game": 5.5, "fg_pct": 0.407, "three_pt_pct": 0.332, "ft_pct": 0.803, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, veteran leader, 32 vs Rutgers", "nba_draft_prospect": False},
    {"team_name": "Tennessee", "player_name": "Nate Ament", "position": "F", "year": "Fr", "points_per_game": 17.5, "rebounds_per_game": 6.6, "assists_per_game": 2.5, "fg_pct": 0.405, "three_pt_pct": 0.331, "ft_pct": 0.789, "is_starter": True, "is_injured": False, "injury_details": "Sprained ankle Feb 28, returned for SEC Tourney but not 100%", "role_description": "star freshman, projected top-10 NBA pick", "nba_draft_prospect": True},
    {"team_name": "Tennessee", "player_name": "J.P. Estrella", "position": "F", "year": "Jr", "points_per_game": 10.1, "rebounds_per_game": 5.2, "assists_per_game": 0.8, "fg_pct": 0.614, "three_pt_pct": 0.400, "ft_pct": 0.667, "is_starter": False, "is_injured": False, "injury_details": "Foot soreness in Feb, missed 2 games, returned", "role_description": "elite efficiency (61.4% FG), interior scoring", "nba_draft_prospect": False},
    {"team_name": "Tennessee", "player_name": "Felix Okpara", "position": "C", "year": "Sr", "points_per_game": 7.7, "rebounds_per_game": 6.2, "assists_per_game": 0.5, "fg_pct": 0.588, "three_pt_pct": 0.364, "ft_pct": 0.645, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting center, rim protector, defensive anchor", "nba_draft_prospect": False},
    {"team_name": "Tennessee", "player_name": "Jaylen Carey", "position": "F", "year": "Jr", "points_per_game": 7.4, "rebounds_per_game": 6.2, "assists_per_game": 1.3, "fg_pct": 0.473, "three_pt_pct": 0.0, "ft_pct": 0.485, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "energy rebounder off bench, no 3PT attempts", "nba_draft_prospect": False},
]
