#!/usr/bin/env python3
"""Batch 4: West region (Arizona, Villanova, Utah State, Wisconsin, High Point, Arkansas, Hawaii, BYU)"""

players_batch4 = [
    # === ARIZONA (1-seed West) ===
    {"team_name": "Arizona", "player_name": "Brayden Burries", "position": "G", "year": "Fr", "points_per_game": 15.9, "rebounds_per_game": 4.7, "assists_per_game": 2.5, "fg_pct": 0.492, "three_pt_pct": 0.365, "ft_pct": 0.820, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, explosive freshman combo guard", "nba_draft_prospect": True},
    {"team_name": "Arizona", "player_name": "Koa Peat", "position": "F", "year": "Fr", "points_per_game": 13.6, "rebounds_per_game": 5.3, "assists_per_game": 2.7, "fg_pct": 0.537, "three_pt_pct": 0.316, "ft_pct": 0.720, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile 6-8 freshman forward, elite upside", "nba_draft_prospect": True},
    {"team_name": "Arizona", "player_name": "Jaden Bradley", "position": "G", "year": "Sr", "points_per_game": 13.4, "rebounds_per_game": 3.5, "assists_per_game": 4.6, "fg_pct": 0.461, "three_pt_pct": 0.300, "ft_pct": 0.785, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "floor general, team leader, Alabama transfer", "nba_draft_prospect": False},
    {"team_name": "Arizona", "player_name": "Motiejus Krivas", "position": "C", "year": "Jr", "points_per_game": 10.5, "rebounds_per_game": 8.1, "assists_per_game": 1.0, "fg_pct": 0.582, "three_pt_pct": 0.333, "ft_pct": 0.786, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "7-2 rim protector, 1.9 BPG, interior anchor", "nba_draft_prospect": True},
    {"team_name": "Arizona", "player_name": "Tobe Awaka", "position": "F", "year": "Sr", "points_per_game": 9.6, "rebounds_per_game": 7.8, "assists_per_game": 1.0, "fg_pct": 0.605, "three_pt_pct": 0.0, "ft_pct": 0.620, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "Big 12 Sixth Man of the Year, energy big", "nba_draft_prospect": False},

    # === VILLANOVA (8-seed West) ===
    {"team_name": "Villanova", "player_name": "Tyler Perkins", "position": "F", "year": "Jr", "points_per_game": 13.6, "rebounds_per_game": 6.2, "assists_per_game": 1.5, "fg_pct": 0.480, "three_pt_pct": 0.350, "ft_pct": 0.760, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "team-leading scorer, versatile forward", "nba_draft_prospect": False},
    {"team_name": "Villanova", "player_name": "Duke Brennan", "position": "F", "year": "So", "points_per_game": 12.4, "rebounds_per_game": 8.5, "assists_per_game": 1.2, "fg_pct": 0.520, "three_pt_pct": 0.300, "ft_pct": 0.700, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "physical interior, double-double threat", "nba_draft_prospect": True},
    {"team_name": "Villanova", "player_name": "Acaden Lewis", "position": "G", "year": "So", "points_per_game": 12.4, "rebounds_per_game": 3.2, "assists_per_game": 5.8, "fg_pct": 0.430, "three_pt_pct": 0.360, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary ball-handler, leads team in assists", "nba_draft_prospect": False},
    {"team_name": "Villanova", "player_name": "Devin Askew", "position": "G", "year": "Sr", "points_per_game": 11.2, "rebounds_per_game": 2.8, "assists_per_game": 3.5, "fg_pct": 0.425, "three_pt_pct": 0.370, "ft_pct": 0.820, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "veteran guard, explosive scorer", "nba_draft_prospect": False},
    {"team_name": "Villanova", "player_name": "Eric Dixon Jr.", "position": "F", "year": "Gr", "points_per_game": 10.5, "rebounds_per_game": 5.5, "assists_per_game": 1.8, "fg_pct": 0.460, "three_pt_pct": 0.340, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "veteran stretch forward", "nba_draft_prospect": False},

    # === UTAH STATE (9-seed West) ===
    {"team_name": "Utah State", "player_name": "MJ Collins", "position": "G", "year": "Sr", "points_per_game": 17.9, "rebounds_per_game": 3.5, "assists_per_game": 2.8, "fg_pct": 0.540, "three_pt_pct": 0.500, "ft_pct": 0.817, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, MW Tourney MVP, 50% 3PT", "nba_draft_prospect": False},
    {"team_name": "Utah State", "player_name": "Mason Falslev", "position": "G", "year": "Jr", "points_per_game": 16.0, "rebounds_per_game": 6.1, "assists_per_game": 3.7, "fg_pct": 0.470, "three_pt_pct": 0.380, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "Mountain West POY, all-around playmaker", "nba_draft_prospect": False},
    {"team_name": "Utah State", "player_name": "Garry Clark", "position": "F", "year": "Gr", "points_per_game": 10.3, "rebounds_per_game": 6.8, "assists_per_game": 1.0, "fg_pct": 0.500, "three_pt_pct": 0.320, "ft_pct": 0.680, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "physical forward, elite offensive rebounding", "nba_draft_prospect": False},
    {"team_name": "Utah State", "player_name": "Karson Templin", "position": "F", "year": "Jr", "points_per_game": 8.9, "rebounds_per_game": 4.3, "assists_per_game": 1.0, "fg_pct": 0.460, "three_pt_pct": 0.340, "ft_pct": 0.820, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile 6-9 stretch forward", "nba_draft_prospect": False},
    {"team_name": "Utah State", "player_name": "Drake Allen", "position": "G", "year": "Jr", "points_per_game": 7.5, "rebounds_per_game": 2.3, "assists_per_game": 2.0, "fg_pct": 0.420, "three_pt_pct": 0.360, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting guard, perimeter shooter", "nba_draft_prospect": False},

    # === WISCONSIN (5-seed West) ===
    {"team_name": "Wisconsin", "player_name": "Nick Boyd", "position": "G", "year": "Sr", "points_per_game": 20.6, "rebounds_per_game": 3.8, "assists_per_game": 4.2, "fg_pct": 0.479, "three_pt_pct": 0.364, "ft_pct": 0.824, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, 4th-highest in program history", "nba_draft_prospect": True},
    {"team_name": "Wisconsin", "player_name": "John Blackwell", "position": "G", "year": "Jr", "points_per_game": 18.8, "rebounds_per_game": 4.9, "assists_per_game": 2.3, "fg_pct": 0.422, "three_pt_pct": 0.387, "ft_pct": 0.853, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "dynamic scoring guard, career-high 34 in BTT", "nba_draft_prospect": True},
    {"team_name": "Wisconsin", "player_name": "Nolan Winter", "position": "C", "year": "Jr", "points_per_game": 13.5, "rebounds_per_game": 8.7, "assists_per_game": 1.5, "fg_pct": 0.520, "three_pt_pct": 0.330, "ft_pct": 0.720, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "7-foot center, stretches floor, anchor rebounder", "nba_draft_prospect": True},
    {"team_name": "Wisconsin", "player_name": "Austin Rapp", "position": "F", "year": "So", "points_per_game": 9.3, "rebounds_per_game": 3.9, "assists_per_game": 1.6, "fg_pct": 0.411, "three_pt_pct": 0.347, "ft_pct": 0.848, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "floor spacer, reliable FT shooter", "nba_draft_prospect": False},
    {"team_name": "Wisconsin", "player_name": "Braeden Carrington", "position": "G", "year": "Sr", "points_per_game": 8.4, "rebounds_per_game": 2.5, "assists_per_game": 1.0, "fg_pct": 0.440, "three_pt_pct": 0.400, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "sharpshooting guard, multiple school records", "nba_draft_prospect": False},

    # === HIGH POINT (12-seed West) ===
    {"team_name": "High Point", "player_name": "Terry Anderson", "position": "F", "year": "Sr", "points_per_game": 16.0, "rebounds_per_game": 6.1, "assists_per_game": 1.6, "fg_pct": 0.500, "three_pt_pct": 0.330, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer and rebounder", "nba_draft_prospect": False},
    {"team_name": "High Point", "player_name": "Rob Martin", "position": "G", "year": "Sr", "points_per_game": 15.0, "rebounds_per_game": 2.0, "assists_per_game": 4.5, "fg_pct": 0.440, "three_pt_pct": 0.330, "ft_pct": 0.840, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "dynamic PG, leads team in assists/steals", "nba_draft_prospect": False},
    {"team_name": "High Point", "player_name": "Vincent Brady II", "position": "G", "year": "Sr", "points_per_game": 10.5, "rebounds_per_game": 3.0, "assists_per_game": 2.0, "fg_pct": 0.420, "three_pt_pct": 0.350, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "experienced guard, backcourt depth", "nba_draft_prospect": False},
    {"team_name": "High Point", "player_name": "Babacar Diallo", "position": "G", "year": "Jr", "points_per_game": 8.2, "rebounds_per_game": 3.2, "assists_per_game": 2.6, "fg_pct": 0.400, "three_pt_pct": 0.300, "ft_pct": 0.720, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile guard-forward, connector", "nba_draft_prospect": False},
    {"team_name": "High Point", "player_name": "David Fonville", "position": "G", "year": "So", "points_per_game": 7.5, "rebounds_per_game": 2.5, "assists_per_game": 1.5, "fg_pct": 0.430, "three_pt_pct": 0.340, "ft_pct": 0.750, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "bench guard, energy scorer", "nba_draft_prospect": False},

    # === ARKANSAS (4-seed West) ===
    {"team_name": "Arkansas", "player_name": "Darius Acuff Jr.", "position": "G", "year": "Fr", "points_per_game": 22.7, "rebounds_per_game": 3.2, "assists_per_game": 6.4, "fg_pct": 0.487, "three_pt_pct": 0.437, "ft_pct": 0.850, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "SEC POY, Wooden finalist, 1st Team All-American", "nba_draft_prospect": True},
    {"team_name": "Arkansas", "player_name": "Meleek Thomas", "position": "G", "year": "Fr", "points_per_game": 15.6, "rebounds_per_game": 3.8, "assists_per_game": 2.5, "fg_pct": 0.430, "three_pt_pct": 0.425, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "five-star freshman, SEC All-Freshman", "nba_draft_prospect": True},
    {"team_name": "Arkansas", "player_name": "Trevon Brazile", "position": "F", "year": "Sr", "points_per_game": 12.8, "rebounds_per_game": 7.2, "assists_per_game": 1.5, "fg_pct": 0.500, "three_pt_pct": 0.320, "ft_pct": 0.700, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "senior forward, top rebounder", "nba_draft_prospect": False},
    {"team_name": "Arkansas", "player_name": "Billy Richmond III", "position": "G", "year": "So", "points_per_game": 11.1, "rebounds_per_game": 3.9, "assists_per_game": 2.0, "fg_pct": 0.470, "three_pt_pct": 0.350, "ft_pct": 0.760, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "emerging sophomore, SEC postseason honors", "nba_draft_prospect": False},
    {"team_name": "Arkansas", "player_name": "Karter Knox", "position": "F", "year": "So", "points_per_game": 8.4, "rebounds_per_game": 3.3, "assists_per_game": 1.2, "fg_pct": 0.460, "three_pt_pct": 0.330, "ft_pct": 0.720, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "withdrew from 2025 draft to return", "nba_draft_prospect": False},

    # === HAWAII (13-seed West) ===
    {"team_name": "Hawaii", "player_name": "Isaac Johnson", "position": "C", "year": "Sr", "points_per_game": 13.7, "rebounds_per_game": 8.0, "assists_per_game": 1.0, "fg_pct": 0.550, "three_pt_pct": 0.0, "ft_pct": 0.680, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "7-0 center, All-Big West, dominant interior", "nba_draft_prospect": False},
    {"team_name": "Hawaii", "player_name": "Dre Bullock", "position": "G", "year": "Gr", "points_per_game": 12.3, "rebounds_per_game": 4.0, "assists_per_game": 2.0, "fg_pct": 0.440, "three_pt_pct": 0.370, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "All-Big West, experienced grad transfer", "nba_draft_prospect": False},
    {"team_name": "Hawaii", "player_name": "Harry Rouhliadeff", "position": "C", "year": "Sr", "points_per_game": 11.7, "rebounds_per_game": 5.3, "assists_per_game": 1.8, "fg_pct": 0.480, "three_pt_pct": 0.300, "ft_pct": 0.720, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "team captain, 4-year player, double-double threat", "nba_draft_prospect": False},
    {"team_name": "Hawaii", "player_name": "Gytis Nemeiksa", "position": "F", "year": "Sr", "points_per_game": 10.0, "rebounds_per_game": 5.2, "assists_per_game": 1.0, "fg_pct": 0.460, "three_pt_pct": 0.330, "ft_pct": 0.700, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "preseason All-Big West, Lithuanian forward", "nba_draft_prospect": False},
    {"team_name": "Hawaii", "player_name": "Aaron Hunkin-Claytor", "position": "G", "year": "So", "points_per_game": 8.5, "rebounds_per_game": 3.0, "assists_per_game": 3.9, "fg_pct": 0.400, "three_pt_pct": 0.320, "ft_pct": 0.740, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "freshman PG, leads team in assists/steals", "nba_draft_prospect": False},

    # === BYU (6-seed West) ===
    {"team_name": "BYU", "player_name": "AJ Dybantsa", "position": "F", "year": "Fr", "points_per_game": 25.3, "rebounds_per_game": 6.7, "assists_per_game": 3.8, "fg_pct": 0.513, "three_pt_pct": 0.340, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "Big 12 leading scorer, projected #1 overall pick", "nba_draft_prospect": True},
    {"team_name": "BYU", "player_name": "Robert Wright III", "position": "G", "year": "So", "points_per_game": 18.5, "rebounds_per_game": 3.5, "assists_per_game": 4.8, "fg_pct": 0.470, "three_pt_pct": 0.460, "ft_pct": 0.820, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "stepped up after Saunders injury, elite 3PT", "nba_draft_prospect": True},
    {"team_name": "BYU", "player_name": "Richie Saunders", "position": "G", "year": "Sr", "points_per_game": 18.0, "rebounds_per_game": 5.8, "assists_per_game": 2.1, "fg_pct": 0.489, "three_pt_pct": 0.376, "ft_pct": 0.800, "is_starter": True, "is_injured": True, "injury_details": "Torn ACL Feb 15, OUT for season", "role_description": "was 2nd leading scorer before torn ACL", "nba_draft_prospect": False},
    {"team_name": "BYU", "player_name": "Kennard Davis Jr.", "position": "F", "year": "Jr", "points_per_game": 7.2, "rebounds_per_game": 4.0, "assists_per_game": 0.8, "fg_pct": 0.440, "three_pt_pct": 0.291, "ft_pct": 0.700, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "SIU transfer, 6-11 forward, scored 20 in BTT", "nba_draft_prospect": False},
    {"team_name": "BYU", "player_name": "Keba Keita", "position": "C", "year": "Sr", "points_per_game": 6.3, "rebounds_per_game": 7.3, "assists_per_game": 0.3, "fg_pct": 0.677, "three_pt_pct": 0.0, "ft_pct": 0.550, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "elite FG%, leads offensive rebounding", "nba_draft_prospect": False},
]
