#!/usr/bin/env python3
"""Batch 6: East small seeds (TCU, Northern Iowa, Cal Baptist, USF, NDSU, UCF, Furman, Siena)"""

players_batch6 = [
    # === TCU (9-seed East) ===
    {"team_name": "TCU", "player_name": "David Punch", "position": "F", "year": "So", "points_per_game": 13.6, "rebounds_per_game": 6.6, "assists_per_game": 2.1, "fg_pct": 0.508, "three_pt_pct": 0.280, "ft_pct": 0.680, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary interior scorer, physical forward", "nba_draft_prospect": True},
    {"team_name": "TCU", "player_name": "Xavier Edmonds", "position": "F", "year": "Jr", "points_per_game": 12.8, "rebounds_per_game": 6.6, "assists_per_game": 1.2, "fg_pct": 0.576, "three_pt_pct": 0.350, "ft_pct": 0.720, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "efficient forward, double-double threat", "nba_draft_prospect": False},
    {"team_name": "TCU", "player_name": "Micah Robinson", "position": "F", "year": "So", "points_per_game": 10.6, "rebounds_per_game": 4.7, "assists_per_game": 1.8, "fg_pct": 0.450, "three_pt_pct": 0.330, "ft_pct": 0.740, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "athletic 6-6 wing", "nba_draft_prospect": False},
    {"team_name": "TCU", "player_name": "Jayden Pierre", "position": "G", "year": "Sr", "points_per_game": 10.4, "rebounds_per_game": 3.2, "assists_per_game": 2.6, "fg_pct": 0.420, "three_pt_pct": 0.350, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "floor general, Providence transfer", "nba_draft_prospect": False},
    {"team_name": "TCU", "player_name": "Kayden Edwards", "position": "G", "year": "Fr", "points_per_game": 8.5, "rebounds_per_game": 2.8, "assists_per_game": 2.0, "fg_pct": 0.440, "three_pt_pct": 0.360, "ft_pct": 0.760, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "four-star freshman combo guard", "nba_draft_prospect": False},

    # === NORTHERN IOWA (12-seed East) ===
    {"team_name": "Northern Iowa", "player_name": "Trey Campbell", "position": "G", "year": "Sr", "points_per_game": 13.2, "rebounds_per_game": 4.2, "assists_per_game": 3.0, "fg_pct": 0.434, "three_pt_pct": 0.323, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, All-MVC, 50 steals", "nba_draft_prospect": False},
    {"team_name": "Northern Iowa", "player_name": "Leon Bond III", "position": "G", "year": "Jr", "points_per_game": 11.5, "rebounds_per_game": 5.0, "assists_per_game": 1.3, "fg_pct": 0.450, "three_pt_pct": 0.340, "ft_pct": 0.720, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "All-MVC, All-Defensive, Virginia transfer", "nba_draft_prospect": False},
    {"team_name": "Northern Iowa", "player_name": "Will Hornseth", "position": "F", "year": "Gr", "points_per_game": 11.3, "rebounds_per_game": 4.6, "assists_per_game": 1.5, "fg_pct": 0.480, "three_pt_pct": 0.320, "ft_pct": 0.730, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "experienced 6-6 grad forward", "nba_draft_prospect": False},
    {"team_name": "Northern Iowa", "player_name": "Tristan Smith", "position": "F", "year": "Sr", "points_per_game": 9.9, "rebounds_per_game": 5.3, "assists_per_game": 1.9, "fg_pct": 0.470, "three_pt_pct": 0.300, "ft_pct": 0.700, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "physical forward, rebounder", "nba_draft_prospect": False},
    {"team_name": "Northern Iowa", "player_name": "Max Weisbrod", "position": "G", "year": "Sr", "points_per_game": 5.1, "rebounds_per_game": 1.9, "assists_per_game": 1.6, "fg_pct": 0.400, "three_pt_pct": 0.396, "ft_pct": 0.780, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "bench sharpshooter, 39.6% 3PT", "nba_draft_prospect": False},

    # === CAL BAPTIST (13-seed East) ===
    {"team_name": "Cal Baptist", "player_name": "Dominique Daniels Jr.", "position": "G", "year": "Gr", "points_per_game": 23.2, "rebounds_per_game": 3.8, "assists_per_game": 3.2, "fg_pct": 0.435, "three_pt_pct": 0.350, "ft_pct": 0.840, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "WAC POY, top-10 national scorer, 47-pt game", "nba_draft_prospect": False},
    {"team_name": "Cal Baptist", "player_name": "Martel Williams", "position": "G", "year": "Sr", "points_per_game": 14.1, "rebounds_per_game": 3.5, "assists_per_game": 2.0, "fg_pct": 0.440, "three_pt_pct": 0.360, "ft_pct": 0.760, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "second scorer, reliable guard", "nba_draft_prospect": False},
    {"team_name": "Cal Baptist", "player_name": "Jayden Jackson", "position": "G", "year": "Jr", "points_per_game": 7.5, "rebounds_per_game": 2.3, "assists_per_game": 2.2, "fg_pct": 0.420, "three_pt_pct": 0.340, "ft_pct": 0.740, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile 6-4 guard", "nba_draft_prospect": False},
    {"team_name": "Cal Baptist", "player_name": "Thomas Ndong", "position": "F", "year": "Jr", "points_per_game": 6.8, "rebounds_per_game": 7.1, "assists_per_game": 0.8, "fg_pct": 0.520, "three_pt_pct": 0.250, "ft_pct": 0.620, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "6-10 OSU transfer, primary rebounder", "nba_draft_prospect": False},
    {"team_name": "Cal Baptist", "player_name": "Jordan Muller", "position": "G", "year": "Fr", "points_per_game": 5.8, "rebounds_per_game": 2.0, "assists_per_game": 2.4, "fg_pct": 0.410, "three_pt_pct": 0.330, "ft_pct": 0.720, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "freshman, WAC All-Freshman Team", "nba_draft_prospect": False},

    # === USF (11-seed East) ===
    {"team_name": "USF", "player_name": "Wes Enis", "position": "G", "year": "Jr", "points_per_game": 16.5, "rebounds_per_game": 3.4, "assists_per_game": 2.8, "fg_pct": 0.450, "three_pt_pct": 0.370, "ft_pct": 0.820, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, AAC Tourney MOP, 100+ 3s", "nba_draft_prospect": False},
    {"team_name": "USF", "player_name": "Izaiyah Nelson", "position": "F", "year": "Sr", "points_per_game": 15.8, "rebounds_per_game": 9.8, "assists_per_game": 1.5, "fg_pct": 0.590, "three_pt_pct": 0.280, "ft_pct": 0.680, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "AAC POY, near double-double avg, 18 DD", "nba_draft_prospect": False},
    {"team_name": "USF", "player_name": "Joseph Pinion", "position": "G", "year": "Sr", "points_per_game": 14.2, "rebounds_per_game": 3.5, "assists_per_game": 1.8, "fg_pct": 0.430, "three_pt_pct": 0.391, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "elite 3PT (39.1%), career-high season", "nba_draft_prospect": False},
    {"team_name": "USF", "player_name": "Josh Omojafo", "position": "G", "year": "Sr", "points_per_game": 11.7, "rebounds_per_game": 5.2, "assists_per_game": 2.3, "fg_pct": 0.440, "three_pt_pct": 0.340, "ft_pct": 0.760, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile 6-5 guard, strong rebounder", "nba_draft_prospect": False},
    {"team_name": "USF", "player_name": "CJ Brown", "position": "G", "year": "So", "points_per_game": 11.4, "rebounds_per_game": 3.8, "assists_per_game": 3.5, "fg_pct": 0.430, "three_pt_pct": 0.350, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "sophomore guard, playmaker", "nba_draft_prospect": False},

    # === NORTH DAKOTA STATE (14-seed East) ===
    {"team_name": "North Dakota State", "player_name": "Damari Wheeler-Thomas", "position": "G", "year": "Jr", "points_per_game": 14.4, "rebounds_per_game": 3.5, "assists_per_game": 2.8, "fg_pct": 0.404, "three_pt_pct": 0.330, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "All-Summit League, 1000+ career pts", "nba_draft_prospect": False},
    {"team_name": "North Dakota State", "player_name": "Trevian Carson", "position": "G", "year": "Jr", "points_per_game": 12.4, "rebounds_per_game": 5.0, "assists_per_game": 2.5, "fg_pct": 0.480, "three_pt_pct": 0.370, "ft_pct": 0.750, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "All-Summit First Team, JUCO transfer", "nba_draft_prospect": False},
    {"team_name": "North Dakota State", "player_name": "Treyson Anderson", "position": "F", "year": "So", "points_per_game": 10.6, "rebounds_per_game": 5.8, "assists_per_game": 1.2, "fg_pct": 0.460, "three_pt_pct": 0.320, "ft_pct": 0.700, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "6-9 interior scorer and rebounder", "nba_draft_prospect": False},
    {"team_name": "North Dakota State", "player_name": "Andy Stefonowicz", "position": "G", "year": "So", "points_per_game": 9.2, "rebounds_per_game": 3.8, "assists_per_game": 4.7, "fg_pct": 0.430, "three_pt_pct": 0.350, "ft_pct": 0.770, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "PG, primary facilitator, 11-assist game", "nba_draft_prospect": False},
    {"team_name": "North Dakota State", "player_name": "Noah Feddersen", "position": "F", "year": "So", "points_per_game": 8.5, "rebounds_per_game": 4.8, "assists_per_game": 1.0, "fg_pct": 0.500, "three_pt_pct": 0.300, "ft_pct": 0.720, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "Summit League 6MOY, 6-10 shot blocker", "nba_draft_prospect": False},

    # === UCF (10-seed East) ===
    {"team_name": "UCF", "player_name": "Riley Kugel", "position": "G", "year": "Sr", "points_per_game": 14.4, "rebounds_per_game": 3.1, "assists_per_game": 2.5, "fg_pct": 0.440, "three_pt_pct": 0.370, "ft_pct": 0.820, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "senior guard, Miss St transfer", "nba_draft_prospect": False},
    {"team_name": "UCF", "player_name": "Themus Fulks", "position": "G", "year": "Sr", "points_per_game": 14.4, "rebounds_per_game": 3.3, "assists_per_game": 6.8, "fg_pct": 0.430, "three_pt_pct": 0.340, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "All-Big 12, UCF assists record, floor general", "nba_draft_prospect": False},
    {"team_name": "UCF", "player_name": "Jordan Burks", "position": "F", "year": "Jr", "points_per_game": 13.4, "rebounds_per_game": 4.4, "assists_per_game": 1.5, "fg_pct": 0.460, "three_pt_pct": 0.340, "ft_pct": 0.760, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "6-9 Georgetown transfer, versatile", "nba_draft_prospect": False},
    {"team_name": "UCF", "player_name": "Jamichael Stillwell", "position": "F", "year": "Sr", "points_per_game": 12.4, "rebounds_per_game": 9.1, "assists_per_game": 1.2, "fg_pct": 0.500, "three_pt_pct": 0.280, "ft_pct": 0.680, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "dominant rebounder (9.1 RPG), interior anchor", "nba_draft_prospect": False},
    {"team_name": "UCF", "player_name": "George Beale Jr.", "position": "G", "year": "Sr", "points_per_game": 7.2, "rebounds_per_game": 2.5, "assists_per_game": 1.8, "fg_pct": 0.420, "three_pt_pct": 0.350, "ft_pct": 0.780, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "sixth man, perimeter shooter", "nba_draft_prospect": False},

    # === FURMAN (15-seed East) ===
    {"team_name": "Furman", "player_name": "Alex Wilkins", "position": "G", "year": "Fr", "points_per_game": 17.7, "rebounds_per_game": 3.4, "assists_per_game": 4.9, "fg_pct": 0.440, "three_pt_pct": 0.350, "ft_pct": 0.820, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "star freshman PG, 34-pt game", "nba_draft_prospect": True},
    {"team_name": "Furman", "player_name": "Cooper Bowser", "position": "F", "year": "Jr", "points_per_game": 13.4, "rebounds_per_game": 6.3, "assists_per_game": 1.0, "fg_pct": 0.500, "three_pt_pct": 0.320, "ft_pct": 0.720, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "6-11 forward, team block leader", "nba_draft_prospect": False},
    {"team_name": "Furman", "player_name": "Asa Thomas", "position": "G", "year": "So", "points_per_game": 13.1, "rebounds_per_game": 3.5, "assists_per_game": 2.8, "fg_pct": 0.430, "three_pt_pct": 0.360, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "6-7 Clemson transfer, versatile wing", "nba_draft_prospect": False},
    {"team_name": "Furman", "player_name": "Charles Johnston", "position": "F", "year": "Sr", "points_per_game": 10.1, "rebounds_per_game": 9.2, "assists_per_game": 0.8, "fg_pct": 0.540, "three_pt_pct": 0.250, "ft_pct": 0.650, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "6-11 Australian center, leading rebounder", "nba_draft_prospect": False},
    {"team_name": "Furman", "player_name": "Gunnar Lewis", "position": "G", "year": "Sr", "points_per_game": 8.5, "rebounds_per_game": 3.0, "assists_per_game": 1.5, "fg_pct": 0.420, "three_pt_pct": 0.370, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "6-7 FSU transfer, floor spacer", "nba_draft_prospect": False},

    # === SIENA (16-seed East) ===
    {"team_name": "Siena", "player_name": "Gavin Doty", "position": "G", "year": "So", "points_per_game": 17.9, "rebounds_per_game": 7.0, "assists_per_game": 2.5, "fg_pct": 0.460, "three_pt_pct": 0.350, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer and rebounder, 31-pt game", "nba_draft_prospect": False},
    {"team_name": "Siena", "player_name": "Justice Shoats", "position": "G", "year": "Sr", "points_per_game": 13.2, "rebounds_per_game": 2.8, "assists_per_game": 4.4, "fg_pct": 0.440, "three_pt_pct": 0.340, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "senior PG, assist leader, 26 in MAAC semi", "nba_draft_prospect": False},
    {"team_name": "Siena", "player_name": "Brendan Coyle", "position": "F", "year": "Sr", "points_per_game": 12.8, "rebounds_per_game": 4.0, "assists_per_game": 1.2, "fg_pct": 0.450, "three_pt_pct": 0.380, "ft_pct": 0.760, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "stretch four, 22 double-figure games", "nba_draft_prospect": False},
    {"team_name": "Siena", "player_name": "Tasman Goodrick", "position": "F", "year": "Jr", "points_per_game": 9.7, "rebounds_per_game": 7.3, "assists_per_game": 1.3, "fg_pct": 0.500, "three_pt_pct": 0.300, "ft_pct": 0.680, "is_starter": False, "is_injured": True, "injury_details": "Season-ending knee injury since December 2025", "role_description": "6-10 forward, was key rebounder before injury", "nba_draft_prospect": False},
    {"team_name": "Siena", "player_name": "Antonio Chandler", "position": "F", "year": "Gr", "points_per_game": 6.7, "rebounds_per_game": 5.7, "assists_per_game": 0.8, "fg_pct": 0.480, "three_pt_pct": 0.280, "ft_pct": 0.650, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "grad transfer, interior rebounder", "nba_draft_prospect": False},
]
