#!/usr/bin/env python3
"""Batch 2: East region (Louisville, Michigan State, UCLA, UConn)"""

players_batch2 = [
    # ===================== LOUISVILLE (6-seed East) =====================
    {"team_name": "Louisville", "player_name": "Ryan Conwell", "position": "G", "year": "Sr", "points_per_game": 18.7, "rebounds_per_game": 4.8, "assists_per_game": 2.5, "fg_pct": 0.407, "three_pt_pct": 0.342, "ft_pct": 0.853, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary scorer, elite shot-maker", "nba_draft_prospect": True},
    {"team_name": "Louisville", "player_name": "Mikel Brown Jr.", "position": "G", "year": "Fr", "points_per_game": 18.2, "rebounds_per_game": 3.3, "assists_per_game": 4.7, "fg_pct": 0.410, "three_pt_pct": 0.344, "ft_pct": 0.844, "is_starter": True, "is_injured": True, "injury_details": "Lower back injury; missed ACC Tournament; hoping to return for NCAAs", "role_description": "floor general, co-primary scorer, projected lottery pick", "nba_draft_prospect": True},
    {"team_name": "Louisville", "player_name": "J'Vonne Hadley", "position": "G", "year": "Sr", "points_per_game": 11.8, "rebounds_per_game": 5.2, "assists_per_game": 1.7, "fg_pct": 0.573, "three_pt_pct": 0.456, "ft_pct": 0.702, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile two-way wing, highly efficient", "nba_draft_prospect": False},
    {"team_name": "Louisville", "player_name": "Isaac McKneely", "position": "G", "year": "Sr", "points_per_game": 10.6, "rebounds_per_game": 3.0, "assists_per_game": 1.4, "fg_pct": 0.407, "three_pt_pct": 0.381, "ft_pct": 0.860, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "3PT specialist, floor spacer", "nba_draft_prospect": False},
    {"team_name": "Louisville", "player_name": "Sananda Fru", "position": "F", "year": "Jr", "points_per_game": 9.2, "rebounds_per_game": 6.0, "assists_per_game": 1.3, "fg_pct": 0.759, "three_pt_pct": 0.500, "ft_pct": 0.631, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "interior finisher, ultra-efficient rebounder", "nba_draft_prospect": False},

    # ===================== MICHIGAN STATE (3-seed East) =====================
    {"team_name": "Michigan State", "player_name": "Jeremy Fears Jr.", "position": "G", "year": "Jr", "points_per_game": 15.7, "rebounds_per_game": 2.4, "assists_per_game": 9.2, "fg_pct": 0.445, "three_pt_pct": 0.320, "ft_pct": 0.893, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "floor general, elite playmaker (9.2 APG)", "nba_draft_prospect": True},
    {"team_name": "Michigan State", "player_name": "Jaxon Kohler", "position": "F", "year": "Sr", "points_per_game": 12.7, "rebounds_per_game": 9.0, "assists_per_game": 1.3, "fg_pct": 0.510, "three_pt_pct": 0.394, "ft_pct": 0.870, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "secondary scorer, lead rebounder, skilled post", "nba_draft_prospect": False},
    {"team_name": "Michigan State", "player_name": "Coen Carr", "position": "F", "year": "Jr", "points_per_game": 11.6, "rebounds_per_game": 5.4, "assists_per_game": 1.3, "fg_pct": 0.506, "three_pt_pct": 0.269, "ft_pct": 0.620, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "athletic slasher, rim protector, elite dunker", "nba_draft_prospect": True},
    {"team_name": "Michigan State", "player_name": "Carson Cooper", "position": "C", "year": "Sr", "points_per_game": 10.8, "rebounds_per_game": 7.1, "assists_per_game": 1.4, "fg_pct": 0.572, "three_pt_pct": 0.250, "ft_pct": 0.778, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "rim protector, interior anchor", "nba_draft_prospect": False},
    {"team_name": "Michigan State", "player_name": "Kur Teng", "position": "G", "year": "So", "points_per_game": 7.7, "rebounds_per_game": 2.1, "assists_per_game": 1.0, "fg_pct": 0.386, "three_pt_pct": 0.381, "ft_pct": 0.842, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "sixth man, 3PT specialist off bench", "nba_draft_prospect": False},

    # ===================== UCLA (7-seed East) =====================
    {"team_name": "UCLA", "player_name": "Tyler Bilodeau", "position": "F", "year": "Sr", "points_per_game": 17.6, "rebounds_per_game": 5.6, "assists_per_game": 1.1, "fg_pct": 0.518, "three_pt_pct": 0.464, "ft_pct": 0.873, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary scorer, stretch-four, elite efficiency", "nba_draft_prospect": True},
    {"team_name": "UCLA", "player_name": "Donovan Dent", "position": "G", "year": "Sr", "points_per_game": 13.5, "rebounds_per_game": 2.9, "assists_per_game": 7.6, "fg_pct": 0.420, "three_pt_pct": 0.262, "ft_pct": 0.636, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "floor general, elite playmaker (7.6 APG)", "nba_draft_prospect": True},
    {"team_name": "UCLA", "player_name": "Trent Perry", "position": "G", "year": "So", "points_per_game": 12.7, "rebounds_per_game": 2.9, "assists_per_game": 2.9, "fg_pct": 0.446, "three_pt_pct": 0.412, "ft_pct": 0.874, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "secondary scorer, 3PT threat", "nba_draft_prospect": False},
    {"team_name": "UCLA", "player_name": "Skyy Clark", "position": "G", "year": "Sr", "points_per_game": 11.7, "rebounds_per_game": 2.3, "assists_per_game": 2.1, "fg_pct": 0.460, "three_pt_pct": 0.432, "ft_pct": 0.861, "is_starter": True, "is_injured": False, "injury_details": "Missed 10 games with hamstring; returned for Big Ten Tournament", "role_description": "3PT specialist, floor spacer", "nba_draft_prospect": False},
    {"team_name": "UCLA", "player_name": "Eric Dailey Jr.", "position": "F", "year": "Jr", "points_per_game": 11.3, "rebounds_per_game": 5.8, "assists_per_game": 1.3, "fg_pct": 0.490, "three_pt_pct": 0.311, "ft_pct": 0.705, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile two-way wing", "nba_draft_prospect": True},

    # ===================== UCONN (2-seed East) =====================
    {"team_name": "UConn", "player_name": "Tarris Reed Jr.", "position": "F", "year": "Sr", "points_per_game": 13.7, "rebounds_per_game": 8.1, "assists_per_game": 2.3, "fg_pct": 0.625, "three_pt_pct": 0.0, "ft_pct": 0.561, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "interior anchor, dominant finisher (.625 FG%)", "nba_draft_prospect": True},
    {"team_name": "UConn", "player_name": "Solomon Ball", "position": "G", "year": "Jr", "points_per_game": 13.5, "rebounds_per_game": 3.3, "assists_per_game": 1.6, "fg_pct": 0.401, "three_pt_pct": 0.306, "ft_pct": 0.849, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "secondary scorer, shooting guard", "nba_draft_prospect": True},
    {"team_name": "UConn", "player_name": "Alex Karaban", "position": "F", "year": "Sr", "points_per_game": 12.6, "rebounds_per_game": 5.2, "assists_per_game": 2.3, "fg_pct": 0.474, "three_pt_pct": 0.386, "ft_pct": 0.838, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "stretch-four, two-time national champion, high IQ", "nba_draft_prospect": True},
    {"team_name": "UConn", "player_name": "Braylon Mullins", "position": "G", "year": "Fr", "points_per_game": 12.0, "rebounds_per_game": 3.5, "assists_per_game": 1.4, "fg_pct": 0.435, "three_pt_pct": 0.345, "ft_pct": 0.852, "is_starter": True, "is_injured": False, "injury_details": "Missed 7 games earlier (ankle/head); currently healthy", "role_description": "freshman scorer, McDonald's All-American", "nba_draft_prospect": True},
    {"team_name": "UConn", "player_name": "Silas Demary Jr.", "position": "G", "year": "Jr", "points_per_game": 10.9, "rebounds_per_game": 4.5, "assists_per_game": 6.2, "fg_pct": 0.461, "three_pt_pct": 0.416, "ft_pct": 0.806, "is_starter": True, "is_injured": True, "injury_details": "Left ankle sprain in Big East final; out of boot, expected to play", "role_description": "floor general, defensive catalyst (6.2 APG)", "nba_draft_prospect": False},
]
