#!/usr/bin/env python3
"""Batch 5: Midwest (SMU, Virginia, Wright State, Kentucky, Santa Clara, Iowa State, Tennessee State, UMBC)"""

players_batch5 = [
    # === SMU (11-seed Midwest) ===
    {"team_name": "SMU", "player_name": "Kevin Miller", "position": "G", "year": "Sr", "points_per_game": 19.2, "rebounds_per_game": 3.9, "assists_per_game": 6.4, "fg_pct": 0.470, "three_pt_pct": 0.410, "ft_pct": 0.871, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary scorer, All-ACC Second Team", "nba_draft_prospect": False},
    {"team_name": "SMU", "player_name": "Jaron Pierre Jr.", "position": "G", "year": "Sr", "points_per_game": 17.6, "rebounds_per_game": 4.9, "assists_per_game": 2.0, "fg_pct": 0.460, "three_pt_pct": 0.378, "ft_pct": 0.755, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "second scorer, 6-6 wing", "nba_draft_prospect": True},
    {"team_name": "SMU", "player_name": "B.J. Edwards", "position": "G", "year": "Sr", "points_per_game": 12.7, "rebounds_per_game": 5.9, "assists_per_game": 4.9, "fg_pct": 0.474, "three_pt_pct": 0.372, "ft_pct": 0.771, "is_starter": True, "is_injured": True, "injury_details": "Ankle injury; missed last 5 games; questionable for NCAAs", "role_description": "two-way guard, All-ACC caliber", "nba_draft_prospect": True},
    {"team_name": "SMU", "player_name": "Corey Washington", "position": "F", "year": "Sr", "points_per_game": 11.3, "rebounds_per_game": 4.9, "assists_per_game": 0.8, "fg_pct": 0.484, "three_pt_pct": 0.398, "ft_pct": 0.768, "is_starter": True, "is_injured": True, "injury_details": "Shoulder injury in ACC Tournament; status uncertain", "role_description": "starting forward, floor-spacer", "nba_draft_prospect": False},
    {"team_name": "SMU", "player_name": "Samet Yigitoglu", "position": "C", "year": "So", "points_per_game": 10.8, "rebounds_per_game": 7.9, "assists_per_game": 1.6, "fg_pct": 0.624, "three_pt_pct": 0.0, "ft_pct": 0.495, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "7-2 center, dominant rebounder, rim finisher", "nba_draft_prospect": False},

    # === VIRGINIA (3-seed Midwest) ===
    {"team_name": "Virginia", "player_name": "Thijs De Ridder", "position": "F", "year": "Fr", "points_per_game": 15.5, "rebounds_per_game": 6.2, "assists_per_game": 1.6, "fg_pct": 0.508, "three_pt_pct": 0.340, "ft_pct": 0.713, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, 6-9 Belgian freshman", "nba_draft_prospect": True},
    {"team_name": "Virginia", "player_name": "Malik Thomas", "position": "G", "year": "Sr", "points_per_game": 12.4, "rebounds_per_game": 3.9, "assists_per_game": 1.6, "fg_pct": 0.412, "three_pt_pct": 0.343, "ft_pct": 0.750, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "veteran guard, second scorer", "nba_draft_prospect": False},
    {"team_name": "Virginia", "player_name": "Sam Lewis", "position": "G", "year": "Jr", "points_per_game": 10.8, "rebounds_per_game": 3.6, "assists_per_game": 1.4, "fg_pct": 0.462, "three_pt_pct": 0.407, "ft_pct": 0.742, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "elite 3PT shooter (40.7%)", "nba_draft_prospect": False},
    {"team_name": "Virginia", "player_name": "Chance Mallory", "position": "G", "year": "Fr", "points_per_game": 9.5, "rebounds_per_game": 3.7, "assists_per_game": 3.6, "fg_pct": 0.421, "three_pt_pct": 0.349, "ft_pct": 0.786, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "freshman guard, primary facilitator", "nba_draft_prospect": False},
    {"team_name": "Virginia", "player_name": "Jacari White", "position": "G", "year": "Sr", "points_per_game": 8.8, "rebounds_per_game": 2.3, "assists_per_game": 1.2, "fg_pct": 0.452, "three_pt_pct": 0.430, "ft_pct": 0.821, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "sixth man, elite 3PT (43.0%)", "nba_draft_prospect": False},

    # === WRIGHT STATE (14-seed Midwest) ===
    {"team_name": "Wright State", "player_name": "Michael Cooper", "position": "G", "year": "Fr", "points_per_game": 13.4, "rebounds_per_game": 2.8, "assists_per_game": 2.2, "fg_pct": 0.449, "three_pt_pct": 0.364, "ft_pct": 0.805, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "freshman PG, leading scorer, breakout star", "nba_draft_prospect": False},
    {"team_name": "Wright State", "player_name": "TJ Burch", "position": "G", "year": "So", "points_per_game": 12.3, "rebounds_per_game": 2.4, "assists_per_game": 3.5, "fg_pct": 0.460, "three_pt_pct": 0.343, "ft_pct": 0.730, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "HL Tourney MVP, DPOY, Newcomer of Year", "nba_draft_prospect": False},
    {"team_name": "Wright State", "player_name": "Michael Imariagbe", "position": "F", "year": "Sr", "points_per_game": 11.8, "rebounds_per_game": 7.0, "assists_per_game": 1.8, "fg_pct": 0.589, "three_pt_pct": 0.167, "ft_pct": 0.683, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading rebounder, efficient interior scorer", "nba_draft_prospect": False},
    {"team_name": "Wright State", "player_name": "Solomon Callaghan", "position": "G", "year": "So", "points_per_game": 9.9, "rebounds_per_game": 1.9, "assists_per_game": 1.1, "fg_pct": 0.410, "three_pt_pct": 0.386, "ft_pct": 0.922, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "elite FT shooter (92.2%), 3PT threat", "nba_draft_prospect": False},
    {"team_name": "Wright State", "player_name": "Dominic Pangonis", "position": "G", "year": "So", "points_per_game": 9.0, "rebounds_per_game": 2.6, "assists_per_game": 1.2, "fg_pct": 0.475, "three_pt_pct": 0.383, "ft_pct": 0.729, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "key reserve, efficient shooter", "nba_draft_prospect": False},

    # === KENTUCKY (7-seed Midwest) ===
    {"team_name": "Kentucky", "player_name": "Otega Oweh", "position": "G", "year": "Sr", "points_per_game": 18.2, "rebounds_per_game": 4.6, "assists_per_game": 2.6, "fg_pct": 0.463, "three_pt_pct": 0.336, "ft_pct": 0.728, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, All-SEC Second Team", "nba_draft_prospect": True},
    {"team_name": "Kentucky", "player_name": "Denzel Aberdeen", "position": "G", "year": "Sr", "points_per_game": 13.2, "rebounds_per_game": 2.6, "assists_per_game": 3.6, "fg_pct": 0.430, "three_pt_pct": 0.351, "ft_pct": 0.798, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "team assist leader, backcourt partner", "nba_draft_prospect": False},
    {"team_name": "Kentucky", "player_name": "Collin Chandler", "position": "G", "year": "So", "points_per_game": 9.9, "rebounds_per_game": 2.8, "assists_per_game": 2.2, "fg_pct": 0.445, "three_pt_pct": 0.427, "ft_pct": 0.833, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "elite 3PT shooter (42.7%)", "nba_draft_prospect": False},
    {"team_name": "Kentucky", "player_name": "Mouhamed Dioubate", "position": "F", "year": "Jr", "points_per_game": 8.7, "rebounds_per_game": 5.5, "assists_per_game": 1.0, "fg_pct": 0.530, "three_pt_pct": 0.192, "ft_pct": 0.639, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "physical interior, second rebounder", "nba_draft_prospect": False},
    {"team_name": "Kentucky", "player_name": "Malachi Moreno", "position": "C", "year": "Fr", "points_per_game": 8.0, "rebounds_per_game": 6.4, "assists_per_game": 1.8, "fg_pct": 0.583, "three_pt_pct": 0.0, "ft_pct": 0.703, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading rebounder, All-SEC Freshman, 1.6 BPG", "nba_draft_prospect": True},

    # === SANTA CLARA (10-seed Midwest) ===
    {"team_name": "Santa Clara", "player_name": "Christian Hammond", "position": "G", "year": "So", "points_per_game": 15.8, "rebounds_per_game": 2.9, "assists_per_game": 2.4, "fg_pct": 0.490, "three_pt_pct": 0.400, "ft_pct": 0.790, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, All-WCC First Team", "nba_draft_prospect": False},
    {"team_name": "Santa Clara", "player_name": "Elijah Mahi", "position": "F", "year": "Sr", "points_per_game": 13.9, "rebounds_per_game": 4.7, "assists_per_game": 2.6, "fg_pct": 0.448, "three_pt_pct": 0.336, "ft_pct": 0.707, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "veteran forward, All-WCC First Team", "nba_draft_prospect": False},
    {"team_name": "Santa Clara", "player_name": "Allen Graves", "position": "F", "year": "Fr", "points_per_game": 11.6, "rebounds_per_game": 6.5, "assists_per_game": 1.8, "fg_pct": 0.517, "three_pt_pct": 0.416, "ft_pct": 0.736, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "WCC FOY & 6MOY, drawing NBA attention", "nba_draft_prospect": True},
    {"team_name": "Santa Clara", "player_name": "Aleksandar Gavalyugov", "position": "G", "year": "Fr", "points_per_game": 8.8, "rebounds_per_game": 1.7, "assists_per_game": 2.6, "fg_pct": 0.401, "three_pt_pct": 0.358, "ft_pct": 0.720, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "key reserve, playmaking guard", "nba_draft_prospect": False},
    {"team_name": "Santa Clara", "player_name": "Bukky Oboye", "position": "C", "year": "So", "points_per_game": 8.0, "rebounds_per_game": 4.2, "assists_per_game": 0.6, "fg_pct": 0.665, "three_pt_pct": 0.250, "ft_pct": 0.656, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting center, hyper-efficient (66.5% FG)", "nba_draft_prospect": False},

    # === IOWA STATE (2-seed Midwest) ===
    {"team_name": "Iowa State", "player_name": "Milan Momcilovic", "position": "F", "year": "Jr", "points_per_game": 17.1, "rebounds_per_game": 3.1, "assists_per_game": 0.9, "fg_pct": 0.512, "three_pt_pct": 0.496, "ft_pct": 0.880, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, elite 3PT sniper (49.6%)", "nba_draft_prospect": True},
    {"team_name": "Iowa State", "player_name": "Joshua Jefferson", "position": "F", "year": "Sr", "points_per_game": 16.9, "rebounds_per_game": 7.6, "assists_per_game": 4.9, "fg_pct": 0.470, "three_pt_pct": 0.345, "ft_pct": 0.700, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "do-it-all wing, projected 1st round pick", "nba_draft_prospect": True},
    {"team_name": "Iowa State", "player_name": "Tamin Lipsey", "position": "G", "year": "Sr", "points_per_game": 13.3, "rebounds_per_game": 4.0, "assists_per_game": 5.0, "fg_pct": 0.461, "three_pt_pct": 0.311, "ft_pct": 0.644, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "PG, team assist leader (5.0 APG)", "nba_draft_prospect": False},
    {"team_name": "Iowa State", "player_name": "Blake Buchanan", "position": "F", "year": "Jr", "points_per_game": 8.4, "rebounds_per_game": 5.7, "assists_per_game": 1.5, "fg_pct": 0.645, "three_pt_pct": 0.0, "ft_pct": 0.478, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "elite finisher (64.5% FG), rebounder", "nba_draft_prospect": False},
    {"team_name": "Iowa State", "player_name": "Killyan Toure", "position": "G", "year": "Fr", "points_per_game": 8.1, "rebounds_per_game": 3.2, "assists_per_game": 2.2, "fg_pct": 0.448, "three_pt_pct": 0.303, "ft_pct": 0.703, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting freshman guard", "nba_draft_prospect": False},

    # === TENNESSEE STATE (15-seed Midwest) ===
    {"team_name": "Tennessee State", "player_name": "Aaron Nkrumah", "position": "G", "year": "Sr", "points_per_game": 17.6, "rebounds_per_game": 5.5, "assists_per_game": 3.0, "fg_pct": 0.437, "three_pt_pct": 0.352, "ft_pct": 0.789, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "OVC POY, national leader in steals", "nba_draft_prospect": False},
    {"team_name": "Tennessee State", "player_name": "Travis Harper II", "position": "G", "year": "Sr", "points_per_game": 17.3, "rebounds_per_game": 4.3, "assists_per_game": 1.2, "fg_pct": 0.476, "three_pt_pct": 0.401, "ft_pct": 0.858, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "All-OVC, elite 3PT (40.1%)", "nba_draft_prospect": False},
    {"team_name": "Tennessee State", "player_name": "Dante Harris", "position": "G", "year": "Sr", "points_per_game": 11.7, "rebounds_per_game": 3.7, "assists_per_game": 4.5, "fg_pct": 0.420, "three_pt_pct": 0.313, "ft_pct": 0.730, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "OVC Tourney MVP, primary playmaker", "nba_draft_prospect": False},
    {"team_name": "Tennessee State", "player_name": "Antoine Lorick III", "position": "F", "year": "Jr", "points_per_game": 9.5, "rebounds_per_game": 5.0, "assists_per_game": 1.0, "fg_pct": 0.520, "three_pt_pct": 0.229, "ft_pct": 0.657, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "efficient interior scorer", "nba_draft_prospect": False},
    {"team_name": "Tennessee State", "player_name": "Jalen Pitre", "position": "F", "year": "Sr", "points_per_game": 6.5, "rebounds_per_game": 6.6, "assists_per_game": 0.9, "fg_pct": 0.630, "three_pt_pct": 0.167, "ft_pct": 0.852, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading rebounder, ultra-efficient (63.0% FG)", "nba_draft_prospect": False},

    # === UMBC (16-seed Midwest) ===
    {"team_name": "UMBC", "player_name": "Jah'Likai King", "position": "G", "year": "Jr", "points_per_game": 13.9, "rebounds_per_game": 3.4, "assists_per_game": 1.5, "fg_pct": 0.415, "three_pt_pct": 0.319, "ft_pct": 0.828, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, America East First Team", "nba_draft_prospect": False},
    {"team_name": "UMBC", "player_name": "DJ Armstrong Jr.", "position": "F", "year": "Sr", "points_per_game": 13.2, "rebounds_per_game": 2.8, "assists_per_game": 2.1, "fg_pct": 0.464, "three_pt_pct": 0.420, "ft_pct": 0.928, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "Tourney MOP (33 pts in title game), elite FT", "nba_draft_prospect": False},
    {"team_name": "UMBC", "player_name": "Ace Valentine", "position": "G", "year": "Jr", "points_per_game": 12.0, "rebounds_per_game": 4.1, "assists_per_game": 4.0, "fg_pct": 0.506, "three_pt_pct": 0.376, "ft_pct": 0.771, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile guard, best playmaker (4.0 APG)", "nba_draft_prospect": False},
    {"team_name": "UMBC", "player_name": "Caden Diggs", "position": "F", "year": "So", "points_per_game": 9.8, "rebounds_per_game": 3.6, "assists_per_game": 0.9, "fg_pct": 0.479, "three_pt_pct": 0.366, "ft_pct": 0.770, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "ODU transfer, well-rounded scorer", "nba_draft_prospect": False},
    {"team_name": "UMBC", "player_name": "Josh Odunowo", "position": "F", "year": "Gr", "points_per_game": 8.6, "rebounds_per_game": 5.2, "assists_per_game": 0.9, "fg_pct": 0.535, "three_pt_pct": 0.0, "ft_pct": 0.731, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading rebounder, veteran interior presence", "nba_draft_prospect": False},
]
