#!/usr/bin/env python3
"""Batch 1: East region top seeds (Duke, Ohio State, St. John's, Kansas)"""

players_batch1 = [
    # ===================== DUKE (1-seed East) =====================
    {"team_name": "Duke", "player_name": "Cameron Boozer", "position": "F", "year": "Fr", "points_per_game": 22.5, "rebounds_per_game": 10.2, "assists_per_game": 4.2, "fg_pct": 0.565, "three_pt_pct": 0.409, "ft_pct": 0.775, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary scorer, double-double machine", "nba_draft_prospect": True},
    {"team_name": "Duke", "player_name": "Isaiah Evans", "position": "G", "year": "So", "points_per_game": 14.9, "rebounds_per_game": 3.1, "assists_per_game": 1.4, "fg_pct": 0.425, "three_pt_pct": 0.365, "ft_pct": 0.874, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "secondary scorer, 3PT specialist wing", "nba_draft_prospect": True},
    {"team_name": "Duke", "player_name": "Patrick Ngongba II", "position": "C", "year": "So", "points_per_game": 10.7, "rebounds_per_game": 6.0, "assists_per_game": 1.9, "fg_pct": 0.602, "three_pt_pct": 0.276, "ft_pct": 0.694, "is_starter": True, "is_injured": True, "injury_details": "Right foot soreness; missed ACC Tournament, expected back for NCAAs", "role_description": "rim protector, defensive anchor", "nba_draft_prospect": False},
    {"team_name": "Duke", "player_name": "Caleb Foster", "position": "G", "year": "Jr", "points_per_game": 8.5, "rebounds_per_game": 3.6, "assists_per_game": 2.8, "fg_pct": 0.442, "three_pt_pct": 0.402, "ft_pct": 0.585, "is_starter": True, "is_injured": True, "injury_details": "Fractured right foot, had surgery, likely OUT", "role_description": "floor general, starting point guard", "nba_draft_prospect": False},
    {"team_name": "Duke", "player_name": "Cayden Boozer", "position": "G", "year": "Fr", "points_per_game": 7.1, "rebounds_per_game": 2.1, "assists_per_game": 2.8, "fg_pct": 0.489, "three_pt_pct": 0.288, "ft_pct": 0.800, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "playmaker, stepped into starting PG after Foster injury", "nba_draft_prospect": True},

    # ===================== OHIO STATE (8-seed East) =====================
    {"team_name": "Ohio State", "player_name": "Bruce Thornton", "position": "G", "year": "Sr", "points_per_game": 20.2, "rebounds_per_game": 5.1, "assists_per_game": 3.9, "fg_pct": 0.558, "three_pt_pct": 0.400, "ft_pct": 0.827, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary scorer, floor general, team leader", "nba_draft_prospect": True},
    {"team_name": "Ohio State", "player_name": "John Mobley Jr.", "position": "G", "year": "So", "points_per_game": 15.7, "rebounds_per_game": 2.4, "assists_per_game": 2.7, "fg_pct": 0.436, "three_pt_pct": 0.418, "ft_pct": 0.868, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "secondary scorer, elite 3PT specialist", "nba_draft_prospect": True},
    {"team_name": "Ohio State", "player_name": "Devin Royal", "position": "F", "year": "Jr", "points_per_game": 13.7, "rebounds_per_game": 5.7, "assists_per_game": 1.7, "fg_pct": 0.476, "three_pt_pct": 0.320, "ft_pct": 0.795, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile forward, inside-outside threat", "nba_draft_prospect": True},
    {"team_name": "Ohio State", "player_name": "Christoph Tilly", "position": "C", "year": "Sr", "points_per_game": 11.0, "rebounds_per_game": 4.7, "assists_per_game": 2.2, "fg_pct": 0.480, "three_pt_pct": 0.236, "ft_pct": 0.727, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "interior scorer, rim protector", "nba_draft_prospect": False},
    {"team_name": "Ohio State", "player_name": "Amare Bynum", "position": "F", "year": "Fr", "points_per_game": 9.7, "rebounds_per_game": 4.8, "assists_per_game": 1.1, "fg_pct": 0.502, "three_pt_pct": 0.318, "ft_pct": 0.729, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "sixth man, energy forward", "nba_draft_prospect": False},

    # ===================== ST. JOHN'S (5-seed East) =====================
    {"team_name": "St. John's", "player_name": "Zuby Ejiofor", "position": "F/C", "year": "Sr", "points_per_game": 16.3, "rebounds_per_game": 7.1, "assists_per_game": 3.5, "fg_pct": 0.554, "three_pt_pct": 0.319, "ft_pct": 0.714, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary scorer, Big East POY, defensive anchor", "nba_draft_prospect": True},
    {"team_name": "St. John's", "player_name": "Bryce Hopkins", "position": "F", "year": "Sr", "points_per_game": 13.5, "rebounds_per_game": 6.2, "assists_per_game": 2.0, "fg_pct": 0.459, "three_pt_pct": 0.299, "ft_pct": 0.723, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "secondary scorer, versatile forward", "nba_draft_prospect": False},
    {"team_name": "St. John's", "player_name": "Oziyah Sellers", "position": "G", "year": "Sr", "points_per_game": 10.7, "rebounds_per_game": 2.9, "assists_per_game": 1.7, "fg_pct": 0.439, "three_pt_pct": 0.350, "ft_pct": 0.859, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "3PT specialist, perimeter shooter", "nba_draft_prospect": False},
    {"team_name": "St. John's", "player_name": "Ian Jackson", "position": "G", "year": "So", "points_per_game": 9.6, "rebounds_per_game": 2.3, "assists_per_game": 1.2, "fg_pct": 0.413, "three_pt_pct": 0.354, "ft_pct": 0.897, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "scoring guard, developing wing", "nba_draft_prospect": True},
    {"team_name": "St. John's", "player_name": "Joson Sanon", "position": "G", "year": "So", "points_per_game": 8.3, "rebounds_per_game": 2.6, "assists_per_game": 0.6, "fg_pct": 0.348, "three_pt_pct": 0.344, "ft_pct": 0.768, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "sixth man, spark-plug guard", "nba_draft_prospect": False},

    # ===================== KANSAS (4-seed East) =====================
    {"team_name": "Kansas", "player_name": "Darryn Peterson", "position": "G", "year": "Fr", "points_per_game": 19.8, "rebounds_per_game": 4.4, "assists_per_game": 1.7, "fg_pct": 0.442, "three_pt_pct": 0.384, "ft_pct": 0.825, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary scorer, one-and-done star", "nba_draft_prospect": True},
    {"team_name": "Kansas", "player_name": "Tre White", "position": "G/F", "year": "Sr", "points_per_game": 13.8, "rebounds_per_game": 6.7, "assists_per_game": 1.8, "fg_pct": 0.457, "three_pt_pct": 0.421, "ft_pct": 0.867, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "secondary scorer, floor spacer", "nba_draft_prospect": True},
    {"team_name": "Kansas", "player_name": "Flory Bidunga", "position": "F/C", "year": "So", "points_per_game": 13.5, "rebounds_per_game": 9.2, "assists_per_game": 1.5, "fg_pct": 0.645, "three_pt_pct": 0.0, "ft_pct": 0.660, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "rim protector, DPOY candidate, elite shot blocker", "nba_draft_prospect": True},
    {"team_name": "Kansas", "player_name": "Melvin Council Jr.", "position": "G", "year": "Sr", "points_per_game": 12.9, "rebounds_per_game": 4.8, "assists_per_game": 5.1, "fg_pct": 0.396, "three_pt_pct": 0.313, "ft_pct": 0.769, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "floor general, lead facilitator", "nba_draft_prospect": False},
    {"team_name": "Kansas", "player_name": "Bryson Tiller", "position": "F", "year": "Fr", "points_per_game": 8.2, "rebounds_per_game": 6.0, "assists_per_game": 1.0, "fg_pct": 0.459, "three_pt_pct": 0.275, "ft_pct": 0.687, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "versatile forward, rebounder", "nba_draft_prospect": True},
]
