#!/usr/bin/env python3
"""South region player data: VCU, Illinois, Penn, Saint Mary's, Texas A&M, Houston, Idaho, Lehigh"""

south_region_players = [
    # ===================== VCU (11-seed South) =====================
    {"team_name": "VCU", "player_name": "Terrence Hill Jr.", "position": "G", "year": "So", "points_per_game": 14.6, "rebounds_per_game": 2.8, "assists_per_game": 2.9, "fg_pct": 0.470, "three_pt_pct": 0.380, "ft_pct": 0.873, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "leading scorer, elite sixth man, All-A10 First Team", "nba_draft_prospect": False},
    {"team_name": "VCU", "player_name": "Lazar Djokovic", "position": "F", "year": "Jr", "points_per_game": 13.7, "rebounds_per_game": 5.6, "assists_per_game": 1.0, "fg_pct": 0.527, "three_pt_pct": 0.320, "ft_pct": 0.720, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "interior scorer, starting forward, All-A10 First Team", "nba_draft_prospect": False},
    {"team_name": "VCU", "player_name": "Jadrian Tracey", "position": "G", "year": "Sr", "points_per_game": 10.1, "rebounds_per_game": 2.9, "assists_per_game": 1.9, "fg_pct": 0.420, "three_pt_pct": 0.350, "ft_pct": 0.790, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting guard, perimeter scorer", "nba_draft_prospect": False},
    {"team_name": "VCU", "player_name": "Brandon Jennings", "position": "G", "year": "So", "points_per_game": 8.8, "rebounds_per_game": 3.1, "assists_per_game": 2.1, "fg_pct": 0.435, "three_pt_pct": 0.340, "ft_pct": 0.750, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting guard, playmaker, All-Defensive Team", "nba_draft_prospect": False},
    {"team_name": "VCU", "player_name": "Nyk Lewis", "position": "G", "year": "Fr", "points_per_game": 8.5, "rebounds_per_game": 4.2, "assists_per_game": 1.7, "fg_pct": 0.393, "three_pt_pct": 0.348, "ft_pct": 0.753, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting freshman guard, A-10 Rookie of the Year", "nba_draft_prospect": False},

    # ===================== ILLINOIS (3-seed South) =====================
    {"team_name": "Illinois", "player_name": "Keaton Wagler", "position": "G", "year": "Fr", "points_per_game": 17.9, "rebounds_per_game": 4.9, "assists_per_game": 4.3, "fg_pct": 0.447, "three_pt_pct": 0.410, "ft_pct": 0.807, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary scorer, unanimous Big Ten Freshman of the Year, All-Big Ten First Team", "nba_draft_prospect": True},
    {"team_name": "Illinois", "player_name": "Kylan Boswell", "position": "G", "year": "Sr", "points_per_game": 13.3, "rebounds_per_game": 4.0, "assists_per_game": 3.4, "fg_pct": 0.440, "three_pt_pct": 0.370, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting combo guard, secondary scorer, All-Big Ten Honorable Mention", "nba_draft_prospect": False},
    {"team_name": "Illinois", "player_name": "David Mirkovic", "position": "F", "year": "Fr", "points_per_game": 13.2, "rebounds_per_game": 7.8, "assists_per_game": 2.5, "fg_pct": 0.481, "three_pt_pct": 0.376, "ft_pct": 0.760, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting forward, double-double threat, All-Big Ten Honorable Mention", "nba_draft_prospect": True},
    {"team_name": "Illinois", "player_name": "Tomislav Ivisic", "position": "C", "year": "Sr", "points_per_game": 10.0, "rebounds_per_game": 5.6, "assists_per_game": 1.2, "fg_pct": 0.490, "three_pt_pct": 0.330, "ft_pct": 0.710, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting center, rim protector, interior presence", "nba_draft_prospect": False},
    {"team_name": "Illinois", "player_name": "Ben Humrichous", "position": "F", "year": "Gr", "points_per_game": 6.3, "rebounds_per_game": 4.1, "assists_per_game": 0.8, "fg_pct": 0.450, "three_pt_pct": 0.350, "ft_pct": 0.700, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting stretch four, veteran leadership", "nba_draft_prospect": False},

    # ===================== PENN (14-seed South) =====================
    {"team_name": "Penn", "player_name": "Ethan Roberts", "position": "F", "year": "Sr", "points_per_game": 18.0, "rebounds_per_game": 5.2, "assists_per_game": 1.8, "fg_pct": 0.460, "three_pt_pct": 0.370, "ft_pct": 0.820, "is_starter": True, "is_injured": True, "injury_details": "Concussion; out for Ivy League Tournament and likely NCAA Tournament", "role_description": "leading scorer, second-team All-Ivy", "nba_draft_prospect": False},
    {"team_name": "Penn", "player_name": "TJ Power", "position": "F", "year": "Jr", "points_per_game": 15.4, "rebounds_per_game": 6.8, "assists_per_game": 1.5, "fg_pct": 0.470, "three_pt_pct": 0.360, "ft_pct": 0.790, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "Ivy Tournament MVP, scored 44 in championship final, double-double threat", "nba_draft_prospect": False},
    {"team_name": "Penn", "player_name": "AJ Levine", "position": "G", "year": "So", "points_per_game": 12.1, "rebounds_per_game": 3.4, "assists_per_game": 3.8, "fg_pct": 0.430, "three_pt_pct": 0.350, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting guard, clutch performer, hit game-winner vs Harvard in tournament", "nba_draft_prospect": False},
    {"team_name": "Penn", "player_name": "Michael Zanoni", "position": "F", "year": "Sr", "points_per_game": 10.6, "rebounds_per_game": 4.1, "assists_per_game": 1.2, "fg_pct": 0.440, "three_pt_pct": 0.340, "ft_pct": 0.770, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting forward, Mercer transfer, offensive versatility", "nba_draft_prospect": False},
    {"team_name": "Penn", "player_name": "Dylan Williams", "position": "G", "year": "Sr", "points_per_game": 7.2, "rebounds_per_game": 2.5, "assists_per_game": 3.6, "fg_pct": 0.400, "three_pt_pct": 0.330, "ft_pct": 0.750, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting point guard, floor general, facilitator", "nba_draft_prospect": False},

    # ===================== SAINT MARY'S (7-seed South) =====================
    {"team_name": "Saint Mary's", "player_name": "Paulius Murauskas", "position": "F", "year": "Jr", "points_per_game": 18.6, "rebounds_per_game": 7.7, "assists_per_game": 2.2, "fg_pct": 0.491, "three_pt_pct": 0.360, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "primary scorer, WCC scoring leader, All-WCC First Team", "nba_draft_prospect": True},
    {"team_name": "Saint Mary's", "player_name": "Mikey Lewis", "position": "G", "year": "So", "points_per_game": 13.9, "rebounds_per_game": 2.8, "assists_per_game": 2.2, "fg_pct": 0.386, "three_pt_pct": 0.340, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting guard, perimeter scorer, hit 7 threes vs Gonzaga", "nba_draft_prospect": False},
    {"team_name": "Saint Mary's", "player_name": "Joshua Dent", "position": "G", "year": "So", "points_per_game": 13.3, "rebounds_per_game": 3.2, "assists_per_game": 5.6, "fg_pct": 0.420, "three_pt_pct": 0.350, "ft_pct": 0.790, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting point guard, lead facilitator, WCC minutes leader", "nba_draft_prospect": False},
    {"team_name": "Saint Mary's", "player_name": "Andrew McKeever", "position": "C", "year": "So", "points_per_game": 8.3, "rebounds_per_game": 9.1, "assists_per_game": 1.7, "fg_pct": 0.513, "three_pt_pct": 0.250, "ft_pct": 0.650, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting center, WCC leading rebounder, interior anchor", "nba_draft_prospect": False},
    {"team_name": "Saint Mary's", "player_name": "Dillan Shaw", "position": "G", "year": "Fr", "points_per_game": 7.5, "rebounds_per_game": 5.3, "assists_per_game": 0.9, "fg_pct": 0.430, "three_pt_pct": 0.310, "ft_pct": 0.720, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "key bench contributor, combo guard, energy off the bench", "nba_draft_prospect": False},

    # ===================== TEXAS A&M (10-seed South) =====================
    {"team_name": "Texas A&M", "player_name": "Rashaun Agee", "position": "F", "year": "Gr", "points_per_game": 14.7, "rebounds_per_game": 8.9, "assists_per_game": 2.1, "fg_pct": 0.520, "three_pt_pct": 0.290, "ft_pct": 0.710, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, double-double machine, Third-Team All-SEC, program record 12 double-doubles", "nba_draft_prospect": False},
    {"team_name": "Texas A&M", "player_name": "Jacari Lane", "position": "G", "year": "Sr", "points_per_game": 13.5, "rebounds_per_game": 3.2, "assists_per_game": 5.0, "fg_pct": 0.423, "three_pt_pct": 0.406, "ft_pct": 0.810, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting point guard, floor general, facilitator", "nba_draft_prospect": False},
    {"team_name": "Texas A&M", "player_name": "Rylan Griffen", "position": "G", "year": "Sr", "points_per_game": 12.8, "rebounds_per_game": 3.0, "assists_per_game": 1.6, "fg_pct": 0.440, "three_pt_pct": 0.419, "ft_pct": 0.830, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting shooting guard, elite three-point shooter, Kansas transfer", "nba_draft_prospect": False},
    {"team_name": "Texas A&M", "player_name": "Ruben Dominguez", "position": "G", "year": "So", "points_per_game": 11.2, "rebounds_per_game": 2.5, "assists_per_game": 1.8, "fg_pct": 0.430, "three_pt_pct": 0.471, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting guard, sharpshooting sophomore, elite 3PT shooter", "nba_draft_prospect": False},
    {"team_name": "Texas A&M", "player_name": "Zach Clemence", "position": "F", "year": "Gr", "points_per_game": 10.5, "rebounds_per_game": 4.2, "assists_per_game": 1.0, "fg_pct": 0.460, "three_pt_pct": 0.370, "ft_pct": 0.760, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting forward, stretch big, rim protector", "nba_draft_prospect": False},

    # ===================== HOUSTON (2-seed South) =====================
    {"team_name": "Houston", "player_name": "Emanuel Sharp", "position": "G", "year": "Sr", "points_per_game": 15.8, "rebounds_per_game": 3.2, "assists_per_game": 1.8, "fg_pct": 0.445, "three_pt_pct": 0.390, "ft_pct": 0.850, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, All-Big 12 First Team, veteran starter", "nba_draft_prospect": True},
    {"team_name": "Houston", "player_name": "Kingston Flemings", "position": "G", "year": "Fr", "points_per_game": 16.5, "rebounds_per_game": 3.3, "assists_per_game": 5.4, "fg_pct": 0.483, "three_pt_pct": 0.376, "ft_pct": 0.810, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting point guard, All-Big 12 First Team, All-America Second Team", "nba_draft_prospect": True},
    {"team_name": "Houston", "player_name": "Milos Uzan", "position": "G", "year": "Sr", "points_per_game": 11.6, "rebounds_per_game": 3.3, "assists_per_game": 4.6, "fg_pct": 0.420, "three_pt_pct": 0.350, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting guard, veteran playmaker, Big 12 Championship standout", "nba_draft_prospect": False},
    {"team_name": "Houston", "player_name": "Chris Cenac Jr.", "position": "F/C", "year": "Fr", "points_per_game": 8.9, "rebounds_per_game": 7.6, "assists_per_game": 0.8, "fg_pct": 0.510, "three_pt_pct": 0.280, "ft_pct": 0.660, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting big, elite rebounder, lottery pick freshman", "nba_draft_prospect": True},
    {"team_name": "Houston", "player_name": "Joseph Tugler", "position": "F/C", "year": "Jr", "points_per_game": 8.5, "rebounds_per_game": 5.5, "assists_per_game": 1.2, "fg_pct": 0.540, "three_pt_pct": 0.290, "ft_pct": 0.680, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting forward, rim protector, shot blocker, career-high 20 pts in Big 12 title game", "nba_draft_prospect": False},

    # ===================== IDAHO (15-seed South) =====================
    {"team_name": "Idaho", "player_name": "Jackson Rasmussen", "position": "F", "year": "Fr", "points_per_game": 13.9, "rebounds_per_game": 4.4, "assists_per_game": 1.3, "fg_pct": 0.495, "three_pt_pct": 0.309, "ft_pct": 0.701, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, Big Sky All-Tournament Team, top recruit in Idaho", "nba_draft_prospect": False},
    {"team_name": "Idaho", "player_name": "Kolton Mitchell", "position": "G", "year": "So", "points_per_game": 13.7, "rebounds_per_game": 2.7, "assists_per_game": 3.9, "fg_pct": 0.410, "three_pt_pct": 0.370, "ft_pct": 0.780, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting point guard, Big Sky All-Tournament Team, 70 three-pointers made", "nba_draft_prospect": False},
    {"team_name": "Idaho", "player_name": "Isaiah Brickner", "position": "G", "year": "Sr", "points_per_game": 12.1, "rebounds_per_game": 3.5, "assists_per_game": 1.2, "fg_pct": 0.420, "three_pt_pct": 0.370, "ft_pct": 0.800, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "sixth man, Big Sky All-Tournament Team, led team with 23 pts in championship", "nba_draft_prospect": False},
    {"team_name": "Idaho", "player_name": "Brody Rowbury", "position": "F/C", "year": "Sr", "points_per_game": 9.2, "rebounds_per_game": 5.2, "assists_per_game": 0.8, "fg_pct": 0.633, "three_pt_pct": 0.250, "ft_pct": 0.680, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting center, leading rebounder, efficient interior scorer", "nba_draft_prospect": False},
    {"team_name": "Idaho", "player_name": "Biko Johnson", "position": "G", "year": "Sr", "points_per_game": 8.8, "rebounds_per_game": 3.0, "assists_per_game": 1.5, "fg_pct": 0.380, "three_pt_pct": 0.340, "ft_pct": 0.760, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting guard, veteran perimeter presence", "nba_draft_prospect": False},

    # ===================== LEHIGH (16-seed South) =====================
    {"team_name": "Lehigh", "player_name": "Nasir Whitlock", "position": "G", "year": "Jr", "points_per_game": 15.6, "rebounds_per_game": 3.8, "assists_per_game": 2.5, "fg_pct": 0.440, "three_pt_pct": 0.366, "ft_pct": 0.820, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "leading scorer, team captain, First-Team All-Patriot League, half-court buzzer-beater vs Holy Cross", "nba_draft_prospect": False},
    {"team_name": "Lehigh", "player_name": "Tyler Whitney-Sidney", "position": "G", "year": "Sr", "points_per_game": 14.3, "rebounds_per_game": 3.5, "assists_per_game": 2.8, "fg_pct": 0.481, "three_pt_pct": 0.380, "ft_pct": 0.800, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting guard, second-team All-Patriot League, career-high FG%", "nba_draft_prospect": False},
    {"team_name": "Lehigh", "player_name": "Hank Alvey", "position": "F", "year": "So", "points_per_game": 10.8, "rebounds_per_game": 7.1, "assists_per_game": 1.0, "fg_pct": 0.490, "three_pt_pct": 0.310, "ft_pct": 0.700, "is_starter": True, "is_injured": False, "injury_details": None, "role_description": "starting forward, Second-Team All-Patriot League, 30 pts in PL semifinal", "nba_draft_prospect": False},
    {"team_name": "Lehigh", "player_name": "Keith Higgins Jr.", "position": "G", "year": "Sr", "points_per_game": 10.2, "rebounds_per_game": 3.0, "assists_per_game": 2.0, "fg_pct": 0.430, "three_pt_pct": 0.380, "ft_pct": 0.790, "is_starter": True, "is_injured": True, "injury_details": "Season-ending injury; ruled out for remainder of season", "role_description": "starting guard, 17.9 ppg in 12 games before injury", "nba_draft_prospect": False},
    {"team_name": "Lehigh", "player_name": "Jalen Vazquez", "position": "G", "year": "Jr", "points_per_game": 7.5, "rebounds_per_game": 2.2, "assists_per_game": 3.5, "fg_pct": 0.400, "three_pt_pct": 0.340, "ft_pct": 0.750, "is_starter": False, "is_injured": False, "injury_details": None, "role_description": "backup point guard, JUCO transfer from Pasadena City College", "nba_draft_prospect": False},
]
