#!/usr/bin/env python3
"""
Sync last_10_record, current_streak, conference_tourney_result, recent_form_notes
to both bracket_loader.py and Supabase for all 68 teams.
"""
import json
import os
import copy
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent / ".env")


def main():
    from bracket_loader import BRACKET_2026
    from supabase import create_client

    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_KEY")
    client = create_client(url, key)

    # Collect all form updates
    all_updates = {}

    # 1. Import 5-16 seed form data
    try:
        from form_updates import form_updates
        all_updates.update(form_updates)
        print(f"Loaded {len(form_updates)} teams from form_updates.py (5-16 seeds)")
    except ImportError:
        print("WARNING: form_updates.py not found")

    # 2. Import 1-4 seed form data
    try:
        from form_updates_top_seeds import form_updates_top_seeds
        all_updates.update(form_updates_top_seeds)
        print(f"Loaded {len(form_updates_top_seeds)} teams from form_updates_top_seeds.py (1-4 seeds)")
    except ImportError:
        print("WARNING: form_updates_top_seeds.py not found")

    # 3. Import First Four team data
    first_four_teams = []
    first_four_players = []
    try:
        from first_four_data import first_four_teams as ff_teams, first_four_players as ff_players
        first_four_teams = ff_teams
        first_four_players = ff_players
        print(f"Loaded {len(ff_teams)} First Four teams, {len(ff_players)} players")
    except ImportError:
        print("WARNING: first_four_data.py not found")

    print(f"\nTotal form updates: {len(all_updates)} teams")

    # ---- Update bracket_loader.py ----
    bracket = copy.deepcopy(BRACKET_2026)

    # Add First Four teams to bracket
    for ff_team in first_four_teams:
        region = ff_team.get("region")
        if region and region in bracket:
            # Check if team already exists
            existing = [t for t in bracket[region] if t["name"] == ff_team["name"]]
            if not existing:
                bracket[region].append(ff_team)
                print(f"  Added First Four team: {ff_team['name']} to {region}")

    # Apply form updates to bracket
    updated_bracket = 0
    for region, teams in bracket.items():
        for team in teams:
            name = team["name"]
            if name in all_updates:
                for field in ["last_10_record", "current_streak", "conference_tourney_result", "recent_form_notes"]:
                    val = all_updates[name].get(field)
                    if val:
                        team[field] = val
                updated_bracket += 1

    print(f"Updated {updated_bracket} teams in bracket")

    # Write bracket_loader.py
    code = '''#!/usr/bin/env python3
"""
Auto-generated bracket data for March Madness Agent Swarm 2026.
Generated by build_bracket.py from verified Selection Sunday data.
Source: NCAA.com, ESPN, Yahoo Sports (March 15, 2026)

First Four games:
- West 11: NC State vs Texas
- Midwest 16: UMBC vs Howard
- Midwest 11: SMU vs Miami OH
- South 16: Lehigh vs Prairie View A&M
"""

BRACKET_2026 = BRACKET_JSON


def get_all_teams() -> list[dict]:
    """Return flat list of all teams in the bracket."""
    teams = []
    for region, region_teams in BRACKET_2026.items():
        teams.extend(region_teams)
    return teams


def get_region(region_name: str) -> list[dict]:
    """Return teams for a specific region."""
    return BRACKET_2026.get(region_name, [])


def get_matchup(region: str, seed_a: int, seed_b: int) -> tuple[dict, dict]:
    """Get a first-round matchup by region and seeds."""
    region_teams = {t["seed"]: t for t in BRACKET_2026.get(region, [])}
    return region_teams.get(seed_a), region_teams.get(seed_b)


if __name__ == "__main__":
    import json
    print(json.dumps(BRACKET_2026, indent=2))
    print(f"\\nTotal teams: {len(get_all_teams())}")
'''.replace('BRACKET_JSON', json.dumps(bracket, indent=2))

    with open(Path(__file__).parent / "bracket_loader.py", "w") as f:
        f.write(code)
    print(f"Wrote bracket_loader.py ({sum(len(t) for t in bracket.values())} teams)")

    # ---- Update Supabase ----
    # Update form data for existing teams
    supabase_updated = 0
    for name, updates in all_updates.items():
        update_data = {}
        for field in ["last_10_record", "current_streak", "conference_tourney_result", "recent_form_notes"]:
            val = updates.get(field)
            if val:
                update_data[field] = val
        if update_data:
            result = client.table("mm_teams").update(update_data).eq("name", name).execute()
            if result.data:
                supabase_updated += 1

    print(f"Updated {supabase_updated} teams in Supabase (form data)")

    # Insert First Four teams into Supabase
    for ff_team in first_four_teams:
        row = {
            "name": ff_team["name"],
            "seed": ff_team["seed"],
            "region": ff_team["region"],
            "adj_o": ff_team.get("adj_o", 0),
            "adj_d": ff_team.get("adj_d", 0),
            "adj_tempo": ff_team.get("adj_tempo", 0),
            "record": ff_team.get("record", ""),
            "conference": ff_team.get("conference", ""),
            "kenpom_rank": ff_team.get("kenpom_rank", 0),
            "three_pt_pct": ff_team.get("three_pt_pct", 0),
            "last_10_record": ff_team.get("last_10_record", ""),
            "current_streak": ff_team.get("current_streak", ""),
            "conference_tourney_result": ff_team.get("conference_tourney_result", ""),
            "recent_form_notes": ff_team.get("recent_form_notes", ""),
        }
        if ff_team.get("key_players"):
            row["key_players"] = ff_team["key_players"]
        result = client.table("mm_teams").upsert(row, on_conflict="name").execute()
        if result.data:
            print(f"  Inserted First Four team: {ff_team['name']}")

    # Insert First Four players into Supabase
    if first_four_players:
        tournament_id = "3e52e2dd-1c70-441c-b46c-766e7b0ee28f"
        def normalize_pct(val):
            if val is None: return 0.0
            if val > 1.0: return round(val / 100.0, 4)
            return round(val, 4)

        player_rows = []
        for p in first_four_players:
            player_rows.append({
                "tournament_id": tournament_id,
                "team_name": p["team_name"],
                "player_name": p["player_name"],
                "position": p.get("position"),
                "year": p.get("year"),
                "points_per_game": p.get("points_per_game", 0),
                "rebounds_per_game": p.get("rebounds_per_game", 0),
                "assists_per_game": p.get("assists_per_game", 0),
                "fg_pct": normalize_pct(p.get("fg_pct", 0)),
                "three_pt_pct": normalize_pct(p.get("three_pt_pct", 0)),
                "ft_pct": normalize_pct(p.get("ft_pct", 0)),
                "is_starter": p.get("is_starter", False),
                "is_injured": p.get("is_injured", False),
                "injury_details": p.get("injury_details"),
                "is_key_player": True,
                "role_description": p.get("role_description"),
                "nba_draft_prospect": p.get("nba_draft_prospect", False),
            })
        client.table("mm_players").insert(player_rows).execute()
        print(f"  Inserted {len(player_rows)} First Four players")

    # ---- Verify ----
    total = client.table("mm_teams").select("name", count="exact").execute()
    filled = client.table("mm_teams").select("name", count="exact").neq("last_10_record", "").execute()
    print(f"\nSupabase verification:")
    print(f"  Total teams: {total.count}")
    print(f"  Teams with last_10_record: {filled.count}")

    # Show a few examples
    samples = client.table("mm_teams").select("name,last_10_record,current_streak,conference_tourney_result,recent_form_notes").in_("name", ["Duke", "Akron", "Florida", "Texas Tech"]).execute()
    for row in samples.data:
        print(f"\n  {row['name']}:")
        print(f"    last_10: {row['last_10_record']}")
        print(f"    streak: {row['current_streak']}")
        print(f"    conf_tourney: {row['conference_tourney_result'][:80]}")
        print(f"    form: {row['recent_form_notes'][:80]}")


if __name__ == "__main__":
    main()
