west_region_players = [
    # ============================================================
    # NC STATE (11-seed West) — 2025-26 Season
    # ============================================================
    {
        "team_name": "NC State",
        "player_name": "Paul McNeil Jr.",
        "position": "G",
        "year": "So",
        "points_per_game": 13.9,
        "rebounds_per_game": 3.6,
        "assists_per_game": 0.8,
        "fg_pct": 43.5,
        "three_pt_pct": 42.9,
        "ft_pct": 82.4,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting shooting guard and elite perimeter scorer; lethal three-point shooter who set a season high of 47 points",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "NC State",
        "player_name": "Quadir Copeland",
        "position": "G",
        "year": "Sr",
        "points_per_game": 13.9,
        "rebounds_per_game": 3.5,
        "assists_per_game": 6.6,
        "fg_pct": 49.7,
        "three_pt_pct": 39.7,
        "ft_pct": 77.7,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting point guard and floor general; leads team in assists; combo guard with elite passing and scoring ability",
        "nba_draft_prospect": True,
    },
    {
        "team_name": "NC State",
        "player_name": "Ven-Allen Lubin",
        "position": "F",
        "year": "Sr",
        "points_per_game": 13.9,
        "rebounds_per_game": 7.2,
        "assists_per_game": 0.8,
        "fg_pct": 67.6,
        "three_pt_pct": 27.3,
        "ft_pct": 73.9,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting power forward; ultra-efficient interior scorer and leading rebounder; dominant around the rim",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "NC State",
        "player_name": "Darrion Williams",
        "position": "F",
        "year": "Sr",
        "points_per_game": 13.8,
        "rebounds_per_game": 4.6,
        "assists_per_game": 2.8,
        "fg_pct": 41.3,
        "three_pt_pct": 40.1,
        "ft_pct": 76.6,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting wing forward; versatile two-way player and transfer from Texas Tech; strong perimeter shooter and defensive disruptor",
        "nba_draft_prospect": True,
    },
    {
        "team_name": "NC State",
        "player_name": "Tre Holloman",
        "position": "G",
        "year": "Sr",
        "points_per_game": 9.3,
        "rebounds_per_game": 1.8,
        "assists_per_game": 2.0,
        "fg_pct": 42.5,
        "three_pt_pct": 40.8,
        "ft_pct": 81.2,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting guard; sharpshooter from three-point range who provides spacing and backcourt depth",
        "nba_draft_prospect": False,
    },

    # ============================================================
    # GONZAGA (3-seed West) — 2025-26 Season
    # ============================================================
    {
        "team_name": "Gonzaga",
        "player_name": "Graham Ike",
        "position": "F",
        "year": "Sr",
        "points_per_game": 19.7,
        "rebounds_per_game": 8.2,
        "assists_per_game": 2.4,
        "fg_pct": 57.3,
        "three_pt_pct": 34.8,
        "ft_pct": 78.7,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting power forward and team's leading scorer; dominant low-post scorer and elite rebounder; All-WCC first team",
        "nba_draft_prospect": True,
    },
    {
        "team_name": "Gonzaga",
        "player_name": "Braden Huff",
        "position": "F",
        "year": "Jr",
        "points_per_game": 17.8,
        "rebounds_per_game": 5.6,
        "assists_per_game": 1.5,
        "fg_pct": 66.2,
        "three_pt_pct": 33.3,
        "ft_pct": 57.5,
        "is_starter": True,
        "is_injured": True,
        "injury_details": "Dislocated kneecap suffered Jan. 15; OUT for first weekend of NCAA Tournament per coach Mark Few",
        "role_description": "Starting forward; highly efficient scorer around the rim; missed final 15 games due to knee injury",
        "nba_draft_prospect": True,
    },
    {
        "team_name": "Gonzaga",
        "player_name": "Tyon Grant-Foster",
        "position": "G",
        "year": "Sr",
        "points_per_game": 11.2,
        "rebounds_per_game": 5.0,
        "assists_per_game": 1.2,
        "fg_pct": 48.1,
        "three_pt_pct": 25.8,
        "ft_pct": 60.1,
        "is_starter": False,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Sixth man and key reserve wing; athletic scorer who stepped into larger role after Huff injury; strong rebounder for a guard",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Gonzaga",
        "player_name": "Mario Saint-Supery",
        "position": "G",
        "year": "Fr",
        "points_per_game": 8.6,
        "rebounds_per_game": 2.8,
        "assists_per_game": 3.6,
        "fg_pct": 42.4,
        "three_pt_pct": 43.4,
        "ft_pct": 87.1,
        "is_starter": False,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Freshman guard splitting time between bench and starting lineup; elite three-point and free throw shooter; solid playmaker",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Gonzaga",
        "player_name": "Davis Fogle",
        "position": "G",
        "year": "Fr",
        "points_per_game": 8.4,
        "rebounds_per_game": 3.0,
        "assists_per_game": 1.4,
        "fg_pct": 53.3,
        "three_pt_pct": 37.1,
        "ft_pct": 71.7,
        "is_starter": False,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Freshman reserve guard; efficient scorer off the bench with good shooting touch; provides energy and depth",
        "nba_draft_prospect": False,
    },

    # ============================================================
    # KENNESAW STATE (14-seed West) — 2025-26 Season
    # ============================================================
    {
        "team_name": "Kennesaw State",
        "player_name": "Simeon Cottle",
        "position": "G",
        "year": "Sr",
        "points_per_game": 20.2,
        "rebounds_per_game": 2.5,
        "assists_per_game": 3.8,
        "fg_pct": 41.1,
        "three_pt_pct": 37.7,
        "ft_pct": 87.6,
        "is_starter": True,
        "is_injured": True,
        "injury_details": "Suspended indefinitely since Jan. 15 after federal indictment in point-shaving scheme; will not play in tournament",
        "role_description": "Former starting guard and team's leading scorer; elite scorer who averaged 20+ PPG before suspension; unavailable for NCAA Tournament",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Kennesaw State",
        "player_name": "RJ Johnson",
        "position": "G",
        "year": "Jr",
        "points_per_game": 14.5,
        "rebounds_per_game": 3.1,
        "assists_per_game": 4.0,
        "fg_pct": 45.7,
        "three_pt_pct": 43.3,
        "ft_pct": 62.6,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting guard and top available scorer; excellent three-point shooter and playmaker; took over as primary option after Cottle suspension",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Kennesaw State",
        "player_name": "Braedan Lue",
        "position": "F",
        "year": "So",
        "points_per_game": 11.1,
        "rebounds_per_game": 5.4,
        "assists_per_game": 1.2,
        "fg_pct": 46.2,
        "three_pt_pct": 27.7,
        "ft_pct": 71.4,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting forward; versatile scorer and rebounder who provides interior presence and toughness",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Kennesaw State",
        "player_name": "Frankquon Sherman",
        "position": "F",
        "year": "Jr",
        "points_per_game": 10.3,
        "rebounds_per_game": 8.4,
        "assists_per_game": 1.0,
        "fg_pct": 46.7,
        "three_pt_pct": 28.6,
        "ft_pct": 72.5,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting forward and leading rebounder; physical inside presence who dominates the glass",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Kennesaw State",
        "player_name": "Trey Simpson",
        "position": "F",
        "year": "Fr",
        "points_per_game": 9.2,
        "rebounds_per_game": 4.9,
        "assists_per_game": 0.6,
        "fg_pct": 43.4,
        "three_pt_pct": 34.5,
        "ft_pct": 68.3,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting freshman forward; emerging scorer who had 26 points in C-USA Tournament; provides perimeter shooting and rebounding",
        "nba_draft_prospect": False,
    },

    # ============================================================
    # MIAMI FL (7-seed West) — 2025-26 Season
    # ============================================================
    {
        "team_name": "Miami FL",
        "player_name": "Malik Reneau",
        "position": "F",
        "year": "Sr",
        "points_per_game": 18.8,
        "rebounds_per_game": 6.6,
        "assists_per_game": 2.0,
        "fg_pct": 54.9,
        "three_pt_pct": 35.3,
        "ft_pct": 78.8,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting power forward and team's leading scorer; elite interior scorer who added three-point range; Indiana transfer",
        "nba_draft_prospect": True,
    },
    {
        "team_name": "Miami FL",
        "player_name": "Tre Donaldson",
        "position": "G",
        "year": "Sr",
        "points_per_game": 16.5,
        "rebounds_per_game": 3.5,
        "assists_per_game": 5.8,
        "fg_pct": 45.8,
        "three_pt_pct": 34.4,
        "ft_pct": 77.2,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting point guard and primary playmaker; elite passer with multiple double-doubles; strong shooter off the dribble",
        "nba_draft_prospect": True,
    },
    {
        "team_name": "Miami FL",
        "player_name": "Shelton Henderson",
        "position": "F",
        "year": "Fr",
        "points_per_game": 13.7,
        "rebounds_per_game": 4.8,
        "assists_per_game": 2.0,
        "fg_pct": 56.3,
        "three_pt_pct": 27.1,
        "ft_pct": 58.8,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting freshman wing; five-star recruit with NBA-ready frame at 6-6, 240 lbs; athletic and powerful two-way player",
        "nba_draft_prospect": True,
    },
    {
        "team_name": "Miami FL",
        "player_name": "Tru Washington",
        "position": "G",
        "year": "Jr",
        "points_per_game": 12.1,
        "rebounds_per_game": 3.9,
        "assists_per_game": 1.7,
        "fg_pct": 45.2,
        "three_pt_pct": 36.5,
        "ft_pct": 74.4,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting guard; reliable perimeter shooter and secondary ball-handler; solid all-around contributor",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Miami FL",
        "player_name": "Ernest Udeh Jr.",
        "position": "C",
        "year": "Sr",
        "points_per_game": 6.9,
        "rebounds_per_game": 9.3,
        "assists_per_game": 0.5,
        "fg_pct": 73.5,
        "three_pt_pct": 0.0,
        "ft_pct": 51.2,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting center and elite rebounder; rim protector who leads team in rebounds; extremely efficient finisher around the basket",
        "nba_draft_prospect": False,
    },

    # ============================================================
    # MISSOURI (10-seed West) — 2025-26 Season
    # ============================================================
    {
        "team_name": "Missouri",
        "player_name": "Mark Mitchell",
        "position": "F",
        "year": "Sr",
        "points_per_game": 18.3,
        "rebounds_per_game": 5.3,
        "assists_per_game": 3.6,
        "fg_pct": 55.1,
        "three_pt_pct": 35.6,
        "ft_pct": 66.4,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting power forward and team's leading scorer; athletic combo forward and former Duke 5-star transfer; high-motor two-way player",
        "nba_draft_prospect": True,
    },
    {
        "team_name": "Missouri",
        "player_name": "Jayden Stone",
        "position": "G",
        "year": "Sr",
        "points_per_game": 13.2,
        "rebounds_per_game": 5.0,
        "assists_per_game": 1.9,
        "fg_pct": 48.2,
        "three_pt_pct": 38.2,
        "ft_pct": 80.2,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting guard; missed early games with broken hand but returned for SEC play; strong shooter and rebounder for a guard",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Missouri",
        "player_name": "Trent Pierce",
        "position": "F",
        "year": "Jr",
        "points_per_game": 10.6,
        "rebounds_per_game": 3.8,
        "assists_per_game": 1.1,
        "fg_pct": 49.3,
        "three_pt_pct": 39.8,
        "ft_pct": 72.7,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting forward; missed start of season with undisclosed injury; versatile scorer with strong three-point shooting",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Missouri",
        "player_name": "T.O. Barrett",
        "position": "G",
        "year": "So",
        "points_per_game": 8.9,
        "rebounds_per_game": 2.7,
        "assists_per_game": 3.1,
        "fg_pct": 47.5,
        "three_pt_pct": 21.4,
        "ft_pct": 79.1,
        "is_starter": False,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Backup guard and primary ball-handler off the bench; solid playmaker who contributes scoring and distribution",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Missouri",
        "player_name": "Anthony Robinson II",
        "position": "G",
        "year": "Jr",
        "points_per_game": 8.8,
        "rebounds_per_game": 3.1,
        "assists_per_game": 2.9,
        "fg_pct": 40.4,
        "three_pt_pct": 29.7,
        "ft_pct": 67.0,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting guard; versatile backcourt contributor who provides scoring, rebounding, and playmaking",
        "nba_draft_prospect": False,
    },

    # ============================================================
    # PURDUE (2-seed West) — 2025-26 Season
    # ============================================================
    {
        "team_name": "Purdue",
        "player_name": "Braden Smith",
        "position": "G",
        "year": "Sr",
        "points_per_game": 14.0,
        "rebounds_per_game": 3.6,
        "assists_per_game": 9.0,
        "fg_pct": 44.4,
        "three_pt_pct": 37.3,
        "ft_pct": 81.4,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting point guard and team leader; Bob Cousy Award winner; reigning Big Ten Player of the Year; elite playmaker averaging 9 APG",
        "nba_draft_prospect": True,
    },
    {
        "team_name": "Purdue",
        "player_name": "Fletcher Loyer",
        "position": "G",
        "year": "Sr",
        "points_per_game": 13.8,
        "rebounds_per_game": 2.3,
        "assists_per_game": 2.0,
        "fg_pct": 43.8,
        "three_pt_pct": 41.5,
        "ft_pct": 87.5,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting shooting guard; elite three-point and free throw shooter; provides perimeter scoring punch",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Purdue",
        "player_name": "Trey Kaufman-Renn",
        "position": "F",
        "year": "Sr",
        "points_per_game": 13.4,
        "rebounds_per_game": 8.7,
        "assists_per_game": 2.7,
        "fg_pct": 57.5,
        "three_pt_pct": 15.4,
        "ft_pct": 62.5,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting power forward; first-team All-Big Ten; dominant interior scorer and rebounder with soft touch; had shoulder scare but played in Big Ten Tournament",
        "nba_draft_prospect": True,
    },
    {
        "team_name": "Purdue",
        "player_name": "Oscar Cluff",
        "position": "F",
        "year": "Sr",
        "points_per_game": 10.3,
        "rebounds_per_game": 7.4,
        "assists_per_game": 1.7,
        "fg_pct": 70.1,
        "three_pt_pct": 0.0,
        "ft_pct": 69.9,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting center; ultra-efficient rim finisher with 70% FG; strong rebounder and interior anchor",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Purdue",
        "player_name": "C.J. Cox",
        "position": "G",
        "year": "So",
        "points_per_game": 8.4,
        "rebounds_per_game": 2.6,
        "assists_per_game": 1.3,
        "fg_pct": 44.2,
        "three_pt_pct": 36.9,
        "ft_pct": 84.8,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting guard; sophomore sharpshooter who provides spacing and shot-making alongside Smith and Loyer",
        "nba_draft_prospect": False,
    },

    # ============================================================
    # QUEENS (15-seed West) — 2025-26 Season
    # ============================================================
    {
        "team_name": "Queens",
        "player_name": "Nasir Mann",
        "position": "F",
        "year": "Sr",
        "points_per_game": 13.4,
        "rebounds_per_game": 5.8,
        "assists_per_game": 2.7,
        "fg_pct": 49.5,
        "three_pt_pct": 32.7,
        "ft_pct": 78.0,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting forward and team's leading scorer; versatile do-it-all forward who leads team in multiple categories",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Queens",
        "player_name": "Yoav Berman",
        "position": "F",
        "year": "So",
        "points_per_game": 12.6,
        "rebounds_per_game": 3.9,
        "assists_per_game": 3.7,
        "fg_pct": 42.1,
        "three_pt_pct": 29.9,
        "ft_pct": 78.7,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting forward; skilled playmaking forward who contributes scoring, rebounding, and passing",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Queens",
        "player_name": "Jordan Watford",
        "position": "G",
        "year": "Fr",
        "points_per_game": 11.9,
        "rebounds_per_game": 2.6,
        "assists_per_game": 3.8,
        "fg_pct": 59.9,
        "three_pt_pct": 37.5,
        "ft_pct": 78.0,
        "is_starter": False,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Freshman guard and key reserve; ultra-efficient scorer off the bench with elite FG%; strong playmaker",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Queens",
        "player_name": "Chris Ashby",
        "position": "G",
        "year": "Sr",
        "points_per_game": 11.7,
        "rebounds_per_game": 2.0,
        "assists_per_game": 1.5,
        "fg_pct": 36.9,
        "three_pt_pct": 37.5,
        "ft_pct": 87.8,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting shooting guard; volume three-point shooter and elite free throw shooter; provides perimeter scoring",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "Queens",
        "player_name": "Avantae Parker",
        "position": "F",
        "year": "Jr",
        "points_per_game": 11.3,
        "rebounds_per_game": 5.3,
        "assists_per_game": 1.1,
        "fg_pct": 68.5,
        "three_pt_pct": 41.7,
        "ft_pct": 61.7,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting forward; hyper-efficient interior scorer with 68.5% FG; strong rebounder and finisher",
        "nba_draft_prospect": False,
    },

    # ============================================================
    # LIU (16-seed West) — 2025-26 Season
    # ============================================================
    {
        "team_name": "LIU",
        "player_name": "Jamal Fuller",
        "position": "F",
        "year": "Sr",
        "points_per_game": 16.4,
        "rebounds_per_game": 5.5,
        "assists_per_game": 2.5,
        "fg_pct": 52.5,
        "three_pt_pct": 43.8,
        "ft_pct": 77.0,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting forward and team's leading scorer; efficient scorer who can shoot from deep; graduate student and veteran leader",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "LIU",
        "player_name": "Malachi Davis",
        "position": "G",
        "year": "Sr",
        "points_per_game": 14.4,
        "rebounds_per_game": 3.5,
        "assists_per_game": 3.4,
        "fg_pct": 41.8,
        "three_pt_pct": 31.9,
        "ft_pct": 62.1,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting guard and primary ball-handler; dynamic scorer who had season-high 30 points; redshirt senior leader",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "LIU",
        "player_name": "Greg Gordon",
        "position": "G",
        "year": "Sr",
        "points_per_game": 14.1,
        "rebounds_per_game": 5.5,
        "assists_per_game": 2.9,
        "fg_pct": 56.5,
        "three_pt_pct": 20.7,
        "ft_pct": 41.4,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting guard; physical guard who excels driving to the basket; strong rebounder for his position but struggles from the line",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "LIU",
        "player_name": "Jomo Goings",
        "position": "G",
        "year": "Jr",
        "points_per_game": 10.0,
        "rebounds_per_game": 4.5,
        "assists_per_game": 2.2,
        "fg_pct": 41.2,
        "three_pt_pct": 37.8,
        "ft_pct": 83.9,
        "is_starter": True,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Starting guard; well-rounded contributor with solid three-point shooting and rebounding; reliable free throw shooter",
        "nba_draft_prospect": False,
    },
    {
        "team_name": "LIU",
        "player_name": "Mason Porter-Brown",
        "position": "F",
        "year": "Jr",
        "points_per_game": 7.6,
        "rebounds_per_game": 3.2,
        "assists_per_game": 0.6,
        "fg_pct": 47.7,
        "three_pt_pct": 39.5,
        "ft_pct": 71.8,
        "is_starter": False,
        "is_injured": False,
        "injury_details": None,
        "role_description": "Key reserve forward; efficient scorer off the bench with good three-point shooting; provides frontcourt depth",
        "nba_draft_prospect": False,
    },
]
